// Code generated by tools/gen-simd-gosimd/gen.py; DO NOT EDIT.

//go:build goexperiment.simd && go1.27 && !go1.28 && amd64

package helpers

// The -simd=go127 helper set for amd64: every simd_<op> lane/memory helper has a
// simd_g_<op> twin here whose v128 operands are archsimd 128-bit vectors,
// so a generated function body keeps its vectors in SIMD registers from
// one op to the next instead of round-tripping [2]uint64 pairs. Ops the
// generator maps natively are short inlinable method chains; the rest
// bridge to the existing helper through memory (correct, not fast — see
// tools/gen-simd-gosimd/gen.py to promote one).
//
// This file is the only generated-code surface that names simd/archsimd,
// which carries no compatibility promise: a Go release that changes the
// API is absorbed by regenerating this file, never the module code.

import (
	"simd/archsimd"
	"unsafe"
)

// V128 is the vector carrier of the -gosimd backend: a wasm v128 in an
// archsimd register type. Lane views are reinterpretations (As<T>),
// free at the instruction level.
type V128 = archsimd.Uint64x2

// simd_g_const loads a v128 literal the emitter parked in a package-level
// [2]uint64 (a memory operand the compiler folds into the consuming op).
func simd_g_const(p *[2]uint64) V128 { return archsimd.LoadUint64x2Array(p) }

// simd_g_from / simd_g_to bridge between the pair carrier and V128 at
// the boundaries where the pure helpers are reused.
func simd_g_from(p [2]uint64) V128 { return archsimd.LoadUint64x2Array(&p) }

func simd_g_to(v V128) [2]uint64 {
	var p [2]uint64
	v.StoreArray(&p)
	return p
}

// simd_g_ea / simd_g_ea64 are the bounds checks of the memory helpers
// (the shape of simdEA / simdEA64), with the trap raised inline: a
// call to the shared trap function costs the inliner more than the
// whole helper is worth, and the loads would stop inlining.
const simdGOOB = "wasm: v128 memory access out of bounds"

func simd_g_ea(m *Module, addr int32, offset int32, size uint64) uintptr {
	ea := uint64(uint32(addr)) + uint64(uint32(offset))
	if ea+size > m.memSize.Load() {
		panic(simdGOOB)
	}
	return uintptr(ea)
}

func simd_g_ea64(m *Module, addr int64, offset int64, size uint64) uintptr {
	ea := uint64(addr) + uint64(offset)
	end := ea + size
	if ea < uint64(addr) || end < ea || end > m.memSize.Load() {
		panic(simdGOOB)
	}
	return uintptr(ea)
}

// simd_g_i8x16_shuffle2 is i8x16.shuffle with the emitter-normalized
// index vectors (0..15 selects from the respective source, 0x80 zeroes),
// and simd_g_i8x16_swizzle_c the single-source form for patterns that
// touch one operand only.
func simd_g_i8x16_shuffle2(a, b, ia, ib V128) V128 {
	return a.ReshapeToUint8s().PermuteOrZero(ia.ReshapeToUint8s().BitsToInt8()).Or(b.ReshapeToUint8s().PermuteOrZero(ib.ReshapeToUint8s().BitsToInt8())).ReshapeToUint64s()
}

func simd_g_i8x16_swizzle_c(a, idx V128) V128 {
	return a.ReshapeToUint8s().PermuteOrZero(idx.ReshapeToUint8s().BitsToInt8()).ReshapeToUint64s()
}

// The AVX-encoded 128-bit ops (and the AVX2 broadcasts) this file
// inlines need the CPU features at run time; a GOEXPERIMENT=simd build
// of a module therefore targets AVX2 hardware, which every x86-64
// since 2013 has. Fail fast rather than SIGILL mid-function.
func init() {
	if !archsimd.X86.AVX2() {
		panic("wasm2go: this binary was built with GOEXPERIMENT=simd and needs an AVX2 CPU; rebuild without GOEXPERIMENT=simd for older hardware")
	}
}

// simd_g_supported reports whether the archsimd backend can run here.
func simd_g_supported() bool { return archsimd.X86.AVX2() }

var simdGPopcntLUT = [2]uint64{0x0302020102010100, 0x0403030203020201}

var simdGNibbleMask = [2]uint64{0x0f0f0f0f0f0f0f0f, 0x0f0f0f0f0f0f0f0f}

var simdGPackLo = [2]uint64{0x0e0c0a0806040200, 0x8080808080808080}

var simdGPackHi = [2]uint64{0x8080808080808080, 0x0e0c0a0806040200}

var simdGLowHalf = [2]uint64{0xffffffffffffffff, 0x0000000000000000}

var simdGZero = [2]uint64{0x0000000000000000, 0x0000000000000000}

var simdGBits8 = [2]uint64{0x8040201008040201, 0x8040201008040201}

var simdGBits16 = [2]uint64{0x0008000400020001, 0x0080004000200010}

var simdGBits32 = [2]uint64{0x0000000200000001, 0x0000000800000004}

var simdGBits64 = [2]uint64{0x0000000000000001, 0x0000000000000002}

var simdGK_f32_2147483648_0 = [2]uint64{0x4f0000004f000000, 0x4f0000004f000000}

var simdGK_f64_2147483648_0 = [2]uint64{0x41e0000000000000, 0x41e0000000000000}

var simdGK_i16_0x00ff = [2]uint64{0x00ff00ff00ff00ff, 0x00ff00ff00ff00ff}

var simdGK_i16_1 = [2]uint64{0x0001000100010001, 0x0001000100010001}

var simdGK_i16_127 = [2]uint64{0x007f007f007f007f, 0x007f007f007f007f}

var simdGK_i16_255 = [2]uint64{0x00ff00ff00ff00ff, 0x00ff00ff00ff00ff}

var simdGK_i16_m0x8000 = [2]uint64{0x8000800080008000, 0x8000800080008000}

var simdGK_i16_m128 = [2]uint64{0xff80ff80ff80ff80, 0xff80ff80ff80ff80}

var simdGK_i16_m256 = [2]uint64{0xff00ff00ff00ff00, 0xff00ff00ff00ff00}

var simdGK_i32_0x10000 = [2]uint64{0x0001000000010000, 0x0001000000010000}

var simdGK_i32_0x4000 = [2]uint64{0x0000400000004000, 0x0000400000004000}

var simdGK_i8_1 = [2]uint64{0x0101010101010101, 0x0101010101010101}

var simdGK_u32_0x7fc00000 = [2]uint64{0x7fc000007fc00000, 0x7fc000007fc00000}

var simdGK_u32_0x7fffffff = [2]uint64{0x7fffffff7fffffff, 0x7fffffff7fffffff}

var simdGK_u64_0x7ff8000000000000 = [2]uint64{0x7ff8000000000000, 0x7ff8000000000000}

var simdGK_u8_1 = [2]uint64{0x0101010101010101, 0x0101010101010101}

var simdGK_u8_112 = [2]uint64{0x7070707070707070, 0x7070707070707070}

var simdGK_u8_16 = [2]uint64{0x1010101010101010, 0x1010101010101010}

func simd_g_i8x16_shuffle(a V128, b V128, pat V128) V128 {
	p := pat.ReshapeToUint8s()
	ia := p.AddSaturated(archsimd.LoadUint64x2Array(&simdGK_u8_112).ReshapeToUint8s()).ReshapeToUint64s().ReshapeToUint8s().BitsToInt8()
	ib := p.Sub(archsimd.LoadUint64x2Array(&simdGK_u8_16).ReshapeToUint8s()).AddSaturated(archsimd.LoadUint64x2Array(&simdGK_u8_112).ReshapeToUint8s()).ReshapeToUint64s().ReshapeToUint8s().BitsToInt8()
	return a.ReshapeToUint8s().PermuteOrZero(ia).Or(b.ReshapeToUint8s().PermuteOrZero(ib)).ReshapeToUint64s()
}

func simd_g_i8x16_swizzle(a V128, s V128) V128 {
	return a.ReshapeToUint8s().PermuteOrZero(s.ReshapeToUint8s().AddSaturated(archsimd.LoadUint64x2Array(&simdGK_u8_112).ReshapeToUint8s()).ReshapeToUint64s().ReshapeToUint8s().BitsToInt8()).ReshapeToUint64s()
}

func simd_g_i8x16_splat(x int32) V128 {
	return archsimd.BroadcastInt8x16(int8(x)).ToBits().ReshapeToUint64s()
}

func simd_g_i16x8_splat(x int32) V128 {
	return archsimd.BroadcastInt16x8(int16(x)).ToBits().ReshapeToUint64s()
}

func simd_g_i32x4_splat(x int32) V128 {
	return archsimd.BroadcastInt32x4(x).ToBits().ReshapeToUint64s()
}

func simd_g_i64x2_splat(x int64) V128 {
	return archsimd.BroadcastInt64x2(x).ToBits()
}

func simd_g_f32x4_splat(x float32) V128 {
	return archsimd.BroadcastFloat32x4(x).ToBits().ReshapeToUint64s()
}

func simd_g_f64x2_splat(x float64) V128 {
	return archsimd.BroadcastFloat64x2(x).ToBits()
}

func simd_g_i8x16_extract_lane_s_l0(v V128) int32 {
	return int32(v.ReshapeToUint8s().BitsToInt8().GetElem(0))
}

func simd_g_i8x16_extract_lane_s_l1(v V128) int32 {
	return int32(v.ReshapeToUint8s().BitsToInt8().GetElem(1))
}

func simd_g_i8x16_extract_lane_s_l2(v V128) int32 {
	return int32(v.ReshapeToUint8s().BitsToInt8().GetElem(2))
}

func simd_g_i8x16_extract_lane_s_l3(v V128) int32 {
	return int32(v.ReshapeToUint8s().BitsToInt8().GetElem(3))
}

func simd_g_i8x16_extract_lane_s_l4(v V128) int32 {
	return int32(v.ReshapeToUint8s().BitsToInt8().GetElem(4))
}

func simd_g_i8x16_extract_lane_s_l5(v V128) int32 {
	return int32(v.ReshapeToUint8s().BitsToInt8().GetElem(5))
}

func simd_g_i8x16_extract_lane_s_l6(v V128) int32 {
	return int32(v.ReshapeToUint8s().BitsToInt8().GetElem(6))
}

func simd_g_i8x16_extract_lane_s_l7(v V128) int32 {
	return int32(v.ReshapeToUint8s().BitsToInt8().GetElem(7))
}

func simd_g_i8x16_extract_lane_s_l8(v V128) int32 {
	return int32(v.ReshapeToUint8s().BitsToInt8().GetElem(8))
}

func simd_g_i8x16_extract_lane_s_l9(v V128) int32 {
	return int32(v.ReshapeToUint8s().BitsToInt8().GetElem(9))
}

func simd_g_i8x16_extract_lane_s_l10(v V128) int32 {
	return int32(v.ReshapeToUint8s().BitsToInt8().GetElem(10))
}

func simd_g_i8x16_extract_lane_s_l11(v V128) int32 {
	return int32(v.ReshapeToUint8s().BitsToInt8().GetElem(11))
}

func simd_g_i8x16_extract_lane_s_l12(v V128) int32 {
	return int32(v.ReshapeToUint8s().BitsToInt8().GetElem(12))
}

func simd_g_i8x16_extract_lane_s_l13(v V128) int32 {
	return int32(v.ReshapeToUint8s().BitsToInt8().GetElem(13))
}

func simd_g_i8x16_extract_lane_s_l14(v V128) int32 {
	return int32(v.ReshapeToUint8s().BitsToInt8().GetElem(14))
}

func simd_g_i8x16_extract_lane_s_l15(v V128) int32 {
	return int32(v.ReshapeToUint8s().BitsToInt8().GetElem(15))
}

func simd_g_i8x16_extract_lane_u_l0(v V128) int32 {
	return int32(v.ReshapeToUint8s().GetElem(0))
}

func simd_g_i8x16_extract_lane_u_l1(v V128) int32 {
	return int32(v.ReshapeToUint8s().GetElem(1))
}

func simd_g_i8x16_extract_lane_u_l2(v V128) int32 {
	return int32(v.ReshapeToUint8s().GetElem(2))
}

func simd_g_i8x16_extract_lane_u_l3(v V128) int32 {
	return int32(v.ReshapeToUint8s().GetElem(3))
}

func simd_g_i8x16_extract_lane_u_l4(v V128) int32 {
	return int32(v.ReshapeToUint8s().GetElem(4))
}

func simd_g_i8x16_extract_lane_u_l5(v V128) int32 {
	return int32(v.ReshapeToUint8s().GetElem(5))
}

func simd_g_i8x16_extract_lane_u_l6(v V128) int32 {
	return int32(v.ReshapeToUint8s().GetElem(6))
}

func simd_g_i8x16_extract_lane_u_l7(v V128) int32 {
	return int32(v.ReshapeToUint8s().GetElem(7))
}

func simd_g_i8x16_extract_lane_u_l8(v V128) int32 {
	return int32(v.ReshapeToUint8s().GetElem(8))
}

func simd_g_i8x16_extract_lane_u_l9(v V128) int32 {
	return int32(v.ReshapeToUint8s().GetElem(9))
}

func simd_g_i8x16_extract_lane_u_l10(v V128) int32 {
	return int32(v.ReshapeToUint8s().GetElem(10))
}

func simd_g_i8x16_extract_lane_u_l11(v V128) int32 {
	return int32(v.ReshapeToUint8s().GetElem(11))
}

func simd_g_i8x16_extract_lane_u_l12(v V128) int32 {
	return int32(v.ReshapeToUint8s().GetElem(12))
}

func simd_g_i8x16_extract_lane_u_l13(v V128) int32 {
	return int32(v.ReshapeToUint8s().GetElem(13))
}

func simd_g_i8x16_extract_lane_u_l14(v V128) int32 {
	return int32(v.ReshapeToUint8s().GetElem(14))
}

func simd_g_i8x16_extract_lane_u_l15(v V128) int32 {
	return int32(v.ReshapeToUint8s().GetElem(15))
}

func simd_g_i8x16_replace_lane_l0(v V128, x int32) V128 {
	return v.ReshapeToUint8s().BitsToInt8().SetElem(0, int8(x)).ToBits().ReshapeToUint64s()
}

func simd_g_i8x16_replace_lane_l1(v V128, x int32) V128 {
	return v.ReshapeToUint8s().BitsToInt8().SetElem(1, int8(x)).ToBits().ReshapeToUint64s()
}

func simd_g_i8x16_replace_lane_l2(v V128, x int32) V128 {
	return v.ReshapeToUint8s().BitsToInt8().SetElem(2, int8(x)).ToBits().ReshapeToUint64s()
}

func simd_g_i8x16_replace_lane_l3(v V128, x int32) V128 {
	return v.ReshapeToUint8s().BitsToInt8().SetElem(3, int8(x)).ToBits().ReshapeToUint64s()
}

func simd_g_i8x16_replace_lane_l4(v V128, x int32) V128 {
	return v.ReshapeToUint8s().BitsToInt8().SetElem(4, int8(x)).ToBits().ReshapeToUint64s()
}

func simd_g_i8x16_replace_lane_l5(v V128, x int32) V128 {
	return v.ReshapeToUint8s().BitsToInt8().SetElem(5, int8(x)).ToBits().ReshapeToUint64s()
}

func simd_g_i8x16_replace_lane_l6(v V128, x int32) V128 {
	return v.ReshapeToUint8s().BitsToInt8().SetElem(6, int8(x)).ToBits().ReshapeToUint64s()
}

func simd_g_i8x16_replace_lane_l7(v V128, x int32) V128 {
	return v.ReshapeToUint8s().BitsToInt8().SetElem(7, int8(x)).ToBits().ReshapeToUint64s()
}

func simd_g_i8x16_replace_lane_l8(v V128, x int32) V128 {
	return v.ReshapeToUint8s().BitsToInt8().SetElem(8, int8(x)).ToBits().ReshapeToUint64s()
}

func simd_g_i8x16_replace_lane_l9(v V128, x int32) V128 {
	return v.ReshapeToUint8s().BitsToInt8().SetElem(9, int8(x)).ToBits().ReshapeToUint64s()
}

func simd_g_i8x16_replace_lane_l10(v V128, x int32) V128 {
	return v.ReshapeToUint8s().BitsToInt8().SetElem(10, int8(x)).ToBits().ReshapeToUint64s()
}

func simd_g_i8x16_replace_lane_l11(v V128, x int32) V128 {
	return v.ReshapeToUint8s().BitsToInt8().SetElem(11, int8(x)).ToBits().ReshapeToUint64s()
}

func simd_g_i8x16_replace_lane_l12(v V128, x int32) V128 {
	return v.ReshapeToUint8s().BitsToInt8().SetElem(12, int8(x)).ToBits().ReshapeToUint64s()
}

func simd_g_i8x16_replace_lane_l13(v V128, x int32) V128 {
	return v.ReshapeToUint8s().BitsToInt8().SetElem(13, int8(x)).ToBits().ReshapeToUint64s()
}

func simd_g_i8x16_replace_lane_l14(v V128, x int32) V128 {
	return v.ReshapeToUint8s().BitsToInt8().SetElem(14, int8(x)).ToBits().ReshapeToUint64s()
}

func simd_g_i8x16_replace_lane_l15(v V128, x int32) V128 {
	return v.ReshapeToUint8s().BitsToInt8().SetElem(15, int8(x)).ToBits().ReshapeToUint64s()
}

func simd_g_i16x8_extract_lane_s_l0(v V128) int32 {
	return int32(v.ReshapeToUint16s().BitsToInt16().GetElem(0))
}

func simd_g_i16x8_extract_lane_s_l1(v V128) int32 {
	return int32(v.ReshapeToUint16s().BitsToInt16().GetElem(1))
}

func simd_g_i16x8_extract_lane_s_l2(v V128) int32 {
	return int32(v.ReshapeToUint16s().BitsToInt16().GetElem(2))
}

func simd_g_i16x8_extract_lane_s_l3(v V128) int32 {
	return int32(v.ReshapeToUint16s().BitsToInt16().GetElem(3))
}

func simd_g_i16x8_extract_lane_s_l4(v V128) int32 {
	return int32(v.ReshapeToUint16s().BitsToInt16().GetElem(4))
}

func simd_g_i16x8_extract_lane_s_l5(v V128) int32 {
	return int32(v.ReshapeToUint16s().BitsToInt16().GetElem(5))
}

func simd_g_i16x8_extract_lane_s_l6(v V128) int32 {
	return int32(v.ReshapeToUint16s().BitsToInt16().GetElem(6))
}

func simd_g_i16x8_extract_lane_s_l7(v V128) int32 {
	return int32(v.ReshapeToUint16s().BitsToInt16().GetElem(7))
}

func simd_g_i16x8_extract_lane_u_l0(v V128) int32 {
	return int32(v.ReshapeToUint16s().GetElem(0))
}

func simd_g_i16x8_extract_lane_u_l1(v V128) int32 {
	return int32(v.ReshapeToUint16s().GetElem(1))
}

func simd_g_i16x8_extract_lane_u_l2(v V128) int32 {
	return int32(v.ReshapeToUint16s().GetElem(2))
}

func simd_g_i16x8_extract_lane_u_l3(v V128) int32 {
	return int32(v.ReshapeToUint16s().GetElem(3))
}

func simd_g_i16x8_extract_lane_u_l4(v V128) int32 {
	return int32(v.ReshapeToUint16s().GetElem(4))
}

func simd_g_i16x8_extract_lane_u_l5(v V128) int32 {
	return int32(v.ReshapeToUint16s().GetElem(5))
}

func simd_g_i16x8_extract_lane_u_l6(v V128) int32 {
	return int32(v.ReshapeToUint16s().GetElem(6))
}

func simd_g_i16x8_extract_lane_u_l7(v V128) int32 {
	return int32(v.ReshapeToUint16s().GetElem(7))
}

func simd_g_i16x8_replace_lane_l0(v V128, x int32) V128 {
	return v.ReshapeToUint16s().BitsToInt16().SetElem(0, int16(x)).ToBits().ReshapeToUint64s()
}

func simd_g_i16x8_replace_lane_l1(v V128, x int32) V128 {
	return v.ReshapeToUint16s().BitsToInt16().SetElem(1, int16(x)).ToBits().ReshapeToUint64s()
}

func simd_g_i16x8_replace_lane_l2(v V128, x int32) V128 {
	return v.ReshapeToUint16s().BitsToInt16().SetElem(2, int16(x)).ToBits().ReshapeToUint64s()
}

func simd_g_i16x8_replace_lane_l3(v V128, x int32) V128 {
	return v.ReshapeToUint16s().BitsToInt16().SetElem(3, int16(x)).ToBits().ReshapeToUint64s()
}

func simd_g_i16x8_replace_lane_l4(v V128, x int32) V128 {
	return v.ReshapeToUint16s().BitsToInt16().SetElem(4, int16(x)).ToBits().ReshapeToUint64s()
}

func simd_g_i16x8_replace_lane_l5(v V128, x int32) V128 {
	return v.ReshapeToUint16s().BitsToInt16().SetElem(5, int16(x)).ToBits().ReshapeToUint64s()
}

func simd_g_i16x8_replace_lane_l6(v V128, x int32) V128 {
	return v.ReshapeToUint16s().BitsToInt16().SetElem(6, int16(x)).ToBits().ReshapeToUint64s()
}

func simd_g_i16x8_replace_lane_l7(v V128, x int32) V128 {
	return v.ReshapeToUint16s().BitsToInt16().SetElem(7, int16(x)).ToBits().ReshapeToUint64s()
}

func simd_g_i32x4_extract_lane_l0(v V128) int32 {
	return v.ReshapeToUint32s().BitsToInt32().GetElem(0)
}

func simd_g_i32x4_extract_lane_l1(v V128) int32 {
	return v.ReshapeToUint32s().BitsToInt32().GetElem(1)
}

func simd_g_i32x4_extract_lane_l2(v V128) int32 {
	return v.ReshapeToUint32s().BitsToInt32().GetElem(2)
}

func simd_g_i32x4_extract_lane_l3(v V128) int32 {
	return v.ReshapeToUint32s().BitsToInt32().GetElem(3)
}

func simd_g_i32x4_replace_lane_l0(v V128, x int32) V128 {
	return v.ReshapeToUint32s().BitsToInt32().SetElem(0, x).ToBits().ReshapeToUint64s()
}

func simd_g_i32x4_replace_lane_l1(v V128, x int32) V128 {
	return v.ReshapeToUint32s().BitsToInt32().SetElem(1, x).ToBits().ReshapeToUint64s()
}

func simd_g_i32x4_replace_lane_l2(v V128, x int32) V128 {
	return v.ReshapeToUint32s().BitsToInt32().SetElem(2, x).ToBits().ReshapeToUint64s()
}

func simd_g_i32x4_replace_lane_l3(v V128, x int32) V128 {
	return v.ReshapeToUint32s().BitsToInt32().SetElem(3, x).ToBits().ReshapeToUint64s()
}

func simd_g_i64x2_extract_lane_l0(v V128) int64 {
	return v.BitsToInt64().GetElem(0)
}

func simd_g_i64x2_extract_lane_l1(v V128) int64 {
	return v.BitsToInt64().GetElem(1)
}

func simd_g_i64x2_replace_lane_l0(v V128, x int64) V128 {
	return v.BitsToInt64().SetElem(0, x).ToBits()
}

func simd_g_i64x2_replace_lane_l1(v V128, x int64) V128 {
	return v.BitsToInt64().SetElem(1, x).ToBits()
}

func simd_g_f32x4_extract_lane_l0(v V128) float32 {
	return v.ReshapeToUint32s().BitsToFloat32().GetElem(0)
}

func simd_g_f32x4_extract_lane_l1(v V128) float32 {
	return v.ReshapeToUint32s().BitsToFloat32().GetElem(1)
}

func simd_g_f32x4_extract_lane_l2(v V128) float32 {
	return v.ReshapeToUint32s().BitsToFloat32().GetElem(2)
}

func simd_g_f32x4_extract_lane_l3(v V128) float32 {
	return v.ReshapeToUint32s().BitsToFloat32().GetElem(3)
}

func simd_g_f32x4_replace_lane_l0(v V128, x float32) V128 {
	return v.ReshapeToUint32s().BitsToFloat32().SetElem(0, x).ToBits().ReshapeToUint64s()
}

func simd_g_f32x4_replace_lane_l1(v V128, x float32) V128 {
	return v.ReshapeToUint32s().BitsToFloat32().SetElem(1, x).ToBits().ReshapeToUint64s()
}

func simd_g_f32x4_replace_lane_l2(v V128, x float32) V128 {
	return v.ReshapeToUint32s().BitsToFloat32().SetElem(2, x).ToBits().ReshapeToUint64s()
}

func simd_g_f32x4_replace_lane_l3(v V128, x float32) V128 {
	return v.ReshapeToUint32s().BitsToFloat32().SetElem(3, x).ToBits().ReshapeToUint64s()
}

func simd_g_f64x2_extract_lane_l0(v V128) float64 {
	return v.BitsToFloat64().GetElem(0)
}

func simd_g_f64x2_extract_lane_l1(v V128) float64 {
	return v.BitsToFloat64().GetElem(1)
}

func simd_g_f64x2_replace_lane_l0(v V128, x float64) V128 {
	return v.BitsToFloat64().SetElem(0, x).ToBits()
}

func simd_g_f64x2_replace_lane_l1(v V128, x float64) V128 {
	return v.BitsToFloat64().SetElem(1, x).ToBits()
}

func simd_g_v128_not(a V128) V128 {
	return a.Not()
}

func simd_g_v128_and(a V128, b V128) V128 {
	return a.And(b)
}

func simd_g_v128_andnot(a V128, b V128) V128 {
	return a.AndNot(b)
}

func simd_g_v128_or(a V128, b V128) V128 {
	return a.Or(b)
}

func simd_g_v128_xor(a V128, b V128) V128 {
	return a.Xor(b)
}

func simd_g_v128_bitselect(a V128, b V128, c V128) V128 {
	return a.And(c).Or(b.AndNot(c))
}

func simd_g_f16x4_cvt_bits(a V128) int64 {
	p_a := simd_g_to(a)
	return simd_f16x4_cvt_bits(p_a)
}

func simd_g_v128_any_true(a V128) int32 {
	if a.IsZero() {
		return 0
	}
	return 1
}

func simd_g_i8x16_eq(a V128, b V128) V128 {
	return a.ReshapeToUint8s().BitsToInt8().Equal(b.ReshapeToUint8s().BitsToInt8()).ToInt8x16().ToBits().ReshapeToUint64s()
}

func simd_g_i8x16_ne(a V128, b V128) V128 {
	return a.ReshapeToUint8s().BitsToInt8().NotEqual(b.ReshapeToUint8s().BitsToInt8()).ToInt8x16().ToBits().ReshapeToUint64s()
}

func simd_g_i8x16_lt_s(a V128, b V128) V128 {
	return a.ReshapeToUint8s().BitsToInt8().Less(b.ReshapeToUint8s().BitsToInt8()).ToInt8x16().ToBits().ReshapeToUint64s()
}

func simd_g_i8x16_lt_u(a V128, b V128) V128 {
	return a.ReshapeToUint8s().Less(b.ReshapeToUint8s()).ToInt8x16().ToBits().ReshapeToUint64s()
}

func simd_g_i8x16_gt_s(a V128, b V128) V128 {
	return a.ReshapeToUint8s().BitsToInt8().Greater(b.ReshapeToUint8s().BitsToInt8()).ToInt8x16().ToBits().ReshapeToUint64s()
}

func simd_g_i8x16_gt_u(a V128, b V128) V128 {
	return a.ReshapeToUint8s().Greater(b.ReshapeToUint8s()).ToInt8x16().ToBits().ReshapeToUint64s()
}

func simd_g_i8x16_le_s(a V128, b V128) V128 {
	return a.ReshapeToUint8s().BitsToInt8().LessEqual(b.ReshapeToUint8s().BitsToInt8()).ToInt8x16().ToBits().ReshapeToUint64s()
}

func simd_g_i8x16_le_u(a V128, b V128) V128 {
	return a.ReshapeToUint8s().LessEqual(b.ReshapeToUint8s()).ToInt8x16().ToBits().ReshapeToUint64s()
}

func simd_g_i8x16_ge_s(a V128, b V128) V128 {
	return a.ReshapeToUint8s().BitsToInt8().GreaterEqual(b.ReshapeToUint8s().BitsToInt8()).ToInt8x16().ToBits().ReshapeToUint64s()
}

func simd_g_i8x16_ge_u(a V128, b V128) V128 {
	return a.ReshapeToUint8s().GreaterEqual(b.ReshapeToUint8s()).ToInt8x16().ToBits().ReshapeToUint64s()
}

func simd_g_i16x8_eq(a V128, b V128) V128 {
	return a.ReshapeToUint16s().BitsToInt16().Equal(b.ReshapeToUint16s().BitsToInt16()).ToInt16x8().ToBits().ReshapeToUint64s()
}

func simd_g_i16x8_ne(a V128, b V128) V128 {
	return a.ReshapeToUint16s().BitsToInt16().NotEqual(b.ReshapeToUint16s().BitsToInt16()).ToInt16x8().ToBits().ReshapeToUint64s()
}

func simd_g_i16x8_lt_s(a V128, b V128) V128 {
	return a.ReshapeToUint16s().BitsToInt16().Less(b.ReshapeToUint16s().BitsToInt16()).ToInt16x8().ToBits().ReshapeToUint64s()
}

func simd_g_i16x8_lt_u(a V128, b V128) V128 {
	return a.ReshapeToUint16s().Less(b.ReshapeToUint16s()).ToInt16x8().ToBits().ReshapeToUint64s()
}

func simd_g_i16x8_gt_s(a V128, b V128) V128 {
	return a.ReshapeToUint16s().BitsToInt16().Greater(b.ReshapeToUint16s().BitsToInt16()).ToInt16x8().ToBits().ReshapeToUint64s()
}

func simd_g_i16x8_gt_u(a V128, b V128) V128 {
	return a.ReshapeToUint16s().Greater(b.ReshapeToUint16s()).ToInt16x8().ToBits().ReshapeToUint64s()
}

func simd_g_i16x8_le_s(a V128, b V128) V128 {
	return a.ReshapeToUint16s().BitsToInt16().LessEqual(b.ReshapeToUint16s().BitsToInt16()).ToInt16x8().ToBits().ReshapeToUint64s()
}

func simd_g_i16x8_le_u(a V128, b V128) V128 {
	return a.ReshapeToUint16s().LessEqual(b.ReshapeToUint16s()).ToInt16x8().ToBits().ReshapeToUint64s()
}

func simd_g_i16x8_ge_s(a V128, b V128) V128 {
	return a.ReshapeToUint16s().BitsToInt16().GreaterEqual(b.ReshapeToUint16s().BitsToInt16()).ToInt16x8().ToBits().ReshapeToUint64s()
}

func simd_g_i16x8_ge_u(a V128, b V128) V128 {
	return a.ReshapeToUint16s().GreaterEqual(b.ReshapeToUint16s()).ToInt16x8().ToBits().ReshapeToUint64s()
}

func simd_g_i32x4_eq(a V128, b V128) V128 {
	return a.ReshapeToUint32s().BitsToInt32().Equal(b.ReshapeToUint32s().BitsToInt32()).ToInt32x4().ToBits().ReshapeToUint64s()
}

func simd_g_i32x4_ne(a V128, b V128) V128 {
	return a.ReshapeToUint32s().BitsToInt32().NotEqual(b.ReshapeToUint32s().BitsToInt32()).ToInt32x4().ToBits().ReshapeToUint64s()
}

func simd_g_i32x4_lt_s(a V128, b V128) V128 {
	return a.ReshapeToUint32s().BitsToInt32().Less(b.ReshapeToUint32s().BitsToInt32()).ToInt32x4().ToBits().ReshapeToUint64s()
}

func simd_g_i32x4_lt_u(a V128, b V128) V128 {
	return a.ReshapeToUint32s().Less(b.ReshapeToUint32s()).ToInt32x4().ToBits().ReshapeToUint64s()
}

func simd_g_i32x4_gt_s(a V128, b V128) V128 {
	return a.ReshapeToUint32s().BitsToInt32().Greater(b.ReshapeToUint32s().BitsToInt32()).ToInt32x4().ToBits().ReshapeToUint64s()
}

func simd_g_i32x4_gt_u(a V128, b V128) V128 {
	return a.ReshapeToUint32s().Greater(b.ReshapeToUint32s()).ToInt32x4().ToBits().ReshapeToUint64s()
}

func simd_g_i32x4_le_s(a V128, b V128) V128 {
	return a.ReshapeToUint32s().BitsToInt32().LessEqual(b.ReshapeToUint32s().BitsToInt32()).ToInt32x4().ToBits().ReshapeToUint64s()
}

func simd_g_i32x4_le_u(a V128, b V128) V128 {
	return a.ReshapeToUint32s().LessEqual(b.ReshapeToUint32s()).ToInt32x4().ToBits().ReshapeToUint64s()
}

func simd_g_i32x4_ge_s(a V128, b V128) V128 {
	return a.ReshapeToUint32s().BitsToInt32().GreaterEqual(b.ReshapeToUint32s().BitsToInt32()).ToInt32x4().ToBits().ReshapeToUint64s()
}

func simd_g_i32x4_ge_u(a V128, b V128) V128 {
	return a.ReshapeToUint32s().GreaterEqual(b.ReshapeToUint32s()).ToInt32x4().ToBits().ReshapeToUint64s()
}

func simd_g_i64x2_eq(a V128, b V128) V128 {
	return a.BitsToInt64().Equal(b.BitsToInt64()).ToInt64x2().ToBits()
}

func simd_g_i64x2_ne(a V128, b V128) V128 {
	return a.BitsToInt64().NotEqual(b.BitsToInt64()).ToInt64x2().ToBits()
}

func simd_g_i64x2_lt_s(a V128, b V128) V128 {
	return a.BitsToInt64().Less(b.BitsToInt64()).ToInt64x2().ToBits()
}

func simd_g_i64x2_gt_s(a V128, b V128) V128 {
	return a.BitsToInt64().Greater(b.BitsToInt64()).ToInt64x2().ToBits()
}

func simd_g_i64x2_le_s(a V128, b V128) V128 {
	return a.BitsToInt64().LessEqual(b.BitsToInt64()).ToInt64x2().ToBits()
}

func simd_g_i64x2_ge_s(a V128, b V128) V128 {
	return a.BitsToInt64().GreaterEqual(b.BitsToInt64()).ToInt64x2().ToBits()
}

func simd_g_f32x4_eq(a V128, b V128) V128 {
	return a.ReshapeToUint32s().BitsToFloat32().Equal(b.ReshapeToUint32s().BitsToFloat32()).ToInt32x4().ToBits().ReshapeToUint64s()
}

func simd_g_f32x4_ne(a V128, b V128) V128 {
	return a.ReshapeToUint32s().BitsToFloat32().NotEqual(b.ReshapeToUint32s().BitsToFloat32()).ToInt32x4().ToBits().ReshapeToUint64s()
}

func simd_g_f32x4_lt(a V128, b V128) V128 {
	return a.ReshapeToUint32s().BitsToFloat32().Less(b.ReshapeToUint32s().BitsToFloat32()).ToInt32x4().ToBits().ReshapeToUint64s()
}

func simd_g_f32x4_gt(a V128, b V128) V128 {
	return a.ReshapeToUint32s().BitsToFloat32().Greater(b.ReshapeToUint32s().BitsToFloat32()).ToInt32x4().ToBits().ReshapeToUint64s()
}

func simd_g_f32x4_le(a V128, b V128) V128 {
	return a.ReshapeToUint32s().BitsToFloat32().LessEqual(b.ReshapeToUint32s().BitsToFloat32()).ToInt32x4().ToBits().ReshapeToUint64s()
}

func simd_g_f32x4_ge(a V128, b V128) V128 {
	return a.ReshapeToUint32s().BitsToFloat32().GreaterEqual(b.ReshapeToUint32s().BitsToFloat32()).ToInt32x4().ToBits().ReshapeToUint64s()
}

func simd_g_f64x2_eq(a V128, b V128) V128 {
	return a.BitsToFloat64().Equal(b.BitsToFloat64()).ToInt64x2().ToBits()
}

func simd_g_f64x2_ne(a V128, b V128) V128 {
	return a.BitsToFloat64().NotEqual(b.BitsToFloat64()).ToInt64x2().ToBits()
}

func simd_g_f64x2_lt(a V128, b V128) V128 {
	return a.BitsToFloat64().Less(b.BitsToFloat64()).ToInt64x2().ToBits()
}

func simd_g_f64x2_gt(a V128, b V128) V128 {
	return a.BitsToFloat64().Greater(b.BitsToFloat64()).ToInt64x2().ToBits()
}

func simd_g_f64x2_le(a V128, b V128) V128 {
	return a.BitsToFloat64().LessEqual(b.BitsToFloat64()).ToInt64x2().ToBits()
}

func simd_g_f64x2_ge(a V128, b V128) V128 {
	return a.BitsToFloat64().GreaterEqual(b.BitsToFloat64()).ToInt64x2().ToBits()
}

func simd_g_i8x16_add(a V128, b V128) V128 {
	return a.ReshapeToUint8s().BitsToInt8().Add(b.ReshapeToUint8s().BitsToInt8()).ToBits().ReshapeToUint64s()
}

func simd_g_i8x16_sub(a V128, b V128) V128 {
	return a.ReshapeToUint8s().BitsToInt8().Sub(b.ReshapeToUint8s().BitsToInt8()).ToBits().ReshapeToUint64s()
}

func simd_g_i8x16_min_s(a V128, b V128) V128 {
	return a.ReshapeToUint8s().BitsToInt8().Min(b.ReshapeToUint8s().BitsToInt8()).ToBits().ReshapeToUint64s()
}

func simd_g_i8x16_min_u(a V128, b V128) V128 {
	return a.ReshapeToUint8s().Min(b.ReshapeToUint8s()).ReshapeToUint64s()
}

func simd_g_i8x16_max_s(a V128, b V128) V128 {
	return a.ReshapeToUint8s().BitsToInt8().Max(b.ReshapeToUint8s().BitsToInt8()).ToBits().ReshapeToUint64s()
}

func simd_g_i8x16_max_u(a V128, b V128) V128 {
	return a.ReshapeToUint8s().Max(b.ReshapeToUint8s()).ReshapeToUint64s()
}

func simd_g_i8x16_abs(a V128) V128 {
	return a.ReshapeToUint8s().BitsToInt8().Abs().ToBits().ReshapeToUint64s()
}

func simd_g_i8x16_neg(a V128) V128 {
	return a.ReshapeToUint8s().BitsToInt8().Neg().ToBits().ReshapeToUint64s()
}

func simd_g_i8x16_all_true(a V128) int32 {
	if a.ReshapeToUint8s().BitsToInt8().Equal(archsimd.LoadUint64x2Array(&simdGZero).ReshapeToUint8s().BitsToInt8()).ToBits() == 0 {
		return 1
	}
	return 0
}

func simd_g_i8x16_bitmask(a V128) int32 {
	return int32(a.ReshapeToUint8s().BitsToInt8().Less(archsimd.LoadUint64x2Array(&simdGZero).ReshapeToUint8s().BitsToInt8()).ToBits())
}

func simd_g_i8x16_shl(a V128, s int32) V128 {
	k := uint64(s & 7)
	return a.ReshapeToUint16s().ShiftAllLeft(k).ReshapeToUint64s().ReshapeToUint8s().And(archsimd.BroadcastUint8x16(uint8(0xff << k))).ReshapeToUint64s()
}

func simd_g_i8x16_shr_s(a V128, s int32) V128 {
	k := uint64(s & 7)
	x := a.ReshapeToUint16s().BitsToInt16()
	lo := x.ShiftAllLeft(8).ShiftAllRight(k + 8).And(archsimd.LoadUint64x2Array(&simdGK_i16_0x00ff).ReshapeToUint16s().BitsToInt16())
	hi := x.ShiftAllRight(k).And(archsimd.LoadUint64x2Array(&simdGK_i16_m256).ReshapeToUint16s().BitsToInt16())
	return hi.Or(lo).ToBits().ReshapeToUint64s()
}

func simd_g_i8x16_shr_u(a V128, s int32) V128 {
	k := uint64(s & 7)
	return a.ReshapeToUint16s().ShiftAllRight(k).ReshapeToUint64s().ReshapeToUint8s().And(archsimd.BroadcastUint8x16(uint8(0xff >> k))).ReshapeToUint64s()
}

func simd_g_i16x8_add(a V128, b V128) V128 {
	return a.ReshapeToUint16s().BitsToInt16().Add(b.ReshapeToUint16s().BitsToInt16()).ToBits().ReshapeToUint64s()
}

func simd_g_i16x8_sub(a V128, b V128) V128 {
	return a.ReshapeToUint16s().BitsToInt16().Sub(b.ReshapeToUint16s().BitsToInt16()).ToBits().ReshapeToUint64s()
}

func simd_g_i16x8_mul(a V128, b V128) V128 {
	return a.ReshapeToUint16s().BitsToInt16().Mul(b.ReshapeToUint16s().BitsToInt16()).ToBits().ReshapeToUint64s()
}

func simd_g_i16x8_min_s(a V128, b V128) V128 {
	return a.ReshapeToUint16s().BitsToInt16().Min(b.ReshapeToUint16s().BitsToInt16()).ToBits().ReshapeToUint64s()
}

func simd_g_i16x8_min_u(a V128, b V128) V128 {
	return a.ReshapeToUint16s().Min(b.ReshapeToUint16s()).ReshapeToUint64s()
}

func simd_g_i16x8_max_s(a V128, b V128) V128 {
	return a.ReshapeToUint16s().BitsToInt16().Max(b.ReshapeToUint16s().BitsToInt16()).ToBits().ReshapeToUint64s()
}

func simd_g_i16x8_max_u(a V128, b V128) V128 {
	return a.ReshapeToUint16s().Max(b.ReshapeToUint16s()).ReshapeToUint64s()
}

func simd_g_i16x8_abs(a V128) V128 {
	return a.ReshapeToUint16s().BitsToInt16().Abs().ToBits().ReshapeToUint64s()
}

func simd_g_i16x8_neg(a V128) V128 {
	return a.ReshapeToUint16s().BitsToInt16().Neg().ToBits().ReshapeToUint64s()
}

func simd_g_i16x8_all_true(a V128) int32 {
	if a.ReshapeToUint16s().BitsToInt16().Equal(archsimd.LoadUint64x2Array(&simdGZero).ReshapeToUint16s().BitsToInt16()).ToBits() == 0 {
		return 1
	}
	return 0
}

func simd_g_i16x8_bitmask(a V128) int32 {
	return int32(a.ReshapeToUint16s().BitsToInt16().Less(archsimd.LoadUint64x2Array(&simdGZero).ReshapeToUint16s().BitsToInt16()).ToBits())
}

func simd_g_i16x8_shl(a V128, s int32) V128 {
	return a.ReshapeToUint16s().BitsToInt16().ShiftAllLeft(uint64(s & 15)).ToBits().ReshapeToUint64s()
}

func simd_g_i16x8_shr_s(a V128, s int32) V128 {
	return a.ReshapeToUint16s().BitsToInt16().ShiftAllRight(uint64(s & 15)).ToBits().ReshapeToUint64s()
}

func simd_g_i16x8_shr_u(a V128, s int32) V128 {
	return a.ReshapeToUint16s().ShiftAllRight(uint64(s & 15)).ReshapeToUint64s()
}

func simd_g_i32x4_add(a V128, b V128) V128 {
	return a.ReshapeToUint32s().BitsToInt32().Add(b.ReshapeToUint32s().BitsToInt32()).ToBits().ReshapeToUint64s()
}

func simd_g_i32x4_sub(a V128, b V128) V128 {
	return a.ReshapeToUint32s().BitsToInt32().Sub(b.ReshapeToUint32s().BitsToInt32()).ToBits().ReshapeToUint64s()
}

func simd_g_i32x4_mul(a V128, b V128) V128 {
	return a.ReshapeToUint32s().BitsToInt32().Mul(b.ReshapeToUint32s().BitsToInt32()).ToBits().ReshapeToUint64s()
}

func simd_g_i32x4_min_s(a V128, b V128) V128 {
	return a.ReshapeToUint32s().BitsToInt32().Min(b.ReshapeToUint32s().BitsToInt32()).ToBits().ReshapeToUint64s()
}

func simd_g_i32x4_min_u(a V128, b V128) V128 {
	return a.ReshapeToUint32s().Min(b.ReshapeToUint32s()).ReshapeToUint64s()
}

func simd_g_i32x4_max_s(a V128, b V128) V128 {
	return a.ReshapeToUint32s().BitsToInt32().Max(b.ReshapeToUint32s().BitsToInt32()).ToBits().ReshapeToUint64s()
}

func simd_g_i32x4_max_u(a V128, b V128) V128 {
	return a.ReshapeToUint32s().Max(b.ReshapeToUint32s()).ReshapeToUint64s()
}

func simd_g_i32x4_abs(a V128) V128 {
	return a.ReshapeToUint32s().BitsToInt32().Abs().ToBits().ReshapeToUint64s()
}

func simd_g_i32x4_neg(a V128) V128 {
	return a.ReshapeToUint32s().BitsToInt32().Neg().ToBits().ReshapeToUint64s()
}

func simd_g_i32x4_all_true(a V128) int32 {
	if a.ReshapeToUint32s().BitsToInt32().Equal(archsimd.LoadUint64x2Array(&simdGZero).ReshapeToUint32s().BitsToInt32()).ToBits() == 0 {
		return 1
	}
	return 0
}

func simd_g_i32x4_bitmask(a V128) int32 {
	return int32(a.ReshapeToUint32s().BitsToInt32().Less(archsimd.LoadUint64x2Array(&simdGZero).ReshapeToUint32s().BitsToInt32()).ToBits())
}

func simd_g_i32x4_shl(a V128, s int32) V128 {
	return a.ReshapeToUint32s().BitsToInt32().ShiftAllLeft(uint64(s & 31)).ToBits().ReshapeToUint64s()
}

func simd_g_i32x4_shr_s(a V128, s int32) V128 {
	return a.ReshapeToUint32s().BitsToInt32().ShiftAllRight(uint64(s & 31)).ToBits().ReshapeToUint64s()
}

func simd_g_i32x4_shr_u(a V128, s int32) V128 {
	return a.ReshapeToUint32s().ShiftAllRight(uint64(s & 31)).ReshapeToUint64s()
}

func simd_g_i8x16_add_sat_s(a V128, b V128) V128 {
	return a.ReshapeToUint8s().BitsToInt8().AddSaturated(b.ReshapeToUint8s().BitsToInt8()).ToBits().ReshapeToUint64s()
}

func simd_g_i8x16_add_sat_u(a V128, b V128) V128 {
	return a.ReshapeToUint8s().AddSaturated(b.ReshapeToUint8s()).ReshapeToUint64s()
}

func simd_g_i8x16_sub_sat_s(a V128, b V128) V128 {
	return a.ReshapeToUint8s().BitsToInt8().SubSaturated(b.ReshapeToUint8s().BitsToInt8()).ToBits().ReshapeToUint64s()
}

func simd_g_i8x16_sub_sat_u(a V128, b V128) V128 {
	return a.ReshapeToUint8s().SubSaturated(b.ReshapeToUint8s()).ReshapeToUint64s()
}

func simd_g_i8x16_avgr_u(a V128, b V128) V128 {
	return a.ReshapeToUint8s().Average(b.ReshapeToUint8s()).ReshapeToUint64s()
}

func simd_g_i16x8_add_sat_s(a V128, b V128) V128 {
	return a.ReshapeToUint16s().BitsToInt16().AddSaturated(b.ReshapeToUint16s().BitsToInt16()).ToBits().ReshapeToUint64s()
}

func simd_g_i16x8_add_sat_u(a V128, b V128) V128 {
	return a.ReshapeToUint16s().AddSaturated(b.ReshapeToUint16s()).ReshapeToUint64s()
}

func simd_g_i16x8_sub_sat_s(a V128, b V128) V128 {
	return a.ReshapeToUint16s().BitsToInt16().SubSaturated(b.ReshapeToUint16s().BitsToInt16()).ToBits().ReshapeToUint64s()
}

func simd_g_i16x8_sub_sat_u(a V128, b V128) V128 {
	return a.ReshapeToUint16s().SubSaturated(b.ReshapeToUint16s()).ReshapeToUint64s()
}

func simd_g_i16x8_avgr_u(a V128, b V128) V128 {
	return a.ReshapeToUint16s().Average(b.ReshapeToUint16s()).ReshapeToUint64s()
}

func simd_g_i8x16_popcnt(a V128) V128 {
	lut := archsimd.LoadUint64x2Array(&simdGPopcntLUT).ReshapeToUint8s().BitsToInt8()
	m := archsimd.LoadUint64x2Array(&simdGNibbleMask).ReshapeToUint8s().BitsToInt8()
	lo := a.ReshapeToUint8s().BitsToInt8().And(m)
	hi := a.ReshapeToUint16s().ShiftAllRight(4).ReshapeToUint64s().ReshapeToUint8s().BitsToInt8().And(m)
	return lut.PermuteOrZero(lo).Add(lut.PermuteOrZero(hi)).ToBits().ReshapeToUint64s()
}

func simd_g_i64x2_add(a V128, b V128) V128 {
	return a.BitsToInt64().Add(b.BitsToInt64()).ToBits()
}

func simd_g_i64x2_sub(a V128, b V128) V128 {
	return a.BitsToInt64().Sub(b.BitsToInt64()).ToBits()
}

func simd_g_i64x2_mul(a V128, b V128) V128 {
	x, y := a.ReshapeToUint32s(), b.ReshapeToUint32s()
	lo := x.MulWidenEven(y)
	t1 := a.ShiftAllRight(32).ReshapeToUint32s().MulWidenEven(y)
	t2 := x.MulWidenEven(b.ShiftAllRight(32).ReshapeToUint32s())
	return lo.Add(t1.Add(t2).ShiftAllLeft(32))
}

func simd_g_i64x2_abs(a V128) V128 {
	x, z := a.BitsToInt64(), archsimd.LoadUint64x2Array(&simdGZero).BitsToInt64()
	return x.IfElse(x.GreaterEqual(z), z.Sub(x)).ToBits()
}

func simd_g_i64x2_neg(a V128) V128 {
	return a.BitsToInt64().Neg().ToBits()
}

func simd_g_i64x2_all_true(a V128) int32 {
	if a.BitsToInt64().Equal(archsimd.LoadUint64x2Array(&simdGZero).BitsToInt64()).ToBits() == 0 {
		return 1
	}
	return 0
}

func simd_g_i64x2_bitmask(a V128) int32 {
	return int32(a.BitsToInt64().Less(archsimd.LoadUint64x2Array(&simdGZero).BitsToInt64()).ToBits())
}

func simd_g_i64x2_shl(a V128, s int32) V128 {
	return a.BitsToInt64().ShiftAllLeft(uint64(s & 63)).ToBits()
}

func simd_g_i64x2_shr_s(a V128, s int32) V128 {
	k := uint64(s & 63)
	t := archsimd.BroadcastUint64x2(0x8000000000000000 >> k)
	return a.ShiftAllRight(k).Xor(t).Sub(t)
}

func simd_g_i64x2_shr_u(a V128, s int32) V128 {
	return a.ShiftAllRight(uint64(s & 63))
}

func simd_g_i16x8_q15mulr_sat_s(a V128, b V128) V128 {
	x, y := a.ReshapeToUint16s().BitsToInt16(), b.ReshapeToUint16s().BitsToInt16()
	lo, hi := x.Mul(y), x.MulHigh(y)
	r := archsimd.LoadUint64x2Array(&simdGK_i32_0x4000).ReshapeToUint32s().BitsToInt32()
	p0 := lo.InterleaveLo(hi).ToBits().ReshapeToUint64s().ReshapeToUint32s().BitsToInt32().Add(r).ShiftAllRight(15)
	p1 := lo.InterleaveHi(hi).ToBits().ReshapeToUint64s().ReshapeToUint32s().BitsToInt32().Add(r).ShiftAllRight(15)
	return p0.SaturateToInt16Concat(p1).ToBits().ReshapeToUint64s()
}

func simd_g_i8x16_narrow_i16x8_s(a V128, b V128) V128 {
	x := a.ReshapeToUint16s().BitsToInt16().Max(archsimd.LoadUint64x2Array(&simdGK_i16_m128).ReshapeToUint16s().BitsToInt16()).Min(archsimd.LoadUint64x2Array(&simdGK_i16_127).ReshapeToUint16s().BitsToInt16()).ToBits().ReshapeToUint64s().ReshapeToUint8s().BitsToInt8()
	y := b.ReshapeToUint16s().BitsToInt16().Max(archsimd.LoadUint64x2Array(&simdGK_i16_m128).ReshapeToUint16s().BitsToInt16()).Min(archsimd.LoadUint64x2Array(&simdGK_i16_127).ReshapeToUint16s().BitsToInt16()).ToBits().ReshapeToUint64s().ReshapeToUint8s().BitsToInt8()
	return x.PermuteOrZero(archsimd.LoadUint64x2Array(&simdGPackLo).ReshapeToUint8s().BitsToInt8()).Or(y.PermuteOrZero(archsimd.LoadUint64x2Array(&simdGPackHi).ReshapeToUint8s().BitsToInt8())).ToBits().ReshapeToUint64s()
}

func simd_g_i8x16_narrow_i16x8_u(a V128, b V128) V128 {
	z, m := archsimd.LoadUint64x2Array(&simdGZero).ReshapeToUint16s().BitsToInt16(), archsimd.LoadUint64x2Array(&simdGK_i16_255).ReshapeToUint16s().BitsToInt16()
	x := a.ReshapeToUint16s().BitsToInt16().Max(z).Min(m).ToBits().ReshapeToUint64s().ReshapeToUint8s().BitsToInt8()
	y := b.ReshapeToUint16s().BitsToInt16().Max(z).Min(m).ToBits().ReshapeToUint64s().ReshapeToUint8s().BitsToInt8()
	return x.PermuteOrZero(archsimd.LoadUint64x2Array(&simdGPackLo).ReshapeToUint8s().BitsToInt8()).Or(y.PermuteOrZero(archsimd.LoadUint64x2Array(&simdGPackHi).ReshapeToUint8s().BitsToInt8())).ToBits().ReshapeToUint64s()
}

func simd_g_i16x8_narrow_i32x4_s(a V128, b V128) V128 {
	return a.ReshapeToUint32s().BitsToInt32().SaturateToInt16Concat(b.ReshapeToUint32s().BitsToInt32()).ToBits().ReshapeToUint64s()
}

func simd_g_i16x8_narrow_i32x4_u(a V128, b V128) V128 {
	return a.ReshapeToUint32s().BitsToInt32().SaturateToUint16Concat(b.ReshapeToUint32s().BitsToInt32()).ReshapeToUint64s()
}

func simd_g_i16x8_extend_low_i8x16_s(a V128) V128 {
	return a.ReshapeToUint8s().BitsToInt8().ExtendLo8ToInt16().ToBits().ReshapeToUint64s()
}

func simd_g_i16x8_extend_low_i8x16_u(a V128) V128 {
	return a.ReshapeToUint8s().ExtendLo8ToUint16().ReshapeToUint64s()
}

func simd_g_i16x8_extend_high_i8x16_s(a V128) V128 {
	return a.ReshapeToUint32s().BitsToInt32().PermuteScalars(2, 3, 2, 3).ToBits().ReshapeToUint64s().ReshapeToUint8s().BitsToInt8().ExtendLo8ToInt16().ToBits().ReshapeToUint64s()
}

func simd_g_i16x8_extend_high_i8x16_u(a V128) V128 {
	return a.ReshapeToUint32s().BitsToInt32().PermuteScalars(2, 3, 2, 3).ToBits().ReshapeToUint64s().ReshapeToUint8s().ExtendLo8ToUint16().ReshapeToUint64s()
}

func simd_g_i32x4_extend_low_i16x8_s(a V128) V128 {
	return a.ReshapeToUint16s().BitsToInt16().ExtendLo4ToInt32().ToBits().ReshapeToUint64s()
}

func simd_g_i32x4_extend_low_i16x8_u(a V128) V128 {
	return a.ReshapeToUint16s().ExtendLo4ToUint32().ReshapeToUint64s()
}

func simd_g_i32x4_extend_high_i16x8_s(a V128) V128 {
	return a.ReshapeToUint32s().BitsToInt32().PermuteScalars(2, 3, 2, 3).ToBits().ReshapeToUint64s().ReshapeToUint16s().BitsToInt16().ExtendLo4ToInt32().ToBits().ReshapeToUint64s()
}

func simd_g_i32x4_extend_high_i16x8_u(a V128) V128 {
	return a.ReshapeToUint32s().BitsToInt32().PermuteScalars(2, 3, 2, 3).ToBits().ReshapeToUint64s().ReshapeToUint16s().ExtendLo4ToUint32().ReshapeToUint64s()
}

func simd_g_i64x2_extend_low_i32x4_s(a V128) V128 {
	return a.ReshapeToUint32s().BitsToInt32().ExtendLo2ToInt64().ToBits()
}

func simd_g_i64x2_extend_low_i32x4_u(a V128) V128 {
	return a.ReshapeToUint32s().ExtendLo2ToUint64()
}

func simd_g_i64x2_extend_high_i32x4_s(a V128) V128 {
	return a.ReshapeToUint32s().BitsToInt32().PermuteScalars(2, 3, 2, 3).ExtendLo2ToInt64().ToBits()
}

func simd_g_i64x2_extend_high_i32x4_u(a V128) V128 {
	return a.ReshapeToUint32s().BitsToInt32().PermuteScalars(2, 3, 2, 3).ToBits().ReshapeToUint64s().ReshapeToUint32s().ExtendLo2ToUint64()
}

func simd_g_i16x8_extadd_pairwise_i8x16_s(a V128) V128 {
	return archsimd.LoadUint64x2Array(&simdGK_u8_1).ReshapeToUint8s().DotProductPairsSaturated(a.ReshapeToUint8s().BitsToInt8()).ToBits().ReshapeToUint64s()
}

func simd_g_i16x8_extadd_pairwise_i8x16_u(a V128) V128 {
	return a.ReshapeToUint8s().DotProductPairsSaturated(archsimd.LoadUint64x2Array(&simdGK_i8_1).ReshapeToUint8s().BitsToInt8()).ToBits().ReshapeToUint64s()
}

func simd_g_i32x4_extadd_pairwise_i16x8_s(a V128) V128 {
	return a.ReshapeToUint16s().BitsToInt16().DotProductPairs(archsimd.LoadUint64x2Array(&simdGK_i16_1).ReshapeToUint16s().BitsToInt16()).ToBits().ReshapeToUint64s()
}

func simd_g_i32x4_extadd_pairwise_i16x8_u(a V128) V128 {
	x := a.ReshapeToUint16s().BitsToInt16().Xor(archsimd.LoadUint64x2Array(&simdGK_i16_m0x8000).ReshapeToUint16s().BitsToInt16())
	return x.DotProductPairs(archsimd.LoadUint64x2Array(&simdGK_i16_1).ReshapeToUint16s().BitsToInt16()).Add(archsimd.LoadUint64x2Array(&simdGK_i32_0x10000).ReshapeToUint32s().BitsToInt32()).ToBits().ReshapeToUint64s()
}

func simd_g_i16x8_extmul_low_i8x16_s(a V128, b V128) V128 {
	return a.ReshapeToUint8s().BitsToInt8().ExtendLo8ToInt16().Mul(b.ReshapeToUint8s().BitsToInt8().ExtendLo8ToInt16()).ToBits().ReshapeToUint64s()
}

func simd_g_i16x8_extmul_low_i8x16_u(a V128, b V128) V128 {
	return a.ReshapeToUint8s().ExtendLo8ToUint16().Mul(b.ReshapeToUint8s().ExtendLo8ToUint16()).ReshapeToUint64s()
}

func simd_g_i16x8_extmul_high_i8x16_s(a V128, b V128) V128 {
	return a.ReshapeToUint32s().BitsToInt32().PermuteScalars(2, 3, 2, 3).ToBits().ReshapeToUint64s().ReshapeToUint8s().BitsToInt8().ExtendLo8ToInt16().Mul(b.ReshapeToUint32s().BitsToInt32().PermuteScalars(2, 3, 2, 3).ToBits().ReshapeToUint64s().ReshapeToUint8s().BitsToInt8().ExtendLo8ToInt16()).ToBits().ReshapeToUint64s()
}

func simd_g_i16x8_extmul_high_i8x16_u(a V128, b V128) V128 {
	return a.ReshapeToUint32s().BitsToInt32().PermuteScalars(2, 3, 2, 3).ToBits().ReshapeToUint64s().ReshapeToUint8s().ExtendLo8ToUint16().Mul(b.ReshapeToUint32s().BitsToInt32().PermuteScalars(2, 3, 2, 3).ToBits().ReshapeToUint64s().ReshapeToUint8s().ExtendLo8ToUint16()).ReshapeToUint64s()
}

func simd_g_i32x4_extmul_low_i16x8_s(a V128, b V128) V128 {
	return a.ReshapeToUint16s().BitsToInt16().ExtendLo4ToInt32().Mul(b.ReshapeToUint16s().BitsToInt16().ExtendLo4ToInt32()).ToBits().ReshapeToUint64s()
}

func simd_g_i32x4_extmul_low_i16x8_u(a V128, b V128) V128 {
	return a.ReshapeToUint16s().ExtendLo4ToUint32().Mul(b.ReshapeToUint16s().ExtendLo4ToUint32()).ReshapeToUint64s()
}

func simd_g_i32x4_extmul_high_i16x8_s(a V128, b V128) V128 {
	return a.ReshapeToUint32s().BitsToInt32().PermuteScalars(2, 3, 2, 3).ToBits().ReshapeToUint64s().ReshapeToUint16s().BitsToInt16().ExtendLo4ToInt32().Mul(b.ReshapeToUint32s().BitsToInt32().PermuteScalars(2, 3, 2, 3).ToBits().ReshapeToUint64s().ReshapeToUint16s().BitsToInt16().ExtendLo4ToInt32()).ToBits().ReshapeToUint64s()
}

func simd_g_i32x4_extmul_high_i16x8_u(a V128, b V128) V128 {
	return a.ReshapeToUint32s().BitsToInt32().PermuteScalars(2, 3, 2, 3).ToBits().ReshapeToUint64s().ReshapeToUint16s().ExtendLo4ToUint32().Mul(b.ReshapeToUint32s().BitsToInt32().PermuteScalars(2, 3, 2, 3).ToBits().ReshapeToUint64s().ReshapeToUint16s().ExtendLo4ToUint32()).ReshapeToUint64s()
}

func simd_g_i64x2_extmul_low_i32x4_s(a V128, b V128) V128 {
	return a.ReshapeToUint32s().BitsToInt32().PermuteScalars(0, 0, 1, 1).MulWidenEven(b.ReshapeToUint32s().BitsToInt32().PermuteScalars(0, 0, 1, 1)).ToBits()
}

func simd_g_i64x2_extmul_low_i32x4_u(a V128, b V128) V128 {
	return a.ReshapeToUint32s().BitsToInt32().PermuteScalars(0, 0, 1, 1).ToBits().ReshapeToUint64s().ReshapeToUint32s().MulWidenEven(b.ReshapeToUint32s().BitsToInt32().PermuteScalars(0, 0, 1, 1).ToBits().ReshapeToUint64s().ReshapeToUint32s())
}

func simd_g_i64x2_extmul_high_i32x4_s(a V128, b V128) V128 {
	return a.ReshapeToUint32s().BitsToInt32().PermuteScalars(2, 2, 3, 3).MulWidenEven(b.ReshapeToUint32s().BitsToInt32().PermuteScalars(2, 2, 3, 3)).ToBits()
}

func simd_g_i64x2_extmul_high_i32x4_u(a V128, b V128) V128 {
	return a.ReshapeToUint32s().BitsToInt32().PermuteScalars(2, 2, 3, 3).ToBits().ReshapeToUint64s().ReshapeToUint32s().MulWidenEven(b.ReshapeToUint32s().BitsToInt32().PermuteScalars(2, 2, 3, 3).ToBits().ReshapeToUint64s().ReshapeToUint32s())
}

func simd_g_i32x4_dot_i16x8_s(a V128, b V128) V128 {
	return a.ReshapeToUint16s().BitsToInt16().DotProductPairs(b.ReshapeToUint16s().BitsToInt16()).ToBits().ReshapeToUint64s()
}

func simd_g_f32x4_add(a V128, b V128) V128 {
	return a.ReshapeToUint32s().BitsToFloat32().Add(b.ReshapeToUint32s().BitsToFloat32()).ToBits().ReshapeToUint64s()
}

func simd_g_f32x4_sub(a V128, b V128) V128 {
	return a.ReshapeToUint32s().BitsToFloat32().Sub(b.ReshapeToUint32s().BitsToFloat32()).ToBits().ReshapeToUint64s()
}

func simd_g_f32x4_mul(a V128, b V128) V128 {
	return a.ReshapeToUint32s().BitsToFloat32().Mul(b.ReshapeToUint32s().BitsToFloat32()).ToBits().ReshapeToUint64s()
}

func simd_g_f32x4_div(a V128, b V128) V128 {
	return a.ReshapeToUint32s().BitsToFloat32().Div(b.ReshapeToUint32s().BitsToFloat32()).ToBits().ReshapeToUint64s()
}

func simd_g_f32x4_min(a V128, b V128) V128 {
	x, y := a.ReshapeToUint32s().BitsToFloat32(), b.ReshapeToUint32s().BitsToFloat32()
	sel := x.Less(y).ToInt32x4().ToBits().ReshapeToUint64s()
	eq := x.Equal(y).ToInt32x4().ToBits().ReshapeToUint64s()
	nan := x.IsNaN().Or(y.IsNaN()).ToInt32x4().ToBits().ReshapeToUint64s()
	r := a.And(sel).Or(b.AndNot(sel))
	r = r.AndNot(eq).Or(a.Or(b).And(eq))
	return r.AndNot(nan).Or(archsimd.LoadUint64x2Array(&simdGK_u32_0x7fc00000).ReshapeToUint32s().ReshapeToUint64s().And(nan))
}

func simd_g_f32x4_max(a V128, b V128) V128 {
	x, y := a.ReshapeToUint32s().BitsToFloat32(), b.ReshapeToUint32s().BitsToFloat32()
	sel := x.Greater(y).ToInt32x4().ToBits().ReshapeToUint64s()
	eq := x.Equal(y).ToInt32x4().ToBits().ReshapeToUint64s()
	nan := x.IsNaN().Or(y.IsNaN()).ToInt32x4().ToBits().ReshapeToUint64s()
	r := a.And(sel).Or(b.AndNot(sel))
	r = r.AndNot(eq).Or(a.And(b).And(eq))
	return r.AndNot(nan).Or(archsimd.LoadUint64x2Array(&simdGK_u32_0x7fc00000).ReshapeToUint32s().ReshapeToUint64s().And(nan))
}

func simd_g_f32x4_pmin(a V128, b V128) V128 {
	x, y := a.ReshapeToUint32s().BitsToFloat32(), b.ReshapeToUint32s().BitsToFloat32()
	return y.IfElse(y.Less(x), x).ToBits().ReshapeToUint64s()
}

func simd_g_f32x4_pmax(a V128, b V128) V128 {
	x, y := a.ReshapeToUint32s().BitsToFloat32(), b.ReshapeToUint32s().BitsToFloat32()
	return y.IfElse(x.Less(y), x).ToBits().ReshapeToUint64s()
}

func simd_g_f32x4_abs(a V128) V128 {
	return a.ReshapeToUint32s().BitsToFloat32().Abs().ToBits().ReshapeToUint64s()
}

func simd_g_f32x4_neg(a V128) V128 {
	return a.ReshapeToUint32s().BitsToFloat32().Neg().ToBits().ReshapeToUint64s()
}

func simd_g_f32x4_sqrt(a V128) V128 {
	return a.ReshapeToUint32s().BitsToFloat32().Sqrt().ToBits().ReshapeToUint64s()
}

func simd_g_f32x4_ceil(a V128) V128 {
	return a.ReshapeToUint32s().BitsToFloat32().Ceil().ToBits().ReshapeToUint64s()
}

func simd_g_f32x4_floor(a V128) V128 {
	return a.ReshapeToUint32s().BitsToFloat32().Floor().ToBits().ReshapeToUint64s()
}

func simd_g_f32x4_trunc(a V128) V128 {
	return a.ReshapeToUint32s().BitsToFloat32().Trunc().ToBits().ReshapeToUint64s()
}

func simd_g_f32x4_nearest(a V128) V128 {
	return a.ReshapeToUint32s().BitsToFloat32().Round().ToBits().ReshapeToUint64s()
}

func simd_g_f64x2_add(a V128, b V128) V128 {
	return a.BitsToFloat64().Add(b.BitsToFloat64()).ToBits()
}

func simd_g_f64x2_sub(a V128, b V128) V128 {
	return a.BitsToFloat64().Sub(b.BitsToFloat64()).ToBits()
}

func simd_g_f64x2_mul(a V128, b V128) V128 {
	return a.BitsToFloat64().Mul(b.BitsToFloat64()).ToBits()
}

func simd_g_f64x2_div(a V128, b V128) V128 {
	return a.BitsToFloat64().Div(b.BitsToFloat64()).ToBits()
}

func simd_g_f64x2_min(a V128, b V128) V128 {
	x, y := a.BitsToFloat64(), b.BitsToFloat64()
	sel := x.Less(y).ToInt64x2().ToBits()
	eq := x.Equal(y).ToInt64x2().ToBits()
	nan := x.IsNaN().Or(y.IsNaN()).ToInt64x2().ToBits()
	r := a.And(sel).Or(b.AndNot(sel))
	r = r.AndNot(eq).Or(a.Or(b).And(eq))
	return r.AndNot(nan).Or(archsimd.LoadUint64x2Array(&simdGK_u64_0x7ff8000000000000).And(nan))
}

func simd_g_f64x2_max(a V128, b V128) V128 {
	x, y := a.BitsToFloat64(), b.BitsToFloat64()
	sel := x.Greater(y).ToInt64x2().ToBits()
	eq := x.Equal(y).ToInt64x2().ToBits()
	nan := x.IsNaN().Or(y.IsNaN()).ToInt64x2().ToBits()
	r := a.And(sel).Or(b.AndNot(sel))
	r = r.AndNot(eq).Or(a.And(b).And(eq))
	return r.AndNot(nan).Or(archsimd.LoadUint64x2Array(&simdGK_u64_0x7ff8000000000000).And(nan))
}

func simd_g_f64x2_pmin(a V128, b V128) V128 {
	x, y := a.BitsToFloat64(), b.BitsToFloat64()
	return y.IfElse(y.Less(x), x).ToBits()
}

func simd_g_f64x2_pmax(a V128, b V128) V128 {
	x, y := a.BitsToFloat64(), b.BitsToFloat64()
	return y.IfElse(x.Less(y), x).ToBits()
}

func simd_g_f64x2_abs(a V128) V128 {
	return a.BitsToFloat64().Abs().ToBits()
}

func simd_g_f64x2_neg(a V128) V128 {
	return a.BitsToFloat64().Neg().ToBits()
}

func simd_g_f64x2_sqrt(a V128) V128 {
	return a.BitsToFloat64().Sqrt().ToBits()
}

func simd_g_f64x2_ceil(a V128) V128 {
	return a.BitsToFloat64().Ceil().ToBits()
}

func simd_g_f64x2_floor(a V128) V128 {
	return a.BitsToFloat64().Floor().ToBits()
}

func simd_g_f64x2_trunc(a V128) V128 {
	return a.BitsToFloat64().Trunc().ToBits()
}

func simd_g_f64x2_nearest(a V128) V128 {
	return a.BitsToFloat64().Round().ToBits()
}

func simd_g_i32x4_trunc_sat_f32x4_s(a V128) V128 {
	x := a.ReshapeToUint32s().BitsToFloat32()
	r := x.ConvertToInt32().ToBits().ReshapeToUint64s().And(x.Equal(x).ToInt32x4().ToBits().ReshapeToUint64s())
	big := x.GreaterEqual(archsimd.LoadUint64x2Array(&simdGK_f32_2147483648_0).ReshapeToUint32s().BitsToFloat32()).ToInt32x4().ToBits().ReshapeToUint64s()
	return r.AndNot(big).Or(big.And(archsimd.LoadUint64x2Array(&simdGK_u32_0x7fffffff).ReshapeToUint32s().ReshapeToUint64s()))
}

func simd_g_i32x4_trunc_sat_f32x4_u(a V128) V128 {
	p_a := simd_g_to(a)
	return simd_g_from(simd_i32x4_trunc_sat_f32x4_u(p_a))
}

func simd_g_i32x4_trunc_sat_f64x2_s_zero(a V128) V128 {
	x := a.BitsToFloat64()
	ok := x.Equal(x).ToInt64x2().ToBits().ReshapeToUint32s().BitsToInt32().PermuteScalars(0, 2, 2, 2).ToBits().ReshapeToUint64s()
	big := x.GreaterEqual(archsimd.LoadUint64x2Array(&simdGK_f64_2147483648_0).BitsToFloat64()).ToInt64x2().ToBits().ReshapeToUint32s().BitsToInt32().PermuteScalars(0, 2, 2, 2).ToBits().ReshapeToUint64s()
	lowHalf := archsimd.LoadUint64x2Array(&simdGLowHalf)
	r := x.ConvertToInt32().ToBits().ReshapeToUint64s().And(ok).And(lowHalf)
	return r.AndNot(big).Or(big.And(archsimd.LoadUint64x2Array(&simdGK_u32_0x7fffffff).ReshapeToUint32s().ReshapeToUint64s()).And(lowHalf))
}

func simd_g_i32x4_trunc_sat_f64x2_u_zero(a V128) V128 {
	p_a := simd_g_to(a)
	return simd_g_from(simd_i32x4_trunc_sat_f64x2_u_zero(p_a))
}

func simd_g_f32x4_convert_i32x4_s(a V128) V128 {
	return a.ReshapeToUint32s().BitsToInt32().ConvertToFloat32().ToBits().ReshapeToUint64s()
}

func simd_g_f32x4_convert_i32x4_u(a V128) V128 {
	p_a := simd_g_to(a)
	return simd_g_from(simd_f32x4_convert_i32x4_u(p_a))
}

func simd_g_f64x2_convert_low_i32x4_s(a V128) V128 {
	p_a := simd_g_to(a)
	return simd_g_from(simd_f64x2_convert_low_i32x4_s(p_a))
}

func simd_g_f64x2_convert_low_i32x4_u(a V128) V128 {
	p_a := simd_g_to(a)
	return simd_g_from(simd_f64x2_convert_low_i32x4_u(p_a))
}

func simd_g_f32x4_demote_f64x2_zero(a V128) V128 {
	return a.BitsToFloat64().ConvertToFloat32().ToBits().ReshapeToUint64s()
}

func simd_g_f64x2_promote_low_f32x4(a V128) V128 {
	p_a := simd_g_to(a)
	return simd_g_from(simd_f64x2_promote_low_f32x4(p_a))
}

func simd_g_v128_load_rng(m *Module, addr int32, offset int32, rlo int32, span int32) V128 {
	start := int64(uint64(uint32(addr))) + int64(rlo)
	if start < 0 || uint64(start)+uint64(uint32(span)) > m.memSize.Load() {
		panic(simdGOOB)
	}
	return archsimd.LoadUint64x2Array((*[2]uint64)(unsafe.Add(m.M, uintptr(uint64(uint32(addr))+uint64(uint32(offset))))))
}

func simd_g_v128_load_nc(m *Module, addr int32, offset int32) V128 {
	return archsimd.LoadUint64x2Array((*[2]uint64)(unsafe.Add(m.M, uintptr(uint64(uint32(addr))+uint64(uint32(offset))))))
}

func simd_g_v128_load(m *Module, addr int32, offset int32) V128 {
	return archsimd.LoadUint64x2Array((*[2]uint64)(unsafe.Add(m.M, simd_g_ea(m, addr, offset, 16))))
}

func simd_g_v128_f16x4_cvt_store(m *Module, addr int32, offset int32, v V128) int32 {
	p_v := simd_g_to(v)
	return simd_v128_f16x4_cvt_store(m, addr, offset, p_v)
}

func simd_g_v128_store(m *Module, addr int32, offset int32, v V128) int32 {
	v.StoreArray((*[2]uint64)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 16)))))
	return 0
}

func simd_g_v128_load8x8_s(m *Module, addr int32, offset int32) V128 {
	return archsimd.BroadcastUint64x2(*(*uint64)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 8))))).ReshapeToUint8s().BitsToInt8().ExtendLo8ToInt16().ToBits().ReshapeToUint64s()
}

func simd_g_v128_load8x8_u(m *Module, addr int32, offset int32) V128 {
	return archsimd.BroadcastUint64x2(*(*uint64)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 8))))).ReshapeToUint8s().ExtendLo8ToUint16().ReshapeToUint64s()
}

func simd_g_v128_load16x4_s(m *Module, addr int32, offset int32) V128 {
	return archsimd.BroadcastUint64x2(*(*uint64)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 8))))).ReshapeToUint16s().BitsToInt16().ExtendLo4ToInt32().ToBits().ReshapeToUint64s()
}

func simd_g_v128_load16x4_u(m *Module, addr int32, offset int32) V128 {
	return archsimd.BroadcastUint64x2(*(*uint64)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 8))))).ReshapeToUint16s().ExtendLo4ToUint32().ReshapeToUint64s()
}

func simd_g_f16x4_cvt(v V128) V128 {
	p_v := simd_g_to(v)
	return simd_g_from(simd_f16x4_cvt(p_v))
}

func simd_g_v128_load32x2_s(m *Module, addr int32, offset int32) V128 {
	return archsimd.BroadcastUint64x2(*(*uint64)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 8))))).ReshapeToUint32s().BitsToInt32().ExtendLo2ToInt64().ToBits()
}

func simd_g_v128_load32x2_u(m *Module, addr int32, offset int32) V128 {
	return archsimd.BroadcastUint64x2(*(*uint64)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 8))))).ReshapeToUint32s().ExtendLo2ToUint64()
}

func simd_g_v128_load8_splat(m *Module, addr int32, offset int32) V128 {
	return archsimd.BroadcastUint8x16(*(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 1))))).ReshapeToUint64s()
}

func simd_g_v128_load16_splat(m *Module, addr int32, offset int32) V128 {
	return archsimd.BroadcastUint16x8(*(*uint16)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 2))))).ReshapeToUint64s()
}

func simd_g_v128_load32_splat(m *Module, addr int32, offset int32) V128 {
	return archsimd.BroadcastUint32x4(*(*uint32)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 4))))).ReshapeToUint64s()
}

func simd_g_v128_load64_splat(m *Module, addr int32, offset int32) V128 {
	return archsimd.BroadcastUint64x2(*(*uint64)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 8)))))
}

func simd_g_v128_load32_zero(m *Module, addr int32, offset int32) V128 {
	return archsimd.LoadUint64x2Array(&simdGZero).ReshapeToUint32s().SetElem(0, *(*uint32)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 4))))).ReshapeToUint64s()
}

func simd_g_v128_load64_zero(m *Module, addr int32, offset int32) V128 {
	return archsimd.LoadUint64x2Array(&simdGZero).SetElem(0, *(*uint64)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 8)))))
}

func simd_g_v128_load8_lane_l0(m *Module, addr int32, offset int32, v V128) V128 {
	return v.ReshapeToUint8s().SetElem(0, *(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 1))))).ReshapeToUint64s()
}

func simd_g_v128_load8_lane_l1(m *Module, addr int32, offset int32, v V128) V128 {
	return v.ReshapeToUint8s().SetElem(1, *(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 1))))).ReshapeToUint64s()
}

func simd_g_v128_load8_lane_l2(m *Module, addr int32, offset int32, v V128) V128 {
	return v.ReshapeToUint8s().SetElem(2, *(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 1))))).ReshapeToUint64s()
}

func simd_g_v128_load8_lane_l3(m *Module, addr int32, offset int32, v V128) V128 {
	return v.ReshapeToUint8s().SetElem(3, *(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 1))))).ReshapeToUint64s()
}

func simd_g_v128_load8_lane_l4(m *Module, addr int32, offset int32, v V128) V128 {
	return v.ReshapeToUint8s().SetElem(4, *(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 1))))).ReshapeToUint64s()
}

func simd_g_v128_load8_lane_l5(m *Module, addr int32, offset int32, v V128) V128 {
	return v.ReshapeToUint8s().SetElem(5, *(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 1))))).ReshapeToUint64s()
}

func simd_g_v128_load8_lane_l6(m *Module, addr int32, offset int32, v V128) V128 {
	return v.ReshapeToUint8s().SetElem(6, *(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 1))))).ReshapeToUint64s()
}

func simd_g_v128_load8_lane_l7(m *Module, addr int32, offset int32, v V128) V128 {
	return v.ReshapeToUint8s().SetElem(7, *(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 1))))).ReshapeToUint64s()
}

func simd_g_v128_load8_lane_l8(m *Module, addr int32, offset int32, v V128) V128 {
	return v.ReshapeToUint8s().SetElem(8, *(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 1))))).ReshapeToUint64s()
}

func simd_g_v128_load8_lane_l9(m *Module, addr int32, offset int32, v V128) V128 {
	return v.ReshapeToUint8s().SetElem(9, *(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 1))))).ReshapeToUint64s()
}

func simd_g_v128_load8_lane_l10(m *Module, addr int32, offset int32, v V128) V128 {
	return v.ReshapeToUint8s().SetElem(10, *(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 1))))).ReshapeToUint64s()
}

func simd_g_v128_load8_lane_l11(m *Module, addr int32, offset int32, v V128) V128 {
	return v.ReshapeToUint8s().SetElem(11, *(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 1))))).ReshapeToUint64s()
}

func simd_g_v128_load8_lane_l12(m *Module, addr int32, offset int32, v V128) V128 {
	return v.ReshapeToUint8s().SetElem(12, *(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 1))))).ReshapeToUint64s()
}

func simd_g_v128_load8_lane_l13(m *Module, addr int32, offset int32, v V128) V128 {
	return v.ReshapeToUint8s().SetElem(13, *(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 1))))).ReshapeToUint64s()
}

func simd_g_v128_load8_lane_l14(m *Module, addr int32, offset int32, v V128) V128 {
	return v.ReshapeToUint8s().SetElem(14, *(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 1))))).ReshapeToUint64s()
}

func simd_g_v128_load8_lane_l15(m *Module, addr int32, offset int32, v V128) V128 {
	return v.ReshapeToUint8s().SetElem(15, *(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 1))))).ReshapeToUint64s()
}

func simd_g_v128_load16_lane_l0(m *Module, addr int32, offset int32, v V128) V128 {
	return v.ReshapeToUint16s().SetElem(0, *(*uint16)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 2))))).ReshapeToUint64s()
}

func simd_g_v128_load16_lane_l1(m *Module, addr int32, offset int32, v V128) V128 {
	return v.ReshapeToUint16s().SetElem(1, *(*uint16)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 2))))).ReshapeToUint64s()
}

func simd_g_v128_load16_lane_l2(m *Module, addr int32, offset int32, v V128) V128 {
	return v.ReshapeToUint16s().SetElem(2, *(*uint16)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 2))))).ReshapeToUint64s()
}

func simd_g_v128_load16_lane_l3(m *Module, addr int32, offset int32, v V128) V128 {
	return v.ReshapeToUint16s().SetElem(3, *(*uint16)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 2))))).ReshapeToUint64s()
}

func simd_g_v128_load16_lane_l4(m *Module, addr int32, offset int32, v V128) V128 {
	return v.ReshapeToUint16s().SetElem(4, *(*uint16)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 2))))).ReshapeToUint64s()
}

func simd_g_v128_load16_lane_l5(m *Module, addr int32, offset int32, v V128) V128 {
	return v.ReshapeToUint16s().SetElem(5, *(*uint16)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 2))))).ReshapeToUint64s()
}

func simd_g_v128_load16_lane_l6(m *Module, addr int32, offset int32, v V128) V128 {
	return v.ReshapeToUint16s().SetElem(6, *(*uint16)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 2))))).ReshapeToUint64s()
}

func simd_g_v128_load16_lane_l7(m *Module, addr int32, offset int32, v V128) V128 {
	return v.ReshapeToUint16s().SetElem(7, *(*uint16)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 2))))).ReshapeToUint64s()
}

func simd_g_v128_load32_lane_l0(m *Module, addr int32, offset int32, v V128) V128 {
	return v.ReshapeToUint32s().SetElem(0, *(*uint32)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 4))))).ReshapeToUint64s()
}

func simd_g_v128_load32_lane_l1(m *Module, addr int32, offset int32, v V128) V128 {
	return v.ReshapeToUint32s().SetElem(1, *(*uint32)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 4))))).ReshapeToUint64s()
}

func simd_g_v128_load32_lane_l2(m *Module, addr int32, offset int32, v V128) V128 {
	return v.ReshapeToUint32s().SetElem(2, *(*uint32)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 4))))).ReshapeToUint64s()
}

func simd_g_v128_load32_lane_l3(m *Module, addr int32, offset int32, v V128) V128 {
	return v.ReshapeToUint32s().SetElem(3, *(*uint32)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 4))))).ReshapeToUint64s()
}

func simd_g_v128_load64_lane_l0(m *Module, addr int32, offset int32, v V128) V128 {
	return v.SetElem(0, *(*uint64)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 8)))))
}

func simd_g_v128_load64_lane_l1(m *Module, addr int32, offset int32, v V128) V128 {
	return v.SetElem(1, *(*uint64)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 8)))))
}

func simd_g_v128_store8_lane_l0(m *Module, addr int32, offset int32, v V128) int32 {
	*(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 1)))) = v.ReshapeToUint8s().GetElem(0)
	return 0
}

func simd_g_v128_store8_lane_l1(m *Module, addr int32, offset int32, v V128) int32 {
	*(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 1)))) = v.ReshapeToUint8s().GetElem(1)
	return 0
}

func simd_g_v128_store8_lane_l2(m *Module, addr int32, offset int32, v V128) int32 {
	*(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 1)))) = v.ReshapeToUint8s().GetElem(2)
	return 0
}

func simd_g_v128_store8_lane_l3(m *Module, addr int32, offset int32, v V128) int32 {
	*(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 1)))) = v.ReshapeToUint8s().GetElem(3)
	return 0
}

func simd_g_v128_store8_lane_l4(m *Module, addr int32, offset int32, v V128) int32 {
	*(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 1)))) = v.ReshapeToUint8s().GetElem(4)
	return 0
}

func simd_g_v128_store8_lane_l5(m *Module, addr int32, offset int32, v V128) int32 {
	*(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 1)))) = v.ReshapeToUint8s().GetElem(5)
	return 0
}

func simd_g_v128_store8_lane_l6(m *Module, addr int32, offset int32, v V128) int32 {
	*(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 1)))) = v.ReshapeToUint8s().GetElem(6)
	return 0
}

func simd_g_v128_store8_lane_l7(m *Module, addr int32, offset int32, v V128) int32 {
	*(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 1)))) = v.ReshapeToUint8s().GetElem(7)
	return 0
}

func simd_g_v128_store8_lane_l8(m *Module, addr int32, offset int32, v V128) int32 {
	*(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 1)))) = v.ReshapeToUint8s().GetElem(8)
	return 0
}

func simd_g_v128_store8_lane_l9(m *Module, addr int32, offset int32, v V128) int32 {
	*(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 1)))) = v.ReshapeToUint8s().GetElem(9)
	return 0
}

func simd_g_v128_store8_lane_l10(m *Module, addr int32, offset int32, v V128) int32 {
	*(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 1)))) = v.ReshapeToUint8s().GetElem(10)
	return 0
}

func simd_g_v128_store8_lane_l11(m *Module, addr int32, offset int32, v V128) int32 {
	*(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 1)))) = v.ReshapeToUint8s().GetElem(11)
	return 0
}

func simd_g_v128_store8_lane_l12(m *Module, addr int32, offset int32, v V128) int32 {
	*(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 1)))) = v.ReshapeToUint8s().GetElem(12)
	return 0
}

func simd_g_v128_store8_lane_l13(m *Module, addr int32, offset int32, v V128) int32 {
	*(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 1)))) = v.ReshapeToUint8s().GetElem(13)
	return 0
}

func simd_g_v128_store8_lane_l14(m *Module, addr int32, offset int32, v V128) int32 {
	*(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 1)))) = v.ReshapeToUint8s().GetElem(14)
	return 0
}

func simd_g_v128_store8_lane_l15(m *Module, addr int32, offset int32, v V128) int32 {
	*(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 1)))) = v.ReshapeToUint8s().GetElem(15)
	return 0
}

func simd_g_v128_store16_lane_l0(m *Module, addr int32, offset int32, v V128) int32 {
	*(*uint16)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 2)))) = v.ReshapeToUint16s().GetElem(0)
	return 0
}

func simd_g_v128_store16_lane_l1(m *Module, addr int32, offset int32, v V128) int32 {
	*(*uint16)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 2)))) = v.ReshapeToUint16s().GetElem(1)
	return 0
}

func simd_g_v128_store16_lane_l2(m *Module, addr int32, offset int32, v V128) int32 {
	*(*uint16)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 2)))) = v.ReshapeToUint16s().GetElem(2)
	return 0
}

func simd_g_v128_store16_lane_l3(m *Module, addr int32, offset int32, v V128) int32 {
	*(*uint16)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 2)))) = v.ReshapeToUint16s().GetElem(3)
	return 0
}

func simd_g_v128_store16_lane_l4(m *Module, addr int32, offset int32, v V128) int32 {
	*(*uint16)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 2)))) = v.ReshapeToUint16s().GetElem(4)
	return 0
}

func simd_g_v128_store16_lane_l5(m *Module, addr int32, offset int32, v V128) int32 {
	*(*uint16)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 2)))) = v.ReshapeToUint16s().GetElem(5)
	return 0
}

func simd_g_v128_store16_lane_l6(m *Module, addr int32, offset int32, v V128) int32 {
	*(*uint16)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 2)))) = v.ReshapeToUint16s().GetElem(6)
	return 0
}

func simd_g_v128_store16_lane_l7(m *Module, addr int32, offset int32, v V128) int32 {
	*(*uint16)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 2)))) = v.ReshapeToUint16s().GetElem(7)
	return 0
}

func simd_g_v128_store32_lane_l0(m *Module, addr int32, offset int32, v V128) int32 {
	*(*uint32)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 4)))) = v.ReshapeToUint32s().GetElem(0)
	return 0
}

func simd_g_v128_store32_lane_l1(m *Module, addr int32, offset int32, v V128) int32 {
	*(*uint32)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 4)))) = v.ReshapeToUint32s().GetElem(1)
	return 0
}

func simd_g_v128_store32_lane_l2(m *Module, addr int32, offset int32, v V128) int32 {
	*(*uint32)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 4)))) = v.ReshapeToUint32s().GetElem(2)
	return 0
}

func simd_g_v128_store32_lane_l3(m *Module, addr int32, offset int32, v V128) int32 {
	*(*uint32)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 4)))) = v.ReshapeToUint32s().GetElem(3)
	return 0
}

func simd_g_v128_store64_lane_l0(m *Module, addr int32, offset int32, v V128) int32 {
	*(*uint64)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 8)))) = v.GetElem(0)
	return 0
}

func simd_g_v128_store64_lane_l1(m *Module, addr int32, offset int32, v V128) int32 {
	*(*uint64)(unsafe.Add(m.M, uintptr(simd_g_ea(m, addr, offset, 8)))) = v.GetElem(1)
	return 0
}

func simd_g_m64_v128_load(m *Module, addr int64, offset int64) V128 {
	return archsimd.LoadUint64x2Array((*[2]uint64)(unsafe.Add(m.M, simd_g_ea64(m, addr, offset, 16))))
}

func simd_g_m64_v128_load_rng(m *Module, addr int64, offset int64, rlo int64, span int64) V128 {
	start := addr + rlo
	if start < 0 || uint64(start)+uint64(span) > m.memSize.Load() {
		panic(simdGOOB)
	}
	return archsimd.LoadUint64x2Array((*[2]uint64)(unsafe.Add(m.M, uintptr(uint64(addr)+uint64(offset)))))
}

func simd_g_m64_v128_load_nc(m *Module, addr int64, offset int64) V128 {
	return archsimd.LoadUint64x2Array((*[2]uint64)(unsafe.Add(m.M, uintptr(uint64(addr)+uint64(offset)))))
}

func simd_g_m64_v128_store(m *Module, addr int64, offset int64, v V128) int32 {
	v.StoreArray((*[2]uint64)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 16)))))
	return 0
}

func simd_g_m64_v128_f16x4_cvt_store(m *Module, addr int64, offset int64, v V128) int32 {
	p_v := simd_g_to(v)
	return simd_m64_v128_f16x4_cvt_store(m, addr, offset, p_v)
}

func simd_g_m64_v128_load32_zero(m *Module, addr int64, offset int64) V128 {
	return archsimd.LoadUint64x2Array(&simdGZero).ReshapeToUint32s().SetElem(0, *(*uint32)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 4))))).ReshapeToUint64s()
}

func simd_g_m64_v128_load64_zero(m *Module, addr int64, offset int64) V128 {
	return archsimd.LoadUint64x2Array(&simdGZero).SetElem(0, *(*uint64)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 8)))))
}

func simd_g_m64_v128_load8_splat(m *Module, addr int64, offset int64) V128 {
	return archsimd.BroadcastUint8x16(*(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 1))))).ReshapeToUint64s()
}

func simd_g_m64_v128_load16_splat(m *Module, addr int64, offset int64) V128 {
	return archsimd.BroadcastUint16x8(*(*uint16)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 2))))).ReshapeToUint64s()
}

func simd_g_m64_v128_load32_splat(m *Module, addr int64, offset int64) V128 {
	return archsimd.BroadcastUint32x4(*(*uint32)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 4))))).ReshapeToUint64s()
}

func simd_g_m64_v128_load64_splat(m *Module, addr int64, offset int64) V128 {
	return archsimd.BroadcastUint64x2(*(*uint64)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 8)))))
}

func simd_g_m64_v128_load8x8_s(m *Module, addr int64, offset int64) V128 {
	return archsimd.BroadcastUint64x2(*(*uint64)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 8))))).ReshapeToUint8s().BitsToInt8().ExtendLo8ToInt16().ToBits().ReshapeToUint64s()
}

func simd_g_m64_v128_load8x8_u(m *Module, addr int64, offset int64) V128 {
	return archsimd.BroadcastUint64x2(*(*uint64)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 8))))).ReshapeToUint8s().ExtendLo8ToUint16().ReshapeToUint64s()
}

func simd_g_m64_v128_load16x4_s(m *Module, addr int64, offset int64) V128 {
	return archsimd.BroadcastUint64x2(*(*uint64)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 8))))).ReshapeToUint16s().BitsToInt16().ExtendLo4ToInt32().ToBits().ReshapeToUint64s()
}

func simd_g_m64_v128_load16x4_u(m *Module, addr int64, offset int64) V128 {
	return archsimd.BroadcastUint64x2(*(*uint64)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 8))))).ReshapeToUint16s().ExtendLo4ToUint32().ReshapeToUint64s()
}

func simd_g_m64_v128_load32x2_s(m *Module, addr int64, offset int64) V128 {
	return archsimd.BroadcastUint64x2(*(*uint64)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 8))))).ReshapeToUint32s().BitsToInt32().ExtendLo2ToInt64().ToBits()
}

func simd_g_m64_v128_load32x2_u(m *Module, addr int64, offset int64) V128 {
	return archsimd.BroadcastUint64x2(*(*uint64)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 8))))).ReshapeToUint32s().ExtendLo2ToUint64()
}

func simd_g_m64_v128_load8_lane_l0(m *Module, addr int64, offset int64, v V128) V128 {
	return v.ReshapeToUint8s().SetElem(0, *(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 1))))).ReshapeToUint64s()
}

func simd_g_m64_v128_load8_lane_l1(m *Module, addr int64, offset int64, v V128) V128 {
	return v.ReshapeToUint8s().SetElem(1, *(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 1))))).ReshapeToUint64s()
}

func simd_g_m64_v128_load8_lane_l2(m *Module, addr int64, offset int64, v V128) V128 {
	return v.ReshapeToUint8s().SetElem(2, *(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 1))))).ReshapeToUint64s()
}

func simd_g_m64_v128_load8_lane_l3(m *Module, addr int64, offset int64, v V128) V128 {
	return v.ReshapeToUint8s().SetElem(3, *(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 1))))).ReshapeToUint64s()
}

func simd_g_m64_v128_load8_lane_l4(m *Module, addr int64, offset int64, v V128) V128 {
	return v.ReshapeToUint8s().SetElem(4, *(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 1))))).ReshapeToUint64s()
}

func simd_g_m64_v128_load8_lane_l5(m *Module, addr int64, offset int64, v V128) V128 {
	return v.ReshapeToUint8s().SetElem(5, *(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 1))))).ReshapeToUint64s()
}

func simd_g_m64_v128_load8_lane_l6(m *Module, addr int64, offset int64, v V128) V128 {
	return v.ReshapeToUint8s().SetElem(6, *(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 1))))).ReshapeToUint64s()
}

func simd_g_m64_v128_load8_lane_l7(m *Module, addr int64, offset int64, v V128) V128 {
	return v.ReshapeToUint8s().SetElem(7, *(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 1))))).ReshapeToUint64s()
}

func simd_g_m64_v128_load8_lane_l8(m *Module, addr int64, offset int64, v V128) V128 {
	return v.ReshapeToUint8s().SetElem(8, *(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 1))))).ReshapeToUint64s()
}

func simd_g_m64_v128_load8_lane_l9(m *Module, addr int64, offset int64, v V128) V128 {
	return v.ReshapeToUint8s().SetElem(9, *(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 1))))).ReshapeToUint64s()
}

func simd_g_m64_v128_load8_lane_l10(m *Module, addr int64, offset int64, v V128) V128 {
	return v.ReshapeToUint8s().SetElem(10, *(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 1))))).ReshapeToUint64s()
}

func simd_g_m64_v128_load8_lane_l11(m *Module, addr int64, offset int64, v V128) V128 {
	return v.ReshapeToUint8s().SetElem(11, *(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 1))))).ReshapeToUint64s()
}

func simd_g_m64_v128_load8_lane_l12(m *Module, addr int64, offset int64, v V128) V128 {
	return v.ReshapeToUint8s().SetElem(12, *(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 1))))).ReshapeToUint64s()
}

func simd_g_m64_v128_load8_lane_l13(m *Module, addr int64, offset int64, v V128) V128 {
	return v.ReshapeToUint8s().SetElem(13, *(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 1))))).ReshapeToUint64s()
}

func simd_g_m64_v128_load8_lane_l14(m *Module, addr int64, offset int64, v V128) V128 {
	return v.ReshapeToUint8s().SetElem(14, *(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 1))))).ReshapeToUint64s()
}

func simd_g_m64_v128_load8_lane_l15(m *Module, addr int64, offset int64, v V128) V128 {
	return v.ReshapeToUint8s().SetElem(15, *(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 1))))).ReshapeToUint64s()
}

func simd_g_m64_v128_load16_lane_l0(m *Module, addr int64, offset int64, v V128) V128 {
	return v.ReshapeToUint16s().SetElem(0, *(*uint16)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 2))))).ReshapeToUint64s()
}

func simd_g_m64_v128_load16_lane_l1(m *Module, addr int64, offset int64, v V128) V128 {
	return v.ReshapeToUint16s().SetElem(1, *(*uint16)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 2))))).ReshapeToUint64s()
}

func simd_g_m64_v128_load16_lane_l2(m *Module, addr int64, offset int64, v V128) V128 {
	return v.ReshapeToUint16s().SetElem(2, *(*uint16)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 2))))).ReshapeToUint64s()
}

func simd_g_m64_v128_load16_lane_l3(m *Module, addr int64, offset int64, v V128) V128 {
	return v.ReshapeToUint16s().SetElem(3, *(*uint16)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 2))))).ReshapeToUint64s()
}

func simd_g_m64_v128_load16_lane_l4(m *Module, addr int64, offset int64, v V128) V128 {
	return v.ReshapeToUint16s().SetElem(4, *(*uint16)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 2))))).ReshapeToUint64s()
}

func simd_g_m64_v128_load16_lane_l5(m *Module, addr int64, offset int64, v V128) V128 {
	return v.ReshapeToUint16s().SetElem(5, *(*uint16)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 2))))).ReshapeToUint64s()
}

func simd_g_m64_v128_load16_lane_l6(m *Module, addr int64, offset int64, v V128) V128 {
	return v.ReshapeToUint16s().SetElem(6, *(*uint16)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 2))))).ReshapeToUint64s()
}

func simd_g_m64_v128_load16_lane_l7(m *Module, addr int64, offset int64, v V128) V128 {
	return v.ReshapeToUint16s().SetElem(7, *(*uint16)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 2))))).ReshapeToUint64s()
}

func simd_g_m64_v128_load32_lane_l0(m *Module, addr int64, offset int64, v V128) V128 {
	return v.ReshapeToUint32s().SetElem(0, *(*uint32)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 4))))).ReshapeToUint64s()
}

func simd_g_m64_v128_load32_lane_l1(m *Module, addr int64, offset int64, v V128) V128 {
	return v.ReshapeToUint32s().SetElem(1, *(*uint32)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 4))))).ReshapeToUint64s()
}

func simd_g_m64_v128_load32_lane_l2(m *Module, addr int64, offset int64, v V128) V128 {
	return v.ReshapeToUint32s().SetElem(2, *(*uint32)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 4))))).ReshapeToUint64s()
}

func simd_g_m64_v128_load32_lane_l3(m *Module, addr int64, offset int64, v V128) V128 {
	return v.ReshapeToUint32s().SetElem(3, *(*uint32)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 4))))).ReshapeToUint64s()
}

func simd_g_m64_v128_load64_lane_l0(m *Module, addr int64, offset int64, v V128) V128 {
	return v.SetElem(0, *(*uint64)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 8)))))
}

func simd_g_m64_v128_load64_lane_l1(m *Module, addr int64, offset int64, v V128) V128 {
	return v.SetElem(1, *(*uint64)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 8)))))
}

func simd_g_m64_v128_store8_lane_l0(m *Module, addr int64, offset int64, v V128) int32 {
	*(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 1)))) = v.ReshapeToUint8s().GetElem(0)
	return 0
}

func simd_g_m64_v128_store8_lane_l1(m *Module, addr int64, offset int64, v V128) int32 {
	*(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 1)))) = v.ReshapeToUint8s().GetElem(1)
	return 0
}

func simd_g_m64_v128_store8_lane_l2(m *Module, addr int64, offset int64, v V128) int32 {
	*(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 1)))) = v.ReshapeToUint8s().GetElem(2)
	return 0
}

func simd_g_m64_v128_store8_lane_l3(m *Module, addr int64, offset int64, v V128) int32 {
	*(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 1)))) = v.ReshapeToUint8s().GetElem(3)
	return 0
}

func simd_g_m64_v128_store8_lane_l4(m *Module, addr int64, offset int64, v V128) int32 {
	*(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 1)))) = v.ReshapeToUint8s().GetElem(4)
	return 0
}

func simd_g_m64_v128_store8_lane_l5(m *Module, addr int64, offset int64, v V128) int32 {
	*(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 1)))) = v.ReshapeToUint8s().GetElem(5)
	return 0
}

func simd_g_m64_v128_store8_lane_l6(m *Module, addr int64, offset int64, v V128) int32 {
	*(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 1)))) = v.ReshapeToUint8s().GetElem(6)
	return 0
}

func simd_g_m64_v128_store8_lane_l7(m *Module, addr int64, offset int64, v V128) int32 {
	*(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 1)))) = v.ReshapeToUint8s().GetElem(7)
	return 0
}

func simd_g_m64_v128_store8_lane_l8(m *Module, addr int64, offset int64, v V128) int32 {
	*(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 1)))) = v.ReshapeToUint8s().GetElem(8)
	return 0
}

func simd_g_m64_v128_store8_lane_l9(m *Module, addr int64, offset int64, v V128) int32 {
	*(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 1)))) = v.ReshapeToUint8s().GetElem(9)
	return 0
}

func simd_g_m64_v128_store8_lane_l10(m *Module, addr int64, offset int64, v V128) int32 {
	*(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 1)))) = v.ReshapeToUint8s().GetElem(10)
	return 0
}

func simd_g_m64_v128_store8_lane_l11(m *Module, addr int64, offset int64, v V128) int32 {
	*(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 1)))) = v.ReshapeToUint8s().GetElem(11)
	return 0
}

func simd_g_m64_v128_store8_lane_l12(m *Module, addr int64, offset int64, v V128) int32 {
	*(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 1)))) = v.ReshapeToUint8s().GetElem(12)
	return 0
}

func simd_g_m64_v128_store8_lane_l13(m *Module, addr int64, offset int64, v V128) int32 {
	*(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 1)))) = v.ReshapeToUint8s().GetElem(13)
	return 0
}

func simd_g_m64_v128_store8_lane_l14(m *Module, addr int64, offset int64, v V128) int32 {
	*(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 1)))) = v.ReshapeToUint8s().GetElem(14)
	return 0
}

func simd_g_m64_v128_store8_lane_l15(m *Module, addr int64, offset int64, v V128) int32 {
	*(*uint8)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 1)))) = v.ReshapeToUint8s().GetElem(15)
	return 0
}

func simd_g_m64_v128_store16_lane_l0(m *Module, addr int64, offset int64, v V128) int32 {
	*(*uint16)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 2)))) = v.ReshapeToUint16s().GetElem(0)
	return 0
}

func simd_g_m64_v128_store16_lane_l1(m *Module, addr int64, offset int64, v V128) int32 {
	*(*uint16)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 2)))) = v.ReshapeToUint16s().GetElem(1)
	return 0
}

func simd_g_m64_v128_store16_lane_l2(m *Module, addr int64, offset int64, v V128) int32 {
	*(*uint16)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 2)))) = v.ReshapeToUint16s().GetElem(2)
	return 0
}

func simd_g_m64_v128_store16_lane_l3(m *Module, addr int64, offset int64, v V128) int32 {
	*(*uint16)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 2)))) = v.ReshapeToUint16s().GetElem(3)
	return 0
}

func simd_g_m64_v128_store16_lane_l4(m *Module, addr int64, offset int64, v V128) int32 {
	*(*uint16)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 2)))) = v.ReshapeToUint16s().GetElem(4)
	return 0
}

func simd_g_m64_v128_store16_lane_l5(m *Module, addr int64, offset int64, v V128) int32 {
	*(*uint16)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 2)))) = v.ReshapeToUint16s().GetElem(5)
	return 0
}

func simd_g_m64_v128_store16_lane_l6(m *Module, addr int64, offset int64, v V128) int32 {
	*(*uint16)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 2)))) = v.ReshapeToUint16s().GetElem(6)
	return 0
}

func simd_g_m64_v128_store16_lane_l7(m *Module, addr int64, offset int64, v V128) int32 {
	*(*uint16)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 2)))) = v.ReshapeToUint16s().GetElem(7)
	return 0
}

func simd_g_m64_v128_store32_lane_l0(m *Module, addr int64, offset int64, v V128) int32 {
	*(*uint32)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 4)))) = v.ReshapeToUint32s().GetElem(0)
	return 0
}

func simd_g_m64_v128_store32_lane_l1(m *Module, addr int64, offset int64, v V128) int32 {
	*(*uint32)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 4)))) = v.ReshapeToUint32s().GetElem(1)
	return 0
}

func simd_g_m64_v128_store32_lane_l2(m *Module, addr int64, offset int64, v V128) int32 {
	*(*uint32)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 4)))) = v.ReshapeToUint32s().GetElem(2)
	return 0
}

func simd_g_m64_v128_store32_lane_l3(m *Module, addr int64, offset int64, v V128) int32 {
	*(*uint32)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 4)))) = v.ReshapeToUint32s().GetElem(3)
	return 0
}

func simd_g_m64_v128_store64_lane_l0(m *Module, addr int64, offset int64, v V128) int32 {
	*(*uint64)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 8)))) = v.GetElem(0)
	return 0
}

func simd_g_m64_v128_store64_lane_l1(m *Module, addr int64, offset int64, v V128) int32 {
	*(*uint64)(unsafe.Add(m.M, uintptr(simd_g_ea64(m, addr, offset, 8)))) = v.GetElem(1)
	return 0
}
