// Code generated by tools/gen-simd-gosimd/gen.py; DO NOT EDIT.

//go:build goexperiment.simd && go1.27 && !go1.28 && (amd64 || arm64)

package helpers

// Every simd_g_<op> must agree with the pair-carrier helper simd_<op>
// (asm-backed on amd64.v2/arm64, the scalar reference elsewhere) on the
// corpus below (edge lanes plus seeded random vectors); memory
// helpers are checked against their pair-carrier originals over a small
// module, including the out-of-bounds trap.

import (
	"bytes"
	"math"
	"math/rand"
	"testing"
)

var simdGCorpus = func() [][2]uint64 {
	vs := [][2]uint64{
		{0, 0},
		{^uint64(0), ^uint64(0)},
		{0x8080808080808080, 0x8080808080808080},
		{0x8000800080008000, 0x8000800080008000},
		{0x8000000080000000, 0x8000000080000000},
		{0x8000000000000000, 0x8000000000000000},
		{0x7f7f7f7f7f7f7f7f, 0x0101010101010101},
		{0x7fff7fff7fff7fff, 0xffffffffffffffff},
		{0x7fffffff7fffffff, 0x0000000100000001},
		{0x7fc000007fc00000, 0xffc00000ff800001}, // f32 NaNs / -inf+payload
		{0x7ff8000000000000, 0xfff0000000000001}, // f64 NaN / sNaN
		{0x3f8000004048f5c3, 0xc248f5c300000000}, // f32 1.0, pi-ish, -50.24, +0
		{0x4f80000041dfffff, 0xcf000000c1dfffff}, // f32 2^32, near-2^31 bounds
		{0x8000000000000000, 0x0000000000000000}, // f64 -0, +0
		{0x41dfffffffc00000, 0x43f0000000000000}, // f64 2^31-1, 2^64
		{0x0102030405060708, 0x090a0b0c0d0e0f10},
		{0x1011121380402010, 0xfefdfcfb00ff7f80}, // swizzle/shuffle indices
		{0x0000000000000000, 0x8000000000000000}, // f64 +0, -0 (order swap)
		{0x3ff0000000000000, 0xc1e0000000000000}, // f64 1.0, -2^31
		{0x41e0000000000000, 0x7ff0000000000000}, // f64 2^31, +inf
	}
	r := rand.New(rand.NewSource(1))
	for i := 0; i < 48; i++ {
		vs = append(vs, [2]uint64{r.Uint64(), r.Uint64()})
	}
	return vs
}()

var simdGShifts = []int32{0, 1, 7, 8, 15, 16, 31, 32, 63, 64, 65, -1}

var simdGScalars32 = []int32{0, 1, -1, 127, -128, 255, 0x7fff, -0x8000, 0x12345678, -0x7fffffff - 1}
var simdGScalars64 = []int64{0, 1, -1, 0x123456789abcdef0, -0x7fffffffffffffff - 1}
var simdGFloats32 = []float32{0, -0.0, 1.5, -2.25, 3.4e38, float32(nan32)}
var simdGFloats64 = []float64{0, -0.0, 1.5, -2.25, 1.7e308, nan64}

// Which NaN an operation propagates when several operands are NaN is
// nondeterministic in wasm (both sides return some arithmetic NaN); those
// lanes compare loosely, everything else bit-for-bit.
func simdGNaNLanes(name string) int {
	switch name {
	case "simd_f32x4_add", "simd_f32x4_sub", "simd_f32x4_mul", "simd_f32x4_div", "simd_f32x4_min", "simd_f32x4_max", "simd_f32x4_sqrt",
		"simd_f32x4_ceil", "simd_f32x4_floor", "simd_f32x4_trunc", "simd_f32x4_nearest", "simd_f32x4_demote_f64x2_zero":
		return 4
	case "simd_f64x2_add", "simd_f64x2_sub", "simd_f64x2_mul", "simd_f64x2_div", "simd_f64x2_min", "simd_f64x2_max", "simd_f64x2_sqrt",
		"simd_f64x2_ceil", "simd_f64x2_floor", "simd_f64x2_trunc", "simd_f64x2_nearest", "simd_f64x2_promote_low_f32x4":
		return 2
	}
	return 0
}

func simdGLaneIsNaN(v [2]uint64, lanes, i int) bool {
	if lanes == 4 {
		x := uint32(v[i>>1] >> (32 * uint(i&1)))
		return x&0x7f800000 == 0x7f800000 && x&0x007fffff != 0
	}
	x := v[i]
	return x&0x7ff0000000000000 == 0x7ff0000000000000 && x&0x000fffffffffffff != 0
}

func simdGEq(got, want [2]uint64, lanes int) bool {
	if got == want {
		return true
	}
	if lanes == 0 {
		return false
	}
	for i := 0; i < lanes; i++ {
		var g, w uint64
		if lanes == 4 {
			g = uint64(uint32(got[i>>1] >> (32 * uint(i&1))))
			w = uint64(uint32(want[i>>1] >> (32 * uint(i&1))))
		} else {
			g, w = got[i], want[i]
		}
		if g == w {
			continue
		}
		if !simdGLaneIsNaN(got, lanes, i) || !simdGLaneIsNaN(want, lanes, i) {
			return false
		}
	}
	return true
}

var simdG_vv_v = map[string]struct {
	g func(V128, V128) V128
	s func([2]uint64, [2]uint64) [2]uint64
}{
	"simd_f32x4_add":                 {simd_g_f32x4_add, simd_f32x4_add},
	"simd_f32x4_div":                 {simd_g_f32x4_div, simd_f32x4_div},
	"simd_f32x4_eq":                  {simd_g_f32x4_eq, simd_f32x4_eq},
	"simd_f32x4_ge":                  {simd_g_f32x4_ge, simd_f32x4_ge},
	"simd_f32x4_gt":                  {simd_g_f32x4_gt, simd_f32x4_gt},
	"simd_f32x4_le":                  {simd_g_f32x4_le, simd_f32x4_le},
	"simd_f32x4_lt":                  {simd_g_f32x4_lt, simd_f32x4_lt},
	"simd_f32x4_max":                 {simd_g_f32x4_max, simd_f32x4_max},
	"simd_f32x4_min":                 {simd_g_f32x4_min, simd_f32x4_min},
	"simd_f32x4_mul":                 {simd_g_f32x4_mul, simd_f32x4_mul},
	"simd_f32x4_ne":                  {simd_g_f32x4_ne, simd_f32x4_ne},
	"simd_f32x4_pmax":                {simd_g_f32x4_pmax, simd_f32x4_pmax},
	"simd_f32x4_pmin":                {simd_g_f32x4_pmin, simd_f32x4_pmin},
	"simd_f32x4_sub":                 {simd_g_f32x4_sub, simd_f32x4_sub},
	"simd_f64x2_add":                 {simd_g_f64x2_add, simd_f64x2_add},
	"simd_f64x2_div":                 {simd_g_f64x2_div, simd_f64x2_div},
	"simd_f64x2_eq":                  {simd_g_f64x2_eq, simd_f64x2_eq},
	"simd_f64x2_ge":                  {simd_g_f64x2_ge, simd_f64x2_ge},
	"simd_f64x2_gt":                  {simd_g_f64x2_gt, simd_f64x2_gt},
	"simd_f64x2_le":                  {simd_g_f64x2_le, simd_f64x2_le},
	"simd_f64x2_lt":                  {simd_g_f64x2_lt, simd_f64x2_lt},
	"simd_f64x2_max":                 {simd_g_f64x2_max, simd_f64x2_max},
	"simd_f64x2_min":                 {simd_g_f64x2_min, simd_f64x2_min},
	"simd_f64x2_mul":                 {simd_g_f64x2_mul, simd_f64x2_mul},
	"simd_f64x2_ne":                  {simd_g_f64x2_ne, simd_f64x2_ne},
	"simd_f64x2_pmax":                {simd_g_f64x2_pmax, simd_f64x2_pmax},
	"simd_f64x2_pmin":                {simd_g_f64x2_pmin, simd_f64x2_pmin},
	"simd_f64x2_sub":                 {simd_g_f64x2_sub, simd_f64x2_sub},
	"simd_i16x8_add":                 {simd_g_i16x8_add, simd_i16x8_add},
	"simd_i16x8_add_sat_s":           {simd_g_i16x8_add_sat_s, simd_i16x8_add_sat_s},
	"simd_i16x8_add_sat_u":           {simd_g_i16x8_add_sat_u, simd_i16x8_add_sat_u},
	"simd_i16x8_avgr_u":              {simd_g_i16x8_avgr_u, simd_i16x8_avgr_u},
	"simd_i16x8_eq":                  {simd_g_i16x8_eq, simd_i16x8_eq},
	"simd_i16x8_extmul_high_i8x16_s": {simd_g_i16x8_extmul_high_i8x16_s, simd_i16x8_extmul_high_i8x16_s},
	"simd_i16x8_extmul_high_i8x16_u": {simd_g_i16x8_extmul_high_i8x16_u, simd_i16x8_extmul_high_i8x16_u},
	"simd_i16x8_extmul_low_i8x16_s":  {simd_g_i16x8_extmul_low_i8x16_s, simd_i16x8_extmul_low_i8x16_s},
	"simd_i16x8_extmul_low_i8x16_u":  {simd_g_i16x8_extmul_low_i8x16_u, simd_i16x8_extmul_low_i8x16_u},
	"simd_i16x8_ge_s":                {simd_g_i16x8_ge_s, simd_i16x8_ge_s},
	"simd_i16x8_ge_u":                {simd_g_i16x8_ge_u, simd_i16x8_ge_u},
	"simd_i16x8_gt_s":                {simd_g_i16x8_gt_s, simd_i16x8_gt_s},
	"simd_i16x8_gt_u":                {simd_g_i16x8_gt_u, simd_i16x8_gt_u},
	"simd_i16x8_le_s":                {simd_g_i16x8_le_s, simd_i16x8_le_s},
	"simd_i16x8_le_u":                {simd_g_i16x8_le_u, simd_i16x8_le_u},
	"simd_i16x8_lt_s":                {simd_g_i16x8_lt_s, simd_i16x8_lt_s},
	"simd_i16x8_lt_u":                {simd_g_i16x8_lt_u, simd_i16x8_lt_u},
	"simd_i16x8_max_s":               {simd_g_i16x8_max_s, simd_i16x8_max_s},
	"simd_i16x8_max_u":               {simd_g_i16x8_max_u, simd_i16x8_max_u},
	"simd_i16x8_min_s":               {simd_g_i16x8_min_s, simd_i16x8_min_s},
	"simd_i16x8_min_u":               {simd_g_i16x8_min_u, simd_i16x8_min_u},
	"simd_i16x8_mul":                 {simd_g_i16x8_mul, simd_i16x8_mul},
	"simd_i16x8_narrow_i32x4_s":      {simd_g_i16x8_narrow_i32x4_s, simd_i16x8_narrow_i32x4_s},
	"simd_i16x8_narrow_i32x4_u":      {simd_g_i16x8_narrow_i32x4_u, simd_i16x8_narrow_i32x4_u},
	"simd_i16x8_ne":                  {simd_g_i16x8_ne, simd_i16x8_ne},
	"simd_i16x8_q15mulr_sat_s":       {simd_g_i16x8_q15mulr_sat_s, simd_i16x8_q15mulr_sat_s},
	"simd_i16x8_sub":                 {simd_g_i16x8_sub, simd_i16x8_sub},
	"simd_i16x8_sub_sat_s":           {simd_g_i16x8_sub_sat_s, simd_i16x8_sub_sat_s},
	"simd_i16x8_sub_sat_u":           {simd_g_i16x8_sub_sat_u, simd_i16x8_sub_sat_u},
	"simd_i32x4_add":                 {simd_g_i32x4_add, simd_i32x4_add},
	"simd_i32x4_dot_i16x8_s":         {simd_g_i32x4_dot_i16x8_s, simd_i32x4_dot_i16x8_s},
	"simd_i32x4_eq":                  {simd_g_i32x4_eq, simd_i32x4_eq},
	"simd_i32x4_extmul_high_i16x8_s": {simd_g_i32x4_extmul_high_i16x8_s, simd_i32x4_extmul_high_i16x8_s},
	"simd_i32x4_extmul_high_i16x8_u": {simd_g_i32x4_extmul_high_i16x8_u, simd_i32x4_extmul_high_i16x8_u},
	"simd_i32x4_extmul_low_i16x8_s":  {simd_g_i32x4_extmul_low_i16x8_s, simd_i32x4_extmul_low_i16x8_s},
	"simd_i32x4_extmul_low_i16x8_u":  {simd_g_i32x4_extmul_low_i16x8_u, simd_i32x4_extmul_low_i16x8_u},
	"simd_i32x4_ge_s":                {simd_g_i32x4_ge_s, simd_i32x4_ge_s},
	"simd_i32x4_ge_u":                {simd_g_i32x4_ge_u, simd_i32x4_ge_u},
	"simd_i32x4_gt_s":                {simd_g_i32x4_gt_s, simd_i32x4_gt_s},
	"simd_i32x4_gt_u":                {simd_g_i32x4_gt_u, simd_i32x4_gt_u},
	"simd_i32x4_le_s":                {simd_g_i32x4_le_s, simd_i32x4_le_s},
	"simd_i32x4_le_u":                {simd_g_i32x4_le_u, simd_i32x4_le_u},
	"simd_i32x4_lt_s":                {simd_g_i32x4_lt_s, simd_i32x4_lt_s},
	"simd_i32x4_lt_u":                {simd_g_i32x4_lt_u, simd_i32x4_lt_u},
	"simd_i32x4_max_s":               {simd_g_i32x4_max_s, simd_i32x4_max_s},
	"simd_i32x4_max_u":               {simd_g_i32x4_max_u, simd_i32x4_max_u},
	"simd_i32x4_min_s":               {simd_g_i32x4_min_s, simd_i32x4_min_s},
	"simd_i32x4_min_u":               {simd_g_i32x4_min_u, simd_i32x4_min_u},
	"simd_i32x4_mul":                 {simd_g_i32x4_mul, simd_i32x4_mul},
	"simd_i32x4_ne":                  {simd_g_i32x4_ne, simd_i32x4_ne},
	"simd_i32x4_sub":                 {simd_g_i32x4_sub, simd_i32x4_sub},
	"simd_i64x2_add":                 {simd_g_i64x2_add, simd_i64x2_add},
	"simd_i64x2_eq":                  {simd_g_i64x2_eq, simd_i64x2_eq},
	"simd_i64x2_extmul_high_i32x4_s": {simd_g_i64x2_extmul_high_i32x4_s, simd_i64x2_extmul_high_i32x4_s},
	"simd_i64x2_extmul_high_i32x4_u": {simd_g_i64x2_extmul_high_i32x4_u, simd_i64x2_extmul_high_i32x4_u},
	"simd_i64x2_extmul_low_i32x4_s":  {simd_g_i64x2_extmul_low_i32x4_s, simd_i64x2_extmul_low_i32x4_s},
	"simd_i64x2_extmul_low_i32x4_u":  {simd_g_i64x2_extmul_low_i32x4_u, simd_i64x2_extmul_low_i32x4_u},
	"simd_i64x2_ge_s":                {simd_g_i64x2_ge_s, simd_i64x2_ge_s},
	"simd_i64x2_gt_s":                {simd_g_i64x2_gt_s, simd_i64x2_gt_s},
	"simd_i64x2_le_s":                {simd_g_i64x2_le_s, simd_i64x2_le_s},
	"simd_i64x2_lt_s":                {simd_g_i64x2_lt_s, simd_i64x2_lt_s},
	"simd_i64x2_mul":                 {simd_g_i64x2_mul, simd_i64x2_mul},
	"simd_i64x2_ne":                  {simd_g_i64x2_ne, simd_i64x2_ne},
	"simd_i64x2_sub":                 {simd_g_i64x2_sub, simd_i64x2_sub},
	"simd_i8x16_add":                 {simd_g_i8x16_add, simd_i8x16_add},
	"simd_i8x16_add_sat_s":           {simd_g_i8x16_add_sat_s, simd_i8x16_add_sat_s},
	"simd_i8x16_add_sat_u":           {simd_g_i8x16_add_sat_u, simd_i8x16_add_sat_u},
	"simd_i8x16_avgr_u":              {simd_g_i8x16_avgr_u, simd_i8x16_avgr_u},
	"simd_i8x16_eq":                  {simd_g_i8x16_eq, simd_i8x16_eq},
	"simd_i8x16_ge_s":                {simd_g_i8x16_ge_s, simd_i8x16_ge_s},
	"simd_i8x16_ge_u":                {simd_g_i8x16_ge_u, simd_i8x16_ge_u},
	"simd_i8x16_gt_s":                {simd_g_i8x16_gt_s, simd_i8x16_gt_s},
	"simd_i8x16_gt_u":                {simd_g_i8x16_gt_u, simd_i8x16_gt_u},
	"simd_i8x16_le_s":                {simd_g_i8x16_le_s, simd_i8x16_le_s},
	"simd_i8x16_le_u":                {simd_g_i8x16_le_u, simd_i8x16_le_u},
	"simd_i8x16_lt_s":                {simd_g_i8x16_lt_s, simd_i8x16_lt_s},
	"simd_i8x16_lt_u":                {simd_g_i8x16_lt_u, simd_i8x16_lt_u},
	"simd_i8x16_max_s":               {simd_g_i8x16_max_s, simd_i8x16_max_s},
	"simd_i8x16_max_u":               {simd_g_i8x16_max_u, simd_i8x16_max_u},
	"simd_i8x16_min_s":               {simd_g_i8x16_min_s, simd_i8x16_min_s},
	"simd_i8x16_min_u":               {simd_g_i8x16_min_u, simd_i8x16_min_u},
	"simd_i8x16_narrow_i16x8_s":      {simd_g_i8x16_narrow_i16x8_s, simd_i8x16_narrow_i16x8_s},
	"simd_i8x16_narrow_i16x8_u":      {simd_g_i8x16_narrow_i16x8_u, simd_i8x16_narrow_i16x8_u},
	"simd_i8x16_ne":                  {simd_g_i8x16_ne, simd_i8x16_ne},
	"simd_i8x16_sub":                 {simd_g_i8x16_sub, simd_i8x16_sub},
	"simd_i8x16_sub_sat_s":           {simd_g_i8x16_sub_sat_s, simd_i8x16_sub_sat_s},
	"simd_i8x16_sub_sat_u":           {simd_g_i8x16_sub_sat_u, simd_i8x16_sub_sat_u},
	"simd_i8x16_swizzle":             {simd_g_i8x16_swizzle, simd_i8x16_swizzle},
	"simd_v128_and":                  {simd_g_v128_and, simd_v128_and},
	"simd_v128_andnot":               {simd_g_v128_andnot, simd_v128_andnot},
	"simd_v128_or":                   {simd_g_v128_or, simd_v128_or},
	"simd_v128_xor":                  {simd_g_v128_xor, simd_v128_xor},
}

var simdG_v_v = map[string]struct {
	g func(V128) V128
	s func([2]uint64) [2]uint64
}{
	"simd_f32x4_abs":                     {simd_g_f32x4_abs, simd_f32x4_abs},
	"simd_f32x4_ceil":                    {simd_g_f32x4_ceil, simd_f32x4_ceil},
	"simd_f32x4_convert_i32x4_s":         {simd_g_f32x4_convert_i32x4_s, simd_f32x4_convert_i32x4_s},
	"simd_f32x4_convert_i32x4_u":         {simd_g_f32x4_convert_i32x4_u, simd_f32x4_convert_i32x4_u},
	"simd_f32x4_demote_f64x2_zero":       {simd_g_f32x4_demote_f64x2_zero, simd_f32x4_demote_f64x2_zero},
	"simd_f32x4_floor":                   {simd_g_f32x4_floor, simd_f32x4_floor},
	"simd_f32x4_nearest":                 {simd_g_f32x4_nearest, simd_f32x4_nearest},
	"simd_f32x4_neg":                     {simd_g_f32x4_neg, simd_f32x4_neg},
	"simd_f32x4_sqrt":                    {simd_g_f32x4_sqrt, simd_f32x4_sqrt},
	"simd_f32x4_trunc":                   {simd_g_f32x4_trunc, simd_f32x4_trunc},
	"simd_f64x2_abs":                     {simd_g_f64x2_abs, simd_f64x2_abs},
	"simd_f64x2_ceil":                    {simd_g_f64x2_ceil, simd_f64x2_ceil},
	"simd_f64x2_convert_low_i32x4_s":     {simd_g_f64x2_convert_low_i32x4_s, simd_f64x2_convert_low_i32x4_s},
	"simd_f64x2_convert_low_i32x4_u":     {simd_g_f64x2_convert_low_i32x4_u, simd_f64x2_convert_low_i32x4_u},
	"simd_f64x2_floor":                   {simd_g_f64x2_floor, simd_f64x2_floor},
	"simd_f64x2_nearest":                 {simd_g_f64x2_nearest, simd_f64x2_nearest},
	"simd_f64x2_neg":                     {simd_g_f64x2_neg, simd_f64x2_neg},
	"simd_f64x2_promote_low_f32x4":       {simd_g_f64x2_promote_low_f32x4, simd_f64x2_promote_low_f32x4},
	"simd_f64x2_sqrt":                    {simd_g_f64x2_sqrt, simd_f64x2_sqrt},
	"simd_f64x2_trunc":                   {simd_g_f64x2_trunc, simd_f64x2_trunc},
	"simd_i16x8_abs":                     {simd_g_i16x8_abs, simd_i16x8_abs},
	"simd_i16x8_extadd_pairwise_i8x16_s": {simd_g_i16x8_extadd_pairwise_i8x16_s, simd_i16x8_extadd_pairwise_i8x16_s},
	"simd_i16x8_extadd_pairwise_i8x16_u": {simd_g_i16x8_extadd_pairwise_i8x16_u, simd_i16x8_extadd_pairwise_i8x16_u},
	"simd_i16x8_extend_high_i8x16_s":     {simd_g_i16x8_extend_high_i8x16_s, simd_i16x8_extend_high_i8x16_s},
	"simd_i16x8_extend_high_i8x16_u":     {simd_g_i16x8_extend_high_i8x16_u, simd_i16x8_extend_high_i8x16_u},
	"simd_i16x8_extend_low_i8x16_s":      {simd_g_i16x8_extend_low_i8x16_s, simd_i16x8_extend_low_i8x16_s},
	"simd_i16x8_extend_low_i8x16_u":      {simd_g_i16x8_extend_low_i8x16_u, simd_i16x8_extend_low_i8x16_u},
	"simd_i16x8_neg":                     {simd_g_i16x8_neg, simd_i16x8_neg},
	"simd_i32x4_abs":                     {simd_g_i32x4_abs, simd_i32x4_abs},
	"simd_i32x4_extadd_pairwise_i16x8_s": {simd_g_i32x4_extadd_pairwise_i16x8_s, simd_i32x4_extadd_pairwise_i16x8_s},
	"simd_i32x4_extadd_pairwise_i16x8_u": {simd_g_i32x4_extadd_pairwise_i16x8_u, simd_i32x4_extadd_pairwise_i16x8_u},
	"simd_i32x4_extend_high_i16x8_s":     {simd_g_i32x4_extend_high_i16x8_s, simd_i32x4_extend_high_i16x8_s},
	"simd_i32x4_extend_high_i16x8_u":     {simd_g_i32x4_extend_high_i16x8_u, simd_i32x4_extend_high_i16x8_u},
	"simd_i32x4_extend_low_i16x8_s":      {simd_g_i32x4_extend_low_i16x8_s, simd_i32x4_extend_low_i16x8_s},
	"simd_i32x4_extend_low_i16x8_u":      {simd_g_i32x4_extend_low_i16x8_u, simd_i32x4_extend_low_i16x8_u},
	"simd_i32x4_neg":                     {simd_g_i32x4_neg, simd_i32x4_neg},
	"simd_i32x4_trunc_sat_f32x4_s":       {simd_g_i32x4_trunc_sat_f32x4_s, simd_i32x4_trunc_sat_f32x4_s},
	"simd_i32x4_trunc_sat_f32x4_u":       {simd_g_i32x4_trunc_sat_f32x4_u, simd_i32x4_trunc_sat_f32x4_u},
	"simd_i32x4_trunc_sat_f64x2_s_zero":  {simd_g_i32x4_trunc_sat_f64x2_s_zero, simd_i32x4_trunc_sat_f64x2_s_zero},
	"simd_i32x4_trunc_sat_f64x2_u_zero":  {simd_g_i32x4_trunc_sat_f64x2_u_zero, simd_i32x4_trunc_sat_f64x2_u_zero},
	"simd_i64x2_abs":                     {simd_g_i64x2_abs, simd_i64x2_abs},
	"simd_i64x2_extend_high_i32x4_s":     {simd_g_i64x2_extend_high_i32x4_s, simd_i64x2_extend_high_i32x4_s},
	"simd_i64x2_extend_high_i32x4_u":     {simd_g_i64x2_extend_high_i32x4_u, simd_i64x2_extend_high_i32x4_u},
	"simd_i64x2_extend_low_i32x4_s":      {simd_g_i64x2_extend_low_i32x4_s, simd_i64x2_extend_low_i32x4_s},
	"simd_i64x2_extend_low_i32x4_u":      {simd_g_i64x2_extend_low_i32x4_u, simd_i64x2_extend_low_i32x4_u},
	"simd_i64x2_neg":                     {simd_g_i64x2_neg, simd_i64x2_neg},
	"simd_i8x16_abs":                     {simd_g_i8x16_abs, simd_i8x16_abs},
	"simd_i8x16_neg":                     {simd_g_i8x16_neg, simd_i8x16_neg},
	"simd_i8x16_popcnt":                  {simd_g_i8x16_popcnt, simd_i8x16_popcnt},
	"simd_v128_not":                      {simd_g_v128_not, simd_v128_not},
}

var simdG_vvv_v = map[string]struct {
	g func(V128, V128, V128) V128
	s func([2]uint64, [2]uint64, [2]uint64) [2]uint64
}{
	"simd_i8x16_shuffle":  {simd_g_i8x16_shuffle, simd_i8x16_shuffle},
	"simd_v128_bitselect": {simd_g_v128_bitselect, simd_v128_bitselect},
}

var simdG_vs_v = map[string]struct {
	g func(V128, int32) V128
	s func([2]uint64, int32) [2]uint64
}{
	"simd_i16x8_shl":   {simd_g_i16x8_shl, simd_i16x8_shl},
	"simd_i16x8_shr_s": {simd_g_i16x8_shr_s, simd_i16x8_shr_s},
	"simd_i16x8_shr_u": {simd_g_i16x8_shr_u, simd_i16x8_shr_u},
	"simd_i32x4_shl":   {simd_g_i32x4_shl, simd_i32x4_shl},
	"simd_i32x4_shr_s": {simd_g_i32x4_shr_s, simd_i32x4_shr_s},
	"simd_i32x4_shr_u": {simd_g_i32x4_shr_u, simd_i32x4_shr_u},
	"simd_i64x2_shl":   {simd_g_i64x2_shl, simd_i64x2_shl},
	"simd_i64x2_shr_s": {simd_g_i64x2_shr_s, simd_i64x2_shr_s},
	"simd_i64x2_shr_u": {simd_g_i64x2_shr_u, simd_i64x2_shr_u},
	"simd_i8x16_shl":   {simd_g_i8x16_shl, simd_i8x16_shl},
	"simd_i8x16_shr_s": {simd_g_i8x16_shr_s, simd_i8x16_shr_s},
	"simd_i8x16_shr_u": {simd_g_i8x16_shr_u, simd_i8x16_shr_u},
}

var simdG_v_i32 = map[string]struct {
	g func(V128) int32
	s func([2]uint64) int32
}{
	"simd_i16x8_all_true": {simd_g_i16x8_all_true, simd_i16x8_all_true},
	"simd_i16x8_bitmask":  {simd_g_i16x8_bitmask, simd_i16x8_bitmask},
	"simd_i32x4_all_true": {simd_g_i32x4_all_true, simd_i32x4_all_true},
	"simd_i32x4_bitmask":  {simd_g_i32x4_bitmask, simd_i32x4_bitmask},
	"simd_i64x2_all_true": {simd_g_i64x2_all_true, simd_i64x2_all_true},
	"simd_i64x2_bitmask":  {simd_g_i64x2_bitmask, simd_i64x2_bitmask},
	"simd_i8x16_all_true": {simd_g_i8x16_all_true, simd_i8x16_all_true},
	"simd_i8x16_bitmask":  {simd_g_i8x16_bitmask, simd_i8x16_bitmask},
	"simd_v128_any_true":  {simd_g_v128_any_true, simd_v128_any_true},
}

var simdG_v_i64 = map[string]struct {
	g func(V128) int64
	s func([2]uint64) int64
}{}

var simdG_v_f32 = map[string]struct {
	g func(V128) float32
	s func([2]uint64) float32
}{}

var simdG_v_f64 = map[string]struct {
	g func(V128) float64
	s func([2]uint64) float64
}{}

var simdG_vi32_v = map[string]struct {
	g func(V128, int32) V128
	s func([2]uint64, int32) [2]uint64
}{}

var simdG_vi64_v = map[string]struct {
	g func(V128, int64) V128
	s func([2]uint64, int64) [2]uint64
}{}

var simdG_vf32_v = map[string]struct {
	g func(V128, float32) V128
	s func([2]uint64, float32) [2]uint64
}{}

var simdG_vf64_v = map[string]struct {
	g func(V128, float64) V128
	s func([2]uint64, float64) [2]uint64
}{}

var simdG_s32_v = map[string]struct {
	g func(int32) V128
	s func(int32) [2]uint64
}{
	"simd_i16x8_splat": {simd_g_i16x8_splat, simd_i16x8_splat},
	"simd_i32x4_splat": {simd_g_i32x4_splat, simd_i32x4_splat},
	"simd_i8x16_splat": {simd_g_i8x16_splat, simd_i8x16_splat},
}

var simdG_s64_v = map[string]struct {
	g func(int64) V128
	s func(int64) [2]uint64
}{
	"simd_i64x2_splat": {simd_g_i64x2_splat, simd_i64x2_splat},
}

var simdG_f32_v = map[string]struct {
	g func(float32) V128
	s func(float32) [2]uint64
}{
	"simd_f32x4_splat": {simd_g_f32x4_splat, simd_f32x4_splat},
}

var simdG_f64_v = map[string]struct {
	g func(float64) V128
	s func(float64) [2]uint64
}{
	"simd_f64x2_splat": {simd_g_f64x2_splat, simd_f64x2_splat},
}

func TestGoSIMDMatchesScalar(t *testing.T) {
	for name, fns := range simdG_vv_v {
		lanes := simdGNaNLanes(name)
		for _, a := range simdGCorpus {
			for _, b := range simdGCorpus {
				if got, want := simd_g_to(fns.g(simd_g_from(a), simd_g_from(b))), fns.s(a, b); !simdGEq(got, want, lanes) {
					t.Fatalf("%s(%#x, %#x) = %#x, scalar %#x", name, a, b, got, want)
				}
			}
		}
	}
	for name, fns := range simdG_v_v {
		lanes := simdGNaNLanes(name)
		for _, a := range simdGCorpus {
			if got, want := simd_g_to(fns.g(simd_g_from(a))), fns.s(a); !simdGEq(got, want, lanes) {
				t.Fatalf("%s(%#x) = %#x, scalar %#x", name, a, got, want)
			}
		}
	}
	for name, fns := range simdG_vvv_v {
		for _, a := range simdGCorpus {
			for _, b := range simdGCorpus[:12] {
				for _, c := range simdGCorpus[:12] {
					if got, want := simd_g_to(fns.g(simd_g_from(a), simd_g_from(b), simd_g_from(c))), fns.s(a, b, c); got != want {
						t.Fatalf("%s(%#x, %#x, %#x) = %#x, scalar %#x", name, a, b, c, got, want)
					}
				}
			}
		}
	}
	for name, fns := range simdG_vs_v {
		for _, a := range simdGCorpus {
			for _, s := range simdGShifts {
				if got, want := simd_g_to(fns.g(simd_g_from(a), s)), fns.s(a, s); got != want {
					t.Fatalf("%s(%#x, %d) = %#x, scalar %#x", name, a, s, got, want)
				}
			}
		}
	}
	for name, fns := range simdG_v_i32 {
		for _, a := range simdGCorpus {
			if got, want := fns.g(simd_g_from(a)), fns.s(a); got != want {
				t.Fatalf("%s(%#x) = %d, scalar %d", name, a, got, want)
			}
		}
	}
	for name, fns := range simdG_v_i64 {
		for _, a := range simdGCorpus {
			if got, want := fns.g(simd_g_from(a)), fns.s(a); got != want {
				t.Fatalf("%s(%#x) = %d, scalar %d", name, a, got, want)
			}
		}
	}
	for name, fns := range simdG_v_f32 {
		for _, a := range simdGCorpus {
			if got, want := fns.g(simd_g_from(a)), fns.s(a); math.Float32bits(got) != math.Float32bits(want) {
				t.Fatalf("%s(%#x) = %v, scalar %v", name, a, got, want)
			}
		}
	}
	for name, fns := range simdG_v_f64 {
		for _, a := range simdGCorpus {
			if got, want := fns.g(simd_g_from(a)), fns.s(a); math.Float64bits(got) != math.Float64bits(want) {
				t.Fatalf("%s(%#x) = %v, scalar %v", name, a, got, want)
			}
		}
	}
	for name, fns := range simdG_vi32_v {
		for _, a := range simdGCorpus {
			for _, x := range simdGScalars32 {
				if got, want := simd_g_to(fns.g(simd_g_from(a), x)), fns.s(a, x); got != want {
					t.Fatalf("%s(%#x, %d) = %#x, scalar %#x", name, a, x, got, want)
				}
			}
		}
	}
	for name, fns := range simdG_vi64_v {
		for _, a := range simdGCorpus {
			for _, x := range simdGScalars64 {
				if got, want := simd_g_to(fns.g(simd_g_from(a), x)), fns.s(a, x); got != want {
					t.Fatalf("%s(%#x, %d) = %#x, scalar %#x", name, a, x, got, want)
				}
			}
		}
	}
	for name, fns := range simdG_vf32_v {
		for _, a := range simdGCorpus {
			for _, x := range simdGFloats32 {
				if got, want := simd_g_to(fns.g(simd_g_from(a), x)), fns.s(a, x); got != want {
					t.Fatalf("%s(%#x, %v) = %#x, scalar %#x", name, a, x, got, want)
				}
			}
		}
	}
	for name, fns := range simdG_vf64_v {
		for _, a := range simdGCorpus {
			for _, x := range simdGFloats64 {
				if got, want := simd_g_to(fns.g(simd_g_from(a), x)), fns.s(a, x); got != want {
					t.Fatalf("%s(%#x, %v) = %#x, scalar %#x", name, a, x, got, want)
				}
			}
		}
	}
	for name, fns := range simdG_s32_v {
		for _, x := range simdGScalars32 {
			if got, want := simd_g_to(fns.g(x)), fns.s(x); got != want {
				t.Fatalf("%s(%d) = %#x, scalar %#x", name, x, got, want)
			}
		}
	}
	for name, fns := range simdG_s64_v {
		for _, x := range simdGScalars64 {
			if got, want := simd_g_to(fns.g(x)), fns.s(x); got != want {
				t.Fatalf("%s(%d) = %#x, scalar %#x", name, x, got, want)
			}
		}
	}
	for name, fns := range simdG_f32_v {
		for _, x := range simdGFloats32 {
			if got, want := simd_g_to(fns.g(x)), fns.s(x); got != want {
				t.Fatalf("%s(%v) = %#x, scalar %#x", name, x, got, want)
			}
		}
	}
	for name, fns := range simdG_f64_v {
		for _, x := range simdGFloats64 {
			if got, want := simd_g_to(fns.g(x)), fns.s(x); got != want {
				t.Fatalf("%s(%v) = %#x, scalar %#x", name, x, got, want)
			}
		}
	}
}

// The constant-pattern shuffle forms must match the generic shuffle for
// every pattern in the corpus, after the emitter's normalization.
func TestGoSIMDShuffleConst(t *testing.T) {
	for _, pat := range simdGCorpus {
		var ia, ib [2]uint64
		singleA, singleB := true, true
		for i := 0; i < 16; i++ {
			idx := uint8(pat[i>>3] >> (8 * uint(i&7)))
			va, vb := uint8(0x80), uint8(0x80)
			if idx < 16 {
				va = idx
				singleB = false
			} else if idx < 32 {
				vb = idx - 16
				singleA = false
			}
			ia[i>>3] |= uint64(va) << (8 * uint(i&7))
			ib[i>>3] |= uint64(vb) << (8 * uint(i&7))
		}
		for _, a := range simdGCorpus[:20] {
			for _, b := range simdGCorpus[:20] {
				want := simd_i8x16_shuffle(a, b, pat)
				if got := simd_g_to(simd_g_i8x16_shuffle2(simd_g_from(a), simd_g_from(b), simd_g_from(ia), simd_g_from(ib))); got != want {
					t.Fatalf("shuffle2(%#x, %#x, pat %#x) = %#x, want %#x", a, b, pat, got, want)
				}
				if singleA {
					if got := simd_g_to(simd_g_i8x16_swizzle_c(simd_g_from(a), simd_g_from(ia))); got != want {
						t.Fatalf("swizzle_c(a) pat %#x = %#x, want %#x", pat, got, want)
					}
				}
				if singleB {
					if got := simd_g_to(simd_g_i8x16_swizzle_c(simd_g_from(b), simd_g_from(ib))); got != want {
						t.Fatalf("swizzle_c(b) pat %#x = %#x, want %#x", pat, got, want)
					}
				}
			}
		}
	}
}

func TestGoSIMDLanes(t *testing.T) {
	for _, a := range simdGCorpus {
		if got, want := simd_g_i8x16_extract_lane_s_l0(simd_g_from(a)), simd_i8x16_extract_lane_s(a, 0); got != want {
			t.Fatalf("simd_i8x16_extract_lane_s lane 0: %v, scalar %v", got, want)
		}
		if got, want := simd_g_i8x16_extract_lane_s_l1(simd_g_from(a)), simd_i8x16_extract_lane_s(a, 1); got != want {
			t.Fatalf("simd_i8x16_extract_lane_s lane 1: %v, scalar %v", got, want)
		}
		if got, want := simd_g_i8x16_extract_lane_s_l2(simd_g_from(a)), simd_i8x16_extract_lane_s(a, 2); got != want {
			t.Fatalf("simd_i8x16_extract_lane_s lane 2: %v, scalar %v", got, want)
		}
		if got, want := simd_g_i8x16_extract_lane_s_l3(simd_g_from(a)), simd_i8x16_extract_lane_s(a, 3); got != want {
			t.Fatalf("simd_i8x16_extract_lane_s lane 3: %v, scalar %v", got, want)
		}
		if got, want := simd_g_i8x16_extract_lane_s_l4(simd_g_from(a)), simd_i8x16_extract_lane_s(a, 4); got != want {
			t.Fatalf("simd_i8x16_extract_lane_s lane 4: %v, scalar %v", got, want)
		}
		if got, want := simd_g_i8x16_extract_lane_s_l5(simd_g_from(a)), simd_i8x16_extract_lane_s(a, 5); got != want {
			t.Fatalf("simd_i8x16_extract_lane_s lane 5: %v, scalar %v", got, want)
		}
		if got, want := simd_g_i8x16_extract_lane_s_l6(simd_g_from(a)), simd_i8x16_extract_lane_s(a, 6); got != want {
			t.Fatalf("simd_i8x16_extract_lane_s lane 6: %v, scalar %v", got, want)
		}
		if got, want := simd_g_i8x16_extract_lane_s_l7(simd_g_from(a)), simd_i8x16_extract_lane_s(a, 7); got != want {
			t.Fatalf("simd_i8x16_extract_lane_s lane 7: %v, scalar %v", got, want)
		}
		if got, want := simd_g_i8x16_extract_lane_s_l8(simd_g_from(a)), simd_i8x16_extract_lane_s(a, 8); got != want {
			t.Fatalf("simd_i8x16_extract_lane_s lane 8: %v, scalar %v", got, want)
		}
		if got, want := simd_g_i8x16_extract_lane_s_l9(simd_g_from(a)), simd_i8x16_extract_lane_s(a, 9); got != want {
			t.Fatalf("simd_i8x16_extract_lane_s lane 9: %v, scalar %v", got, want)
		}
		if got, want := simd_g_i8x16_extract_lane_s_l10(simd_g_from(a)), simd_i8x16_extract_lane_s(a, 10); got != want {
			t.Fatalf("simd_i8x16_extract_lane_s lane 10: %v, scalar %v", got, want)
		}
		if got, want := simd_g_i8x16_extract_lane_s_l11(simd_g_from(a)), simd_i8x16_extract_lane_s(a, 11); got != want {
			t.Fatalf("simd_i8x16_extract_lane_s lane 11: %v, scalar %v", got, want)
		}
		if got, want := simd_g_i8x16_extract_lane_s_l12(simd_g_from(a)), simd_i8x16_extract_lane_s(a, 12); got != want {
			t.Fatalf("simd_i8x16_extract_lane_s lane 12: %v, scalar %v", got, want)
		}
		if got, want := simd_g_i8x16_extract_lane_s_l13(simd_g_from(a)), simd_i8x16_extract_lane_s(a, 13); got != want {
			t.Fatalf("simd_i8x16_extract_lane_s lane 13: %v, scalar %v", got, want)
		}
		if got, want := simd_g_i8x16_extract_lane_s_l14(simd_g_from(a)), simd_i8x16_extract_lane_s(a, 14); got != want {
			t.Fatalf("simd_i8x16_extract_lane_s lane 14: %v, scalar %v", got, want)
		}
		if got, want := simd_g_i8x16_extract_lane_s_l15(simd_g_from(a)), simd_i8x16_extract_lane_s(a, 15); got != want {
			t.Fatalf("simd_i8x16_extract_lane_s lane 15: %v, scalar %v", got, want)
		}
		if got, want := simd_g_i8x16_extract_lane_u_l0(simd_g_from(a)), simd_i8x16_extract_lane_u(a, 0); got != want {
			t.Fatalf("simd_i8x16_extract_lane_u lane 0: %v, scalar %v", got, want)
		}
		if got, want := simd_g_i8x16_extract_lane_u_l1(simd_g_from(a)), simd_i8x16_extract_lane_u(a, 1); got != want {
			t.Fatalf("simd_i8x16_extract_lane_u lane 1: %v, scalar %v", got, want)
		}
		if got, want := simd_g_i8x16_extract_lane_u_l2(simd_g_from(a)), simd_i8x16_extract_lane_u(a, 2); got != want {
			t.Fatalf("simd_i8x16_extract_lane_u lane 2: %v, scalar %v", got, want)
		}
		if got, want := simd_g_i8x16_extract_lane_u_l3(simd_g_from(a)), simd_i8x16_extract_lane_u(a, 3); got != want {
			t.Fatalf("simd_i8x16_extract_lane_u lane 3: %v, scalar %v", got, want)
		}
		if got, want := simd_g_i8x16_extract_lane_u_l4(simd_g_from(a)), simd_i8x16_extract_lane_u(a, 4); got != want {
			t.Fatalf("simd_i8x16_extract_lane_u lane 4: %v, scalar %v", got, want)
		}
		if got, want := simd_g_i8x16_extract_lane_u_l5(simd_g_from(a)), simd_i8x16_extract_lane_u(a, 5); got != want {
			t.Fatalf("simd_i8x16_extract_lane_u lane 5: %v, scalar %v", got, want)
		}
		if got, want := simd_g_i8x16_extract_lane_u_l6(simd_g_from(a)), simd_i8x16_extract_lane_u(a, 6); got != want {
			t.Fatalf("simd_i8x16_extract_lane_u lane 6: %v, scalar %v", got, want)
		}
		if got, want := simd_g_i8x16_extract_lane_u_l7(simd_g_from(a)), simd_i8x16_extract_lane_u(a, 7); got != want {
			t.Fatalf("simd_i8x16_extract_lane_u lane 7: %v, scalar %v", got, want)
		}
		if got, want := simd_g_i8x16_extract_lane_u_l8(simd_g_from(a)), simd_i8x16_extract_lane_u(a, 8); got != want {
			t.Fatalf("simd_i8x16_extract_lane_u lane 8: %v, scalar %v", got, want)
		}
		if got, want := simd_g_i8x16_extract_lane_u_l9(simd_g_from(a)), simd_i8x16_extract_lane_u(a, 9); got != want {
			t.Fatalf("simd_i8x16_extract_lane_u lane 9: %v, scalar %v", got, want)
		}
		if got, want := simd_g_i8x16_extract_lane_u_l10(simd_g_from(a)), simd_i8x16_extract_lane_u(a, 10); got != want {
			t.Fatalf("simd_i8x16_extract_lane_u lane 10: %v, scalar %v", got, want)
		}
		if got, want := simd_g_i8x16_extract_lane_u_l11(simd_g_from(a)), simd_i8x16_extract_lane_u(a, 11); got != want {
			t.Fatalf("simd_i8x16_extract_lane_u lane 11: %v, scalar %v", got, want)
		}
		if got, want := simd_g_i8x16_extract_lane_u_l12(simd_g_from(a)), simd_i8x16_extract_lane_u(a, 12); got != want {
			t.Fatalf("simd_i8x16_extract_lane_u lane 12: %v, scalar %v", got, want)
		}
		if got, want := simd_g_i8x16_extract_lane_u_l13(simd_g_from(a)), simd_i8x16_extract_lane_u(a, 13); got != want {
			t.Fatalf("simd_i8x16_extract_lane_u lane 13: %v, scalar %v", got, want)
		}
		if got, want := simd_g_i8x16_extract_lane_u_l14(simd_g_from(a)), simd_i8x16_extract_lane_u(a, 14); got != want {
			t.Fatalf("simd_i8x16_extract_lane_u lane 14: %v, scalar %v", got, want)
		}
		if got, want := simd_g_i8x16_extract_lane_u_l15(simd_g_from(a)), simd_i8x16_extract_lane_u(a, 15); got != want {
			t.Fatalf("simd_i8x16_extract_lane_u lane 15: %v, scalar %v", got, want)
		}
		for _, x := range simdGScalars32 {
			if got, want := simd_g_to(simd_g_i8x16_replace_lane_l0(simd_g_from(a), x)), simd_i8x16_replace_lane(a, 0, x); got != want {
				t.Fatalf("simd_i8x16_replace_lane lane 0 x=%v: %#x, scalar %#x", x, got, want)
			}
		}
		for _, x := range simdGScalars32 {
			if got, want := simd_g_to(simd_g_i8x16_replace_lane_l1(simd_g_from(a), x)), simd_i8x16_replace_lane(a, 1, x); got != want {
				t.Fatalf("simd_i8x16_replace_lane lane 1 x=%v: %#x, scalar %#x", x, got, want)
			}
		}
		for _, x := range simdGScalars32 {
			if got, want := simd_g_to(simd_g_i8x16_replace_lane_l2(simd_g_from(a), x)), simd_i8x16_replace_lane(a, 2, x); got != want {
				t.Fatalf("simd_i8x16_replace_lane lane 2 x=%v: %#x, scalar %#x", x, got, want)
			}
		}
		for _, x := range simdGScalars32 {
			if got, want := simd_g_to(simd_g_i8x16_replace_lane_l3(simd_g_from(a), x)), simd_i8x16_replace_lane(a, 3, x); got != want {
				t.Fatalf("simd_i8x16_replace_lane lane 3 x=%v: %#x, scalar %#x", x, got, want)
			}
		}
		for _, x := range simdGScalars32 {
			if got, want := simd_g_to(simd_g_i8x16_replace_lane_l4(simd_g_from(a), x)), simd_i8x16_replace_lane(a, 4, x); got != want {
				t.Fatalf("simd_i8x16_replace_lane lane 4 x=%v: %#x, scalar %#x", x, got, want)
			}
		}
		for _, x := range simdGScalars32 {
			if got, want := simd_g_to(simd_g_i8x16_replace_lane_l5(simd_g_from(a), x)), simd_i8x16_replace_lane(a, 5, x); got != want {
				t.Fatalf("simd_i8x16_replace_lane lane 5 x=%v: %#x, scalar %#x", x, got, want)
			}
		}
		for _, x := range simdGScalars32 {
			if got, want := simd_g_to(simd_g_i8x16_replace_lane_l6(simd_g_from(a), x)), simd_i8x16_replace_lane(a, 6, x); got != want {
				t.Fatalf("simd_i8x16_replace_lane lane 6 x=%v: %#x, scalar %#x", x, got, want)
			}
		}
		for _, x := range simdGScalars32 {
			if got, want := simd_g_to(simd_g_i8x16_replace_lane_l7(simd_g_from(a), x)), simd_i8x16_replace_lane(a, 7, x); got != want {
				t.Fatalf("simd_i8x16_replace_lane lane 7 x=%v: %#x, scalar %#x", x, got, want)
			}
		}
		for _, x := range simdGScalars32 {
			if got, want := simd_g_to(simd_g_i8x16_replace_lane_l8(simd_g_from(a), x)), simd_i8x16_replace_lane(a, 8, x); got != want {
				t.Fatalf("simd_i8x16_replace_lane lane 8 x=%v: %#x, scalar %#x", x, got, want)
			}
		}
		for _, x := range simdGScalars32 {
			if got, want := simd_g_to(simd_g_i8x16_replace_lane_l9(simd_g_from(a), x)), simd_i8x16_replace_lane(a, 9, x); got != want {
				t.Fatalf("simd_i8x16_replace_lane lane 9 x=%v: %#x, scalar %#x", x, got, want)
			}
		}
		for _, x := range simdGScalars32 {
			if got, want := simd_g_to(simd_g_i8x16_replace_lane_l10(simd_g_from(a), x)), simd_i8x16_replace_lane(a, 10, x); got != want {
				t.Fatalf("simd_i8x16_replace_lane lane 10 x=%v: %#x, scalar %#x", x, got, want)
			}
		}
		for _, x := range simdGScalars32 {
			if got, want := simd_g_to(simd_g_i8x16_replace_lane_l11(simd_g_from(a), x)), simd_i8x16_replace_lane(a, 11, x); got != want {
				t.Fatalf("simd_i8x16_replace_lane lane 11 x=%v: %#x, scalar %#x", x, got, want)
			}
		}
		for _, x := range simdGScalars32 {
			if got, want := simd_g_to(simd_g_i8x16_replace_lane_l12(simd_g_from(a), x)), simd_i8x16_replace_lane(a, 12, x); got != want {
				t.Fatalf("simd_i8x16_replace_lane lane 12 x=%v: %#x, scalar %#x", x, got, want)
			}
		}
		for _, x := range simdGScalars32 {
			if got, want := simd_g_to(simd_g_i8x16_replace_lane_l13(simd_g_from(a), x)), simd_i8x16_replace_lane(a, 13, x); got != want {
				t.Fatalf("simd_i8x16_replace_lane lane 13 x=%v: %#x, scalar %#x", x, got, want)
			}
		}
		for _, x := range simdGScalars32 {
			if got, want := simd_g_to(simd_g_i8x16_replace_lane_l14(simd_g_from(a), x)), simd_i8x16_replace_lane(a, 14, x); got != want {
				t.Fatalf("simd_i8x16_replace_lane lane 14 x=%v: %#x, scalar %#x", x, got, want)
			}
		}
		for _, x := range simdGScalars32 {
			if got, want := simd_g_to(simd_g_i8x16_replace_lane_l15(simd_g_from(a), x)), simd_i8x16_replace_lane(a, 15, x); got != want {
				t.Fatalf("simd_i8x16_replace_lane lane 15 x=%v: %#x, scalar %#x", x, got, want)
			}
		}
		if got, want := simd_g_i16x8_extract_lane_s_l0(simd_g_from(a)), simd_i16x8_extract_lane_s(a, 0); got != want {
			t.Fatalf("simd_i16x8_extract_lane_s lane 0: %v, scalar %v", got, want)
		}
		if got, want := simd_g_i16x8_extract_lane_s_l1(simd_g_from(a)), simd_i16x8_extract_lane_s(a, 1); got != want {
			t.Fatalf("simd_i16x8_extract_lane_s lane 1: %v, scalar %v", got, want)
		}
		if got, want := simd_g_i16x8_extract_lane_s_l2(simd_g_from(a)), simd_i16x8_extract_lane_s(a, 2); got != want {
			t.Fatalf("simd_i16x8_extract_lane_s lane 2: %v, scalar %v", got, want)
		}
		if got, want := simd_g_i16x8_extract_lane_s_l3(simd_g_from(a)), simd_i16x8_extract_lane_s(a, 3); got != want {
			t.Fatalf("simd_i16x8_extract_lane_s lane 3: %v, scalar %v", got, want)
		}
		if got, want := simd_g_i16x8_extract_lane_s_l4(simd_g_from(a)), simd_i16x8_extract_lane_s(a, 4); got != want {
			t.Fatalf("simd_i16x8_extract_lane_s lane 4: %v, scalar %v", got, want)
		}
		if got, want := simd_g_i16x8_extract_lane_s_l5(simd_g_from(a)), simd_i16x8_extract_lane_s(a, 5); got != want {
			t.Fatalf("simd_i16x8_extract_lane_s lane 5: %v, scalar %v", got, want)
		}
		if got, want := simd_g_i16x8_extract_lane_s_l6(simd_g_from(a)), simd_i16x8_extract_lane_s(a, 6); got != want {
			t.Fatalf("simd_i16x8_extract_lane_s lane 6: %v, scalar %v", got, want)
		}
		if got, want := simd_g_i16x8_extract_lane_s_l7(simd_g_from(a)), simd_i16x8_extract_lane_s(a, 7); got != want {
			t.Fatalf("simd_i16x8_extract_lane_s lane 7: %v, scalar %v", got, want)
		}
		if got, want := simd_g_i16x8_extract_lane_u_l0(simd_g_from(a)), simd_i16x8_extract_lane_u(a, 0); got != want {
			t.Fatalf("simd_i16x8_extract_lane_u lane 0: %v, scalar %v", got, want)
		}
		if got, want := simd_g_i16x8_extract_lane_u_l1(simd_g_from(a)), simd_i16x8_extract_lane_u(a, 1); got != want {
			t.Fatalf("simd_i16x8_extract_lane_u lane 1: %v, scalar %v", got, want)
		}
		if got, want := simd_g_i16x8_extract_lane_u_l2(simd_g_from(a)), simd_i16x8_extract_lane_u(a, 2); got != want {
			t.Fatalf("simd_i16x8_extract_lane_u lane 2: %v, scalar %v", got, want)
		}
		if got, want := simd_g_i16x8_extract_lane_u_l3(simd_g_from(a)), simd_i16x8_extract_lane_u(a, 3); got != want {
			t.Fatalf("simd_i16x8_extract_lane_u lane 3: %v, scalar %v", got, want)
		}
		if got, want := simd_g_i16x8_extract_lane_u_l4(simd_g_from(a)), simd_i16x8_extract_lane_u(a, 4); got != want {
			t.Fatalf("simd_i16x8_extract_lane_u lane 4: %v, scalar %v", got, want)
		}
		if got, want := simd_g_i16x8_extract_lane_u_l5(simd_g_from(a)), simd_i16x8_extract_lane_u(a, 5); got != want {
			t.Fatalf("simd_i16x8_extract_lane_u lane 5: %v, scalar %v", got, want)
		}
		if got, want := simd_g_i16x8_extract_lane_u_l6(simd_g_from(a)), simd_i16x8_extract_lane_u(a, 6); got != want {
			t.Fatalf("simd_i16x8_extract_lane_u lane 6: %v, scalar %v", got, want)
		}
		if got, want := simd_g_i16x8_extract_lane_u_l7(simd_g_from(a)), simd_i16x8_extract_lane_u(a, 7); got != want {
			t.Fatalf("simd_i16x8_extract_lane_u lane 7: %v, scalar %v", got, want)
		}
		for _, x := range simdGScalars32 {
			if got, want := simd_g_to(simd_g_i16x8_replace_lane_l0(simd_g_from(a), x)), simd_i16x8_replace_lane(a, 0, x); got != want {
				t.Fatalf("simd_i16x8_replace_lane lane 0 x=%v: %#x, scalar %#x", x, got, want)
			}
		}
		for _, x := range simdGScalars32 {
			if got, want := simd_g_to(simd_g_i16x8_replace_lane_l1(simd_g_from(a), x)), simd_i16x8_replace_lane(a, 1, x); got != want {
				t.Fatalf("simd_i16x8_replace_lane lane 1 x=%v: %#x, scalar %#x", x, got, want)
			}
		}
		for _, x := range simdGScalars32 {
			if got, want := simd_g_to(simd_g_i16x8_replace_lane_l2(simd_g_from(a), x)), simd_i16x8_replace_lane(a, 2, x); got != want {
				t.Fatalf("simd_i16x8_replace_lane lane 2 x=%v: %#x, scalar %#x", x, got, want)
			}
		}
		for _, x := range simdGScalars32 {
			if got, want := simd_g_to(simd_g_i16x8_replace_lane_l3(simd_g_from(a), x)), simd_i16x8_replace_lane(a, 3, x); got != want {
				t.Fatalf("simd_i16x8_replace_lane lane 3 x=%v: %#x, scalar %#x", x, got, want)
			}
		}
		for _, x := range simdGScalars32 {
			if got, want := simd_g_to(simd_g_i16x8_replace_lane_l4(simd_g_from(a), x)), simd_i16x8_replace_lane(a, 4, x); got != want {
				t.Fatalf("simd_i16x8_replace_lane lane 4 x=%v: %#x, scalar %#x", x, got, want)
			}
		}
		for _, x := range simdGScalars32 {
			if got, want := simd_g_to(simd_g_i16x8_replace_lane_l5(simd_g_from(a), x)), simd_i16x8_replace_lane(a, 5, x); got != want {
				t.Fatalf("simd_i16x8_replace_lane lane 5 x=%v: %#x, scalar %#x", x, got, want)
			}
		}
		for _, x := range simdGScalars32 {
			if got, want := simd_g_to(simd_g_i16x8_replace_lane_l6(simd_g_from(a), x)), simd_i16x8_replace_lane(a, 6, x); got != want {
				t.Fatalf("simd_i16x8_replace_lane lane 6 x=%v: %#x, scalar %#x", x, got, want)
			}
		}
		for _, x := range simdGScalars32 {
			if got, want := simd_g_to(simd_g_i16x8_replace_lane_l7(simd_g_from(a), x)), simd_i16x8_replace_lane(a, 7, x); got != want {
				t.Fatalf("simd_i16x8_replace_lane lane 7 x=%v: %#x, scalar %#x", x, got, want)
			}
		}
		if got, want := simd_g_i32x4_extract_lane_l0(simd_g_from(a)), simd_i32x4_extract_lane(a, 0); got != want {
			t.Fatalf("simd_i32x4_extract_lane lane 0: %v, scalar %v", got, want)
		}
		if got, want := simd_g_i32x4_extract_lane_l1(simd_g_from(a)), simd_i32x4_extract_lane(a, 1); got != want {
			t.Fatalf("simd_i32x4_extract_lane lane 1: %v, scalar %v", got, want)
		}
		if got, want := simd_g_i32x4_extract_lane_l2(simd_g_from(a)), simd_i32x4_extract_lane(a, 2); got != want {
			t.Fatalf("simd_i32x4_extract_lane lane 2: %v, scalar %v", got, want)
		}
		if got, want := simd_g_i32x4_extract_lane_l3(simd_g_from(a)), simd_i32x4_extract_lane(a, 3); got != want {
			t.Fatalf("simd_i32x4_extract_lane lane 3: %v, scalar %v", got, want)
		}
		for _, x := range simdGScalars32 {
			if got, want := simd_g_to(simd_g_i32x4_replace_lane_l0(simd_g_from(a), x)), simd_i32x4_replace_lane(a, 0, x); got != want {
				t.Fatalf("simd_i32x4_replace_lane lane 0 x=%v: %#x, scalar %#x", x, got, want)
			}
		}
		for _, x := range simdGScalars32 {
			if got, want := simd_g_to(simd_g_i32x4_replace_lane_l1(simd_g_from(a), x)), simd_i32x4_replace_lane(a, 1, x); got != want {
				t.Fatalf("simd_i32x4_replace_lane lane 1 x=%v: %#x, scalar %#x", x, got, want)
			}
		}
		for _, x := range simdGScalars32 {
			if got, want := simd_g_to(simd_g_i32x4_replace_lane_l2(simd_g_from(a), x)), simd_i32x4_replace_lane(a, 2, x); got != want {
				t.Fatalf("simd_i32x4_replace_lane lane 2 x=%v: %#x, scalar %#x", x, got, want)
			}
		}
		for _, x := range simdGScalars32 {
			if got, want := simd_g_to(simd_g_i32x4_replace_lane_l3(simd_g_from(a), x)), simd_i32x4_replace_lane(a, 3, x); got != want {
				t.Fatalf("simd_i32x4_replace_lane lane 3 x=%v: %#x, scalar %#x", x, got, want)
			}
		}
		if got, want := simd_g_i64x2_extract_lane_l0(simd_g_from(a)), simd_i64x2_extract_lane(a, 0); got != want {
			t.Fatalf("simd_i64x2_extract_lane lane 0: %v, scalar %v", got, want)
		}
		if got, want := simd_g_i64x2_extract_lane_l1(simd_g_from(a)), simd_i64x2_extract_lane(a, 1); got != want {
			t.Fatalf("simd_i64x2_extract_lane lane 1: %v, scalar %v", got, want)
		}
		for _, x := range simdGScalars64 {
			if got, want := simd_g_to(simd_g_i64x2_replace_lane_l0(simd_g_from(a), x)), simd_i64x2_replace_lane(a, 0, x); got != want {
				t.Fatalf("simd_i64x2_replace_lane lane 0 x=%v: %#x, scalar %#x", x, got, want)
			}
		}
		for _, x := range simdGScalars64 {
			if got, want := simd_g_to(simd_g_i64x2_replace_lane_l1(simd_g_from(a), x)), simd_i64x2_replace_lane(a, 1, x); got != want {
				t.Fatalf("simd_i64x2_replace_lane lane 1 x=%v: %#x, scalar %#x", x, got, want)
			}
		}
		if got, want := simd_g_f32x4_extract_lane_l0(simd_g_from(a)), simd_f32x4_extract_lane(a, 0); math.Float32bits(got) != math.Float32bits(want) {
			t.Fatalf("simd_f32x4_extract_lane lane 0: %v, scalar %v", got, want)
		}
		if got, want := simd_g_f32x4_extract_lane_l1(simd_g_from(a)), simd_f32x4_extract_lane(a, 1); math.Float32bits(got) != math.Float32bits(want) {
			t.Fatalf("simd_f32x4_extract_lane lane 1: %v, scalar %v", got, want)
		}
		if got, want := simd_g_f32x4_extract_lane_l2(simd_g_from(a)), simd_f32x4_extract_lane(a, 2); math.Float32bits(got) != math.Float32bits(want) {
			t.Fatalf("simd_f32x4_extract_lane lane 2: %v, scalar %v", got, want)
		}
		if got, want := simd_g_f32x4_extract_lane_l3(simd_g_from(a)), simd_f32x4_extract_lane(a, 3); math.Float32bits(got) != math.Float32bits(want) {
			t.Fatalf("simd_f32x4_extract_lane lane 3: %v, scalar %v", got, want)
		}
		for _, x := range simdGFloats32 {
			if got, want := simd_g_to(simd_g_f32x4_replace_lane_l0(simd_g_from(a), x)), simd_f32x4_replace_lane(a, 0, x); got != want {
				t.Fatalf("simd_f32x4_replace_lane lane 0 x=%v: %#x, scalar %#x", x, got, want)
			}
		}
		for _, x := range simdGFloats32 {
			if got, want := simd_g_to(simd_g_f32x4_replace_lane_l1(simd_g_from(a), x)), simd_f32x4_replace_lane(a, 1, x); got != want {
				t.Fatalf("simd_f32x4_replace_lane lane 1 x=%v: %#x, scalar %#x", x, got, want)
			}
		}
		for _, x := range simdGFloats32 {
			if got, want := simd_g_to(simd_g_f32x4_replace_lane_l2(simd_g_from(a), x)), simd_f32x4_replace_lane(a, 2, x); got != want {
				t.Fatalf("simd_f32x4_replace_lane lane 2 x=%v: %#x, scalar %#x", x, got, want)
			}
		}
		for _, x := range simdGFloats32 {
			if got, want := simd_g_to(simd_g_f32x4_replace_lane_l3(simd_g_from(a), x)), simd_f32x4_replace_lane(a, 3, x); got != want {
				t.Fatalf("simd_f32x4_replace_lane lane 3 x=%v: %#x, scalar %#x", x, got, want)
			}
		}
		if got, want := simd_g_f64x2_extract_lane_l0(simd_g_from(a)), simd_f64x2_extract_lane(a, 0); math.Float64bits(got) != math.Float64bits(want) {
			t.Fatalf("simd_f64x2_extract_lane lane 0: %v, scalar %v", got, want)
		}
		if got, want := simd_g_f64x2_extract_lane_l1(simd_g_from(a)), simd_f64x2_extract_lane(a, 1); math.Float64bits(got) != math.Float64bits(want) {
			t.Fatalf("simd_f64x2_extract_lane lane 1: %v, scalar %v", got, want)
		}
		for _, x := range simdGFloats64 {
			if got, want := simd_g_to(simd_g_f64x2_replace_lane_l0(simd_g_from(a), x)), simd_f64x2_replace_lane(a, 0, x); got != want {
				t.Fatalf("simd_f64x2_replace_lane lane 0 x=%v: %#x, scalar %#x", x, got, want)
			}
		}
		for _, x := range simdGFloats64 {
			if got, want := simd_g_to(simd_g_f64x2_replace_lane_l1(simd_g_from(a), x)), simd_f64x2_replace_lane(a, 1, x); got != want {
				t.Fatalf("simd_f64x2_replace_lane lane 1 x=%v: %#x, scalar %#x", x, got, want)
			}
		}
	}
}

func TestGoSIMDMemory(t *testing.T) {
	m := memTestModule(t, 256)
	for _, addr := range []int32{0, 1, 3, 8, 16, 100, 200, 239, 240, 248, 252, 255} {
		for _, off := range []int32{0, 1, 16} {
			for _, v := range simdGCorpus[:8] {
				{
					var got [2]uint64
					gt := simdGTrap(func() { got = simd_g_to(simd_g_v128_load(m, addr, off)) })
					var want [2]uint64
					wt := simdGTrap(func() { want = simd_v128_load(m, addr, off) })
					if gt != wt || got != want {
						t.Fatalf("simd_v128_load addr %d+%d: got %#x trap=%v, want %#x trap=%v", addr, off, got, gt, want, wt)
					}
				}
				{
					m2 := memTestModule(t, 256)
					gt := simdGTrap(func() { simd_g_v128_store(m2, addr, off, simd_g_from(v)) })
					m3 := memTestModule(t, 256)
					wt := simdGTrap(func() { simd_v128_store(m3, addr, off, v) })
					if gt != wt || !bytes.Equal(m2.memory, m3.memory) {
						t.Fatalf("simd_v128_store addr %d+%d: trap=%v want trap=%v, memory differs", addr, off, gt, wt)
					}
				}
				{
					var got [2]uint64
					gt := simdGTrap(func() { got = simd_g_to(simd_g_v128_load8x8_s(m, addr, off)) })
					var want [2]uint64
					wt := simdGTrap(func() { want = simd_v128_load8x8_s(m, addr, off) })
					if gt != wt || got != want {
						t.Fatalf("simd_v128_load8x8_s addr %d+%d: got %#x trap=%v, want %#x trap=%v", addr, off, got, gt, want, wt)
					}
				}
				{
					var got [2]uint64
					gt := simdGTrap(func() { got = simd_g_to(simd_g_v128_load8x8_u(m, addr, off)) })
					var want [2]uint64
					wt := simdGTrap(func() { want = simd_v128_load8x8_u(m, addr, off) })
					if gt != wt || got != want {
						t.Fatalf("simd_v128_load8x8_u addr %d+%d: got %#x trap=%v, want %#x trap=%v", addr, off, got, gt, want, wt)
					}
				}
				{
					var got [2]uint64
					gt := simdGTrap(func() { got = simd_g_to(simd_g_v128_load16x4_s(m, addr, off)) })
					var want [2]uint64
					wt := simdGTrap(func() { want = simd_v128_load16x4_s(m, addr, off) })
					if gt != wt || got != want {
						t.Fatalf("simd_v128_load16x4_s addr %d+%d: got %#x trap=%v, want %#x trap=%v", addr, off, got, gt, want, wt)
					}
				}
				{
					var got [2]uint64
					gt := simdGTrap(func() { got = simd_g_to(simd_g_v128_load16x4_u(m, addr, off)) })
					var want [2]uint64
					wt := simdGTrap(func() { want = simd_v128_load16x4_u(m, addr, off) })
					if gt != wt || got != want {
						t.Fatalf("simd_v128_load16x4_u addr %d+%d: got %#x trap=%v, want %#x trap=%v", addr, off, got, gt, want, wt)
					}
				}
				{
					var got [2]uint64
					gt := simdGTrap(func() { got = simd_g_to(simd_g_v128_load32x2_s(m, addr, off)) })
					var want [2]uint64
					wt := simdGTrap(func() { want = simd_v128_load32x2_s(m, addr, off) })
					if gt != wt || got != want {
						t.Fatalf("simd_v128_load32x2_s addr %d+%d: got %#x trap=%v, want %#x trap=%v", addr, off, got, gt, want, wt)
					}
				}
				{
					var got [2]uint64
					gt := simdGTrap(func() { got = simd_g_to(simd_g_v128_load32x2_u(m, addr, off)) })
					var want [2]uint64
					wt := simdGTrap(func() { want = simd_v128_load32x2_u(m, addr, off) })
					if gt != wt || got != want {
						t.Fatalf("simd_v128_load32x2_u addr %d+%d: got %#x trap=%v, want %#x trap=%v", addr, off, got, gt, want, wt)
					}
				}
				{
					var got [2]uint64
					gt := simdGTrap(func() { got = simd_g_to(simd_g_v128_load8_splat(m, addr, off)) })
					var want [2]uint64
					wt := simdGTrap(func() { want = simd_v128_load8_splat(m, addr, off) })
					if gt != wt || got != want {
						t.Fatalf("simd_v128_load8_splat addr %d+%d: got %#x trap=%v, want %#x trap=%v", addr, off, got, gt, want, wt)
					}
				}
				{
					var got [2]uint64
					gt := simdGTrap(func() { got = simd_g_to(simd_g_v128_load16_splat(m, addr, off)) })
					var want [2]uint64
					wt := simdGTrap(func() { want = simd_v128_load16_splat(m, addr, off) })
					if gt != wt || got != want {
						t.Fatalf("simd_v128_load16_splat addr %d+%d: got %#x trap=%v, want %#x trap=%v", addr, off, got, gt, want, wt)
					}
				}
				{
					var got [2]uint64
					gt := simdGTrap(func() { got = simd_g_to(simd_g_v128_load32_splat(m, addr, off)) })
					var want [2]uint64
					wt := simdGTrap(func() { want = simd_v128_load32_splat(m, addr, off) })
					if gt != wt || got != want {
						t.Fatalf("simd_v128_load32_splat addr %d+%d: got %#x trap=%v, want %#x trap=%v", addr, off, got, gt, want, wt)
					}
				}
				{
					var got [2]uint64
					gt := simdGTrap(func() { got = simd_g_to(simd_g_v128_load64_splat(m, addr, off)) })
					var want [2]uint64
					wt := simdGTrap(func() { want = simd_v128_load64_splat(m, addr, off) })
					if gt != wt || got != want {
						t.Fatalf("simd_v128_load64_splat addr %d+%d: got %#x trap=%v, want %#x trap=%v", addr, off, got, gt, want, wt)
					}
				}
				{
					var got [2]uint64
					gt := simdGTrap(func() { got = simd_g_to(simd_g_v128_load32_zero(m, addr, off)) })
					var want [2]uint64
					wt := simdGTrap(func() { want = simd_v128_load32_zero(m, addr, off) })
					if gt != wt || got != want {
						t.Fatalf("simd_v128_load32_zero addr %d+%d: got %#x trap=%v, want %#x trap=%v", addr, off, got, gt, want, wt)
					}
				}
				{
					var got [2]uint64
					gt := simdGTrap(func() { got = simd_g_to(simd_g_v128_load64_zero(m, addr, off)) })
					var want [2]uint64
					wt := simdGTrap(func() { want = simd_v128_load64_zero(m, addr, off) })
					if gt != wt || got != want {
						t.Fatalf("simd_v128_load64_zero addr %d+%d: got %#x trap=%v, want %#x trap=%v", addr, off, got, gt, want, wt)
					}
				}
				{
					var got [2]uint64
					gt := simdGTrap(func() { got = simd_g_to(simd_g_v128_load8_lane_l0(m, addr, off, simd_g_from(v))) })
					var want [2]uint64
					wt := simdGTrap(func() { want = simd_v128_load8_lane(m, addr, off, 0, v) })
					if gt != wt || got != want {
						t.Fatalf("simd_v128_load8_lane lane 0 addr %d+%d: got %#x trap=%v, want %#x trap=%v", addr, off, got, gt, want, wt)
					}
				}
				{
					var got [2]uint64
					gt := simdGTrap(func() { got = simd_g_to(simd_g_v128_load8_lane_l1(m, addr, off, simd_g_from(v))) })
					var want [2]uint64
					wt := simdGTrap(func() { want = simd_v128_load8_lane(m, addr, off, 1, v) })
					if gt != wt || got != want {
						t.Fatalf("simd_v128_load8_lane lane 1 addr %d+%d: got %#x trap=%v, want %#x trap=%v", addr, off, got, gt, want, wt)
					}
				}
				{
					var got [2]uint64
					gt := simdGTrap(func() { got = simd_g_to(simd_g_v128_load8_lane_l2(m, addr, off, simd_g_from(v))) })
					var want [2]uint64
					wt := simdGTrap(func() { want = simd_v128_load8_lane(m, addr, off, 2, v) })
					if gt != wt || got != want {
						t.Fatalf("simd_v128_load8_lane lane 2 addr %d+%d: got %#x trap=%v, want %#x trap=%v", addr, off, got, gt, want, wt)
					}
				}
				{
					var got [2]uint64
					gt := simdGTrap(func() { got = simd_g_to(simd_g_v128_load8_lane_l3(m, addr, off, simd_g_from(v))) })
					var want [2]uint64
					wt := simdGTrap(func() { want = simd_v128_load8_lane(m, addr, off, 3, v) })
					if gt != wt || got != want {
						t.Fatalf("simd_v128_load8_lane lane 3 addr %d+%d: got %#x trap=%v, want %#x trap=%v", addr, off, got, gt, want, wt)
					}
				}
				{
					var got [2]uint64
					gt := simdGTrap(func() { got = simd_g_to(simd_g_v128_load8_lane_l4(m, addr, off, simd_g_from(v))) })
					var want [2]uint64
					wt := simdGTrap(func() { want = simd_v128_load8_lane(m, addr, off, 4, v) })
					if gt != wt || got != want {
						t.Fatalf("simd_v128_load8_lane lane 4 addr %d+%d: got %#x trap=%v, want %#x trap=%v", addr, off, got, gt, want, wt)
					}
				}
				{
					var got [2]uint64
					gt := simdGTrap(func() { got = simd_g_to(simd_g_v128_load8_lane_l5(m, addr, off, simd_g_from(v))) })
					var want [2]uint64
					wt := simdGTrap(func() { want = simd_v128_load8_lane(m, addr, off, 5, v) })
					if gt != wt || got != want {
						t.Fatalf("simd_v128_load8_lane lane 5 addr %d+%d: got %#x trap=%v, want %#x trap=%v", addr, off, got, gt, want, wt)
					}
				}
				{
					var got [2]uint64
					gt := simdGTrap(func() { got = simd_g_to(simd_g_v128_load8_lane_l6(m, addr, off, simd_g_from(v))) })
					var want [2]uint64
					wt := simdGTrap(func() { want = simd_v128_load8_lane(m, addr, off, 6, v) })
					if gt != wt || got != want {
						t.Fatalf("simd_v128_load8_lane lane 6 addr %d+%d: got %#x trap=%v, want %#x trap=%v", addr, off, got, gt, want, wt)
					}
				}
				{
					var got [2]uint64
					gt := simdGTrap(func() { got = simd_g_to(simd_g_v128_load8_lane_l7(m, addr, off, simd_g_from(v))) })
					var want [2]uint64
					wt := simdGTrap(func() { want = simd_v128_load8_lane(m, addr, off, 7, v) })
					if gt != wt || got != want {
						t.Fatalf("simd_v128_load8_lane lane 7 addr %d+%d: got %#x trap=%v, want %#x trap=%v", addr, off, got, gt, want, wt)
					}
				}
				{
					var got [2]uint64
					gt := simdGTrap(func() { got = simd_g_to(simd_g_v128_load8_lane_l8(m, addr, off, simd_g_from(v))) })
					var want [2]uint64
					wt := simdGTrap(func() { want = simd_v128_load8_lane(m, addr, off, 8, v) })
					if gt != wt || got != want {
						t.Fatalf("simd_v128_load8_lane lane 8 addr %d+%d: got %#x trap=%v, want %#x trap=%v", addr, off, got, gt, want, wt)
					}
				}
				{
					var got [2]uint64
					gt := simdGTrap(func() { got = simd_g_to(simd_g_v128_load8_lane_l9(m, addr, off, simd_g_from(v))) })
					var want [2]uint64
					wt := simdGTrap(func() { want = simd_v128_load8_lane(m, addr, off, 9, v) })
					if gt != wt || got != want {
						t.Fatalf("simd_v128_load8_lane lane 9 addr %d+%d: got %#x trap=%v, want %#x trap=%v", addr, off, got, gt, want, wt)
					}
				}
				{
					var got [2]uint64
					gt := simdGTrap(func() { got = simd_g_to(simd_g_v128_load8_lane_l10(m, addr, off, simd_g_from(v))) })
					var want [2]uint64
					wt := simdGTrap(func() { want = simd_v128_load8_lane(m, addr, off, 10, v) })
					if gt != wt || got != want {
						t.Fatalf("simd_v128_load8_lane lane 10 addr %d+%d: got %#x trap=%v, want %#x trap=%v", addr, off, got, gt, want, wt)
					}
				}
				{
					var got [2]uint64
					gt := simdGTrap(func() { got = simd_g_to(simd_g_v128_load8_lane_l11(m, addr, off, simd_g_from(v))) })
					var want [2]uint64
					wt := simdGTrap(func() { want = simd_v128_load8_lane(m, addr, off, 11, v) })
					if gt != wt || got != want {
						t.Fatalf("simd_v128_load8_lane lane 11 addr %d+%d: got %#x trap=%v, want %#x trap=%v", addr, off, got, gt, want, wt)
					}
				}
				{
					var got [2]uint64
					gt := simdGTrap(func() { got = simd_g_to(simd_g_v128_load8_lane_l12(m, addr, off, simd_g_from(v))) })
					var want [2]uint64
					wt := simdGTrap(func() { want = simd_v128_load8_lane(m, addr, off, 12, v) })
					if gt != wt || got != want {
						t.Fatalf("simd_v128_load8_lane lane 12 addr %d+%d: got %#x trap=%v, want %#x trap=%v", addr, off, got, gt, want, wt)
					}
				}
				{
					var got [2]uint64
					gt := simdGTrap(func() { got = simd_g_to(simd_g_v128_load8_lane_l13(m, addr, off, simd_g_from(v))) })
					var want [2]uint64
					wt := simdGTrap(func() { want = simd_v128_load8_lane(m, addr, off, 13, v) })
					if gt != wt || got != want {
						t.Fatalf("simd_v128_load8_lane lane 13 addr %d+%d: got %#x trap=%v, want %#x trap=%v", addr, off, got, gt, want, wt)
					}
				}
				{
					var got [2]uint64
					gt := simdGTrap(func() { got = simd_g_to(simd_g_v128_load8_lane_l14(m, addr, off, simd_g_from(v))) })
					var want [2]uint64
					wt := simdGTrap(func() { want = simd_v128_load8_lane(m, addr, off, 14, v) })
					if gt != wt || got != want {
						t.Fatalf("simd_v128_load8_lane lane 14 addr %d+%d: got %#x trap=%v, want %#x trap=%v", addr, off, got, gt, want, wt)
					}
				}
				{
					var got [2]uint64
					gt := simdGTrap(func() { got = simd_g_to(simd_g_v128_load8_lane_l15(m, addr, off, simd_g_from(v))) })
					var want [2]uint64
					wt := simdGTrap(func() { want = simd_v128_load8_lane(m, addr, off, 15, v) })
					if gt != wt || got != want {
						t.Fatalf("simd_v128_load8_lane lane 15 addr %d+%d: got %#x trap=%v, want %#x trap=%v", addr, off, got, gt, want, wt)
					}
				}
				{
					var got [2]uint64
					gt := simdGTrap(func() { got = simd_g_to(simd_g_v128_load16_lane_l0(m, addr, off, simd_g_from(v))) })
					var want [2]uint64
					wt := simdGTrap(func() { want = simd_v128_load16_lane(m, addr, off, 0, v) })
					if gt != wt || got != want {
						t.Fatalf("simd_v128_load16_lane lane 0 addr %d+%d: got %#x trap=%v, want %#x trap=%v", addr, off, got, gt, want, wt)
					}
				}
				{
					var got [2]uint64
					gt := simdGTrap(func() { got = simd_g_to(simd_g_v128_load16_lane_l1(m, addr, off, simd_g_from(v))) })
					var want [2]uint64
					wt := simdGTrap(func() { want = simd_v128_load16_lane(m, addr, off, 1, v) })
					if gt != wt || got != want {
						t.Fatalf("simd_v128_load16_lane lane 1 addr %d+%d: got %#x trap=%v, want %#x trap=%v", addr, off, got, gt, want, wt)
					}
				}
				{
					var got [2]uint64
					gt := simdGTrap(func() { got = simd_g_to(simd_g_v128_load16_lane_l2(m, addr, off, simd_g_from(v))) })
					var want [2]uint64
					wt := simdGTrap(func() { want = simd_v128_load16_lane(m, addr, off, 2, v) })
					if gt != wt || got != want {
						t.Fatalf("simd_v128_load16_lane lane 2 addr %d+%d: got %#x trap=%v, want %#x trap=%v", addr, off, got, gt, want, wt)
					}
				}
				{
					var got [2]uint64
					gt := simdGTrap(func() { got = simd_g_to(simd_g_v128_load16_lane_l3(m, addr, off, simd_g_from(v))) })
					var want [2]uint64
					wt := simdGTrap(func() { want = simd_v128_load16_lane(m, addr, off, 3, v) })
					if gt != wt || got != want {
						t.Fatalf("simd_v128_load16_lane lane 3 addr %d+%d: got %#x trap=%v, want %#x trap=%v", addr, off, got, gt, want, wt)
					}
				}
				{
					var got [2]uint64
					gt := simdGTrap(func() { got = simd_g_to(simd_g_v128_load16_lane_l4(m, addr, off, simd_g_from(v))) })
					var want [2]uint64
					wt := simdGTrap(func() { want = simd_v128_load16_lane(m, addr, off, 4, v) })
					if gt != wt || got != want {
						t.Fatalf("simd_v128_load16_lane lane 4 addr %d+%d: got %#x trap=%v, want %#x trap=%v", addr, off, got, gt, want, wt)
					}
				}
				{
					var got [2]uint64
					gt := simdGTrap(func() { got = simd_g_to(simd_g_v128_load16_lane_l5(m, addr, off, simd_g_from(v))) })
					var want [2]uint64
					wt := simdGTrap(func() { want = simd_v128_load16_lane(m, addr, off, 5, v) })
					if gt != wt || got != want {
						t.Fatalf("simd_v128_load16_lane lane 5 addr %d+%d: got %#x trap=%v, want %#x trap=%v", addr, off, got, gt, want, wt)
					}
				}
				{
					var got [2]uint64
					gt := simdGTrap(func() { got = simd_g_to(simd_g_v128_load16_lane_l6(m, addr, off, simd_g_from(v))) })
					var want [2]uint64
					wt := simdGTrap(func() { want = simd_v128_load16_lane(m, addr, off, 6, v) })
					if gt != wt || got != want {
						t.Fatalf("simd_v128_load16_lane lane 6 addr %d+%d: got %#x trap=%v, want %#x trap=%v", addr, off, got, gt, want, wt)
					}
				}
				{
					var got [2]uint64
					gt := simdGTrap(func() { got = simd_g_to(simd_g_v128_load16_lane_l7(m, addr, off, simd_g_from(v))) })
					var want [2]uint64
					wt := simdGTrap(func() { want = simd_v128_load16_lane(m, addr, off, 7, v) })
					if gt != wt || got != want {
						t.Fatalf("simd_v128_load16_lane lane 7 addr %d+%d: got %#x trap=%v, want %#x trap=%v", addr, off, got, gt, want, wt)
					}
				}
				{
					var got [2]uint64
					gt := simdGTrap(func() { got = simd_g_to(simd_g_v128_load32_lane_l0(m, addr, off, simd_g_from(v))) })
					var want [2]uint64
					wt := simdGTrap(func() { want = simd_v128_load32_lane(m, addr, off, 0, v) })
					if gt != wt || got != want {
						t.Fatalf("simd_v128_load32_lane lane 0 addr %d+%d: got %#x trap=%v, want %#x trap=%v", addr, off, got, gt, want, wt)
					}
				}
				{
					var got [2]uint64
					gt := simdGTrap(func() { got = simd_g_to(simd_g_v128_load32_lane_l1(m, addr, off, simd_g_from(v))) })
					var want [2]uint64
					wt := simdGTrap(func() { want = simd_v128_load32_lane(m, addr, off, 1, v) })
					if gt != wt || got != want {
						t.Fatalf("simd_v128_load32_lane lane 1 addr %d+%d: got %#x trap=%v, want %#x trap=%v", addr, off, got, gt, want, wt)
					}
				}
				{
					var got [2]uint64
					gt := simdGTrap(func() { got = simd_g_to(simd_g_v128_load32_lane_l2(m, addr, off, simd_g_from(v))) })
					var want [2]uint64
					wt := simdGTrap(func() { want = simd_v128_load32_lane(m, addr, off, 2, v) })
					if gt != wt || got != want {
						t.Fatalf("simd_v128_load32_lane lane 2 addr %d+%d: got %#x trap=%v, want %#x trap=%v", addr, off, got, gt, want, wt)
					}
				}
				{
					var got [2]uint64
					gt := simdGTrap(func() { got = simd_g_to(simd_g_v128_load32_lane_l3(m, addr, off, simd_g_from(v))) })
					var want [2]uint64
					wt := simdGTrap(func() { want = simd_v128_load32_lane(m, addr, off, 3, v) })
					if gt != wt || got != want {
						t.Fatalf("simd_v128_load32_lane lane 3 addr %d+%d: got %#x trap=%v, want %#x trap=%v", addr, off, got, gt, want, wt)
					}
				}
				{
					var got [2]uint64
					gt := simdGTrap(func() { got = simd_g_to(simd_g_v128_load64_lane_l0(m, addr, off, simd_g_from(v))) })
					var want [2]uint64
					wt := simdGTrap(func() { want = simd_v128_load64_lane(m, addr, off, 0, v) })
					if gt != wt || got != want {
						t.Fatalf("simd_v128_load64_lane lane 0 addr %d+%d: got %#x trap=%v, want %#x trap=%v", addr, off, got, gt, want, wt)
					}
				}
				{
					var got [2]uint64
					gt := simdGTrap(func() { got = simd_g_to(simd_g_v128_load64_lane_l1(m, addr, off, simd_g_from(v))) })
					var want [2]uint64
					wt := simdGTrap(func() { want = simd_v128_load64_lane(m, addr, off, 1, v) })
					if gt != wt || got != want {
						t.Fatalf("simd_v128_load64_lane lane 1 addr %d+%d: got %#x trap=%v, want %#x trap=%v", addr, off, got, gt, want, wt)
					}
				}
				{
					m2 := memTestModule(t, 256)
					gt := simdGTrap(func() { simd_g_v128_store8_lane_l0(m2, addr, off, simd_g_from(v)) })
					m3 := memTestModule(t, 256)
					wt := simdGTrap(func() { simd_v128_store8_lane(m3, addr, off, 0, v) })
					if gt != wt || !bytes.Equal(m2.memory, m3.memory) {
						t.Fatalf("simd_v128_store8_lane lane 0 addr %d+%d: trap=%v want trap=%v, memory differs", addr, off, gt, wt)
					}
				}
				{
					m2 := memTestModule(t, 256)
					gt := simdGTrap(func() { simd_g_v128_store8_lane_l1(m2, addr, off, simd_g_from(v)) })
					m3 := memTestModule(t, 256)
					wt := simdGTrap(func() { simd_v128_store8_lane(m3, addr, off, 1, v) })
					if gt != wt || !bytes.Equal(m2.memory, m3.memory) {
						t.Fatalf("simd_v128_store8_lane lane 1 addr %d+%d: trap=%v want trap=%v, memory differs", addr, off, gt, wt)
					}
				}
				{
					m2 := memTestModule(t, 256)
					gt := simdGTrap(func() { simd_g_v128_store8_lane_l2(m2, addr, off, simd_g_from(v)) })
					m3 := memTestModule(t, 256)
					wt := simdGTrap(func() { simd_v128_store8_lane(m3, addr, off, 2, v) })
					if gt != wt || !bytes.Equal(m2.memory, m3.memory) {
						t.Fatalf("simd_v128_store8_lane lane 2 addr %d+%d: trap=%v want trap=%v, memory differs", addr, off, gt, wt)
					}
				}
				{
					m2 := memTestModule(t, 256)
					gt := simdGTrap(func() { simd_g_v128_store8_lane_l3(m2, addr, off, simd_g_from(v)) })
					m3 := memTestModule(t, 256)
					wt := simdGTrap(func() { simd_v128_store8_lane(m3, addr, off, 3, v) })
					if gt != wt || !bytes.Equal(m2.memory, m3.memory) {
						t.Fatalf("simd_v128_store8_lane lane 3 addr %d+%d: trap=%v want trap=%v, memory differs", addr, off, gt, wt)
					}
				}
				{
					m2 := memTestModule(t, 256)
					gt := simdGTrap(func() { simd_g_v128_store8_lane_l4(m2, addr, off, simd_g_from(v)) })
					m3 := memTestModule(t, 256)
					wt := simdGTrap(func() { simd_v128_store8_lane(m3, addr, off, 4, v) })
					if gt != wt || !bytes.Equal(m2.memory, m3.memory) {
						t.Fatalf("simd_v128_store8_lane lane 4 addr %d+%d: trap=%v want trap=%v, memory differs", addr, off, gt, wt)
					}
				}
				{
					m2 := memTestModule(t, 256)
					gt := simdGTrap(func() { simd_g_v128_store8_lane_l5(m2, addr, off, simd_g_from(v)) })
					m3 := memTestModule(t, 256)
					wt := simdGTrap(func() { simd_v128_store8_lane(m3, addr, off, 5, v) })
					if gt != wt || !bytes.Equal(m2.memory, m3.memory) {
						t.Fatalf("simd_v128_store8_lane lane 5 addr %d+%d: trap=%v want trap=%v, memory differs", addr, off, gt, wt)
					}
				}
				{
					m2 := memTestModule(t, 256)
					gt := simdGTrap(func() { simd_g_v128_store8_lane_l6(m2, addr, off, simd_g_from(v)) })
					m3 := memTestModule(t, 256)
					wt := simdGTrap(func() { simd_v128_store8_lane(m3, addr, off, 6, v) })
					if gt != wt || !bytes.Equal(m2.memory, m3.memory) {
						t.Fatalf("simd_v128_store8_lane lane 6 addr %d+%d: trap=%v want trap=%v, memory differs", addr, off, gt, wt)
					}
				}
				{
					m2 := memTestModule(t, 256)
					gt := simdGTrap(func() { simd_g_v128_store8_lane_l7(m2, addr, off, simd_g_from(v)) })
					m3 := memTestModule(t, 256)
					wt := simdGTrap(func() { simd_v128_store8_lane(m3, addr, off, 7, v) })
					if gt != wt || !bytes.Equal(m2.memory, m3.memory) {
						t.Fatalf("simd_v128_store8_lane lane 7 addr %d+%d: trap=%v want trap=%v, memory differs", addr, off, gt, wt)
					}
				}
				{
					m2 := memTestModule(t, 256)
					gt := simdGTrap(func() { simd_g_v128_store8_lane_l8(m2, addr, off, simd_g_from(v)) })
					m3 := memTestModule(t, 256)
					wt := simdGTrap(func() { simd_v128_store8_lane(m3, addr, off, 8, v) })
					if gt != wt || !bytes.Equal(m2.memory, m3.memory) {
						t.Fatalf("simd_v128_store8_lane lane 8 addr %d+%d: trap=%v want trap=%v, memory differs", addr, off, gt, wt)
					}
				}
				{
					m2 := memTestModule(t, 256)
					gt := simdGTrap(func() { simd_g_v128_store8_lane_l9(m2, addr, off, simd_g_from(v)) })
					m3 := memTestModule(t, 256)
					wt := simdGTrap(func() { simd_v128_store8_lane(m3, addr, off, 9, v) })
					if gt != wt || !bytes.Equal(m2.memory, m3.memory) {
						t.Fatalf("simd_v128_store8_lane lane 9 addr %d+%d: trap=%v want trap=%v, memory differs", addr, off, gt, wt)
					}
				}
				{
					m2 := memTestModule(t, 256)
					gt := simdGTrap(func() { simd_g_v128_store8_lane_l10(m2, addr, off, simd_g_from(v)) })
					m3 := memTestModule(t, 256)
					wt := simdGTrap(func() { simd_v128_store8_lane(m3, addr, off, 10, v) })
					if gt != wt || !bytes.Equal(m2.memory, m3.memory) {
						t.Fatalf("simd_v128_store8_lane lane 10 addr %d+%d: trap=%v want trap=%v, memory differs", addr, off, gt, wt)
					}
				}
				{
					m2 := memTestModule(t, 256)
					gt := simdGTrap(func() { simd_g_v128_store8_lane_l11(m2, addr, off, simd_g_from(v)) })
					m3 := memTestModule(t, 256)
					wt := simdGTrap(func() { simd_v128_store8_lane(m3, addr, off, 11, v) })
					if gt != wt || !bytes.Equal(m2.memory, m3.memory) {
						t.Fatalf("simd_v128_store8_lane lane 11 addr %d+%d: trap=%v want trap=%v, memory differs", addr, off, gt, wt)
					}
				}
				{
					m2 := memTestModule(t, 256)
					gt := simdGTrap(func() { simd_g_v128_store8_lane_l12(m2, addr, off, simd_g_from(v)) })
					m3 := memTestModule(t, 256)
					wt := simdGTrap(func() { simd_v128_store8_lane(m3, addr, off, 12, v) })
					if gt != wt || !bytes.Equal(m2.memory, m3.memory) {
						t.Fatalf("simd_v128_store8_lane lane 12 addr %d+%d: trap=%v want trap=%v, memory differs", addr, off, gt, wt)
					}
				}
				{
					m2 := memTestModule(t, 256)
					gt := simdGTrap(func() { simd_g_v128_store8_lane_l13(m2, addr, off, simd_g_from(v)) })
					m3 := memTestModule(t, 256)
					wt := simdGTrap(func() { simd_v128_store8_lane(m3, addr, off, 13, v) })
					if gt != wt || !bytes.Equal(m2.memory, m3.memory) {
						t.Fatalf("simd_v128_store8_lane lane 13 addr %d+%d: trap=%v want trap=%v, memory differs", addr, off, gt, wt)
					}
				}
				{
					m2 := memTestModule(t, 256)
					gt := simdGTrap(func() { simd_g_v128_store8_lane_l14(m2, addr, off, simd_g_from(v)) })
					m3 := memTestModule(t, 256)
					wt := simdGTrap(func() { simd_v128_store8_lane(m3, addr, off, 14, v) })
					if gt != wt || !bytes.Equal(m2.memory, m3.memory) {
						t.Fatalf("simd_v128_store8_lane lane 14 addr %d+%d: trap=%v want trap=%v, memory differs", addr, off, gt, wt)
					}
				}
				{
					m2 := memTestModule(t, 256)
					gt := simdGTrap(func() { simd_g_v128_store8_lane_l15(m2, addr, off, simd_g_from(v)) })
					m3 := memTestModule(t, 256)
					wt := simdGTrap(func() { simd_v128_store8_lane(m3, addr, off, 15, v) })
					if gt != wt || !bytes.Equal(m2.memory, m3.memory) {
						t.Fatalf("simd_v128_store8_lane lane 15 addr %d+%d: trap=%v want trap=%v, memory differs", addr, off, gt, wt)
					}
				}
				{
					m2 := memTestModule(t, 256)
					gt := simdGTrap(func() { simd_g_v128_store16_lane_l0(m2, addr, off, simd_g_from(v)) })
					m3 := memTestModule(t, 256)
					wt := simdGTrap(func() { simd_v128_store16_lane(m3, addr, off, 0, v) })
					if gt != wt || !bytes.Equal(m2.memory, m3.memory) {
						t.Fatalf("simd_v128_store16_lane lane 0 addr %d+%d: trap=%v want trap=%v, memory differs", addr, off, gt, wt)
					}
				}
				{
					m2 := memTestModule(t, 256)
					gt := simdGTrap(func() { simd_g_v128_store16_lane_l1(m2, addr, off, simd_g_from(v)) })
					m3 := memTestModule(t, 256)
					wt := simdGTrap(func() { simd_v128_store16_lane(m3, addr, off, 1, v) })
					if gt != wt || !bytes.Equal(m2.memory, m3.memory) {
						t.Fatalf("simd_v128_store16_lane lane 1 addr %d+%d: trap=%v want trap=%v, memory differs", addr, off, gt, wt)
					}
				}
				{
					m2 := memTestModule(t, 256)
					gt := simdGTrap(func() { simd_g_v128_store16_lane_l2(m2, addr, off, simd_g_from(v)) })
					m3 := memTestModule(t, 256)
					wt := simdGTrap(func() { simd_v128_store16_lane(m3, addr, off, 2, v) })
					if gt != wt || !bytes.Equal(m2.memory, m3.memory) {
						t.Fatalf("simd_v128_store16_lane lane 2 addr %d+%d: trap=%v want trap=%v, memory differs", addr, off, gt, wt)
					}
				}
				{
					m2 := memTestModule(t, 256)
					gt := simdGTrap(func() { simd_g_v128_store16_lane_l3(m2, addr, off, simd_g_from(v)) })
					m3 := memTestModule(t, 256)
					wt := simdGTrap(func() { simd_v128_store16_lane(m3, addr, off, 3, v) })
					if gt != wt || !bytes.Equal(m2.memory, m3.memory) {
						t.Fatalf("simd_v128_store16_lane lane 3 addr %d+%d: trap=%v want trap=%v, memory differs", addr, off, gt, wt)
					}
				}
				{
					m2 := memTestModule(t, 256)
					gt := simdGTrap(func() { simd_g_v128_store16_lane_l4(m2, addr, off, simd_g_from(v)) })
					m3 := memTestModule(t, 256)
					wt := simdGTrap(func() { simd_v128_store16_lane(m3, addr, off, 4, v) })
					if gt != wt || !bytes.Equal(m2.memory, m3.memory) {
						t.Fatalf("simd_v128_store16_lane lane 4 addr %d+%d: trap=%v want trap=%v, memory differs", addr, off, gt, wt)
					}
				}
				{
					m2 := memTestModule(t, 256)
					gt := simdGTrap(func() { simd_g_v128_store16_lane_l5(m2, addr, off, simd_g_from(v)) })
					m3 := memTestModule(t, 256)
					wt := simdGTrap(func() { simd_v128_store16_lane(m3, addr, off, 5, v) })
					if gt != wt || !bytes.Equal(m2.memory, m3.memory) {
						t.Fatalf("simd_v128_store16_lane lane 5 addr %d+%d: trap=%v want trap=%v, memory differs", addr, off, gt, wt)
					}
				}
				{
					m2 := memTestModule(t, 256)
					gt := simdGTrap(func() { simd_g_v128_store16_lane_l6(m2, addr, off, simd_g_from(v)) })
					m3 := memTestModule(t, 256)
					wt := simdGTrap(func() { simd_v128_store16_lane(m3, addr, off, 6, v) })
					if gt != wt || !bytes.Equal(m2.memory, m3.memory) {
						t.Fatalf("simd_v128_store16_lane lane 6 addr %d+%d: trap=%v want trap=%v, memory differs", addr, off, gt, wt)
					}
				}
				{
					m2 := memTestModule(t, 256)
					gt := simdGTrap(func() { simd_g_v128_store16_lane_l7(m2, addr, off, simd_g_from(v)) })
					m3 := memTestModule(t, 256)
					wt := simdGTrap(func() { simd_v128_store16_lane(m3, addr, off, 7, v) })
					if gt != wt || !bytes.Equal(m2.memory, m3.memory) {
						t.Fatalf("simd_v128_store16_lane lane 7 addr %d+%d: trap=%v want trap=%v, memory differs", addr, off, gt, wt)
					}
				}
				{
					m2 := memTestModule(t, 256)
					gt := simdGTrap(func() { simd_g_v128_store32_lane_l0(m2, addr, off, simd_g_from(v)) })
					m3 := memTestModule(t, 256)
					wt := simdGTrap(func() { simd_v128_store32_lane(m3, addr, off, 0, v) })
					if gt != wt || !bytes.Equal(m2.memory, m3.memory) {
						t.Fatalf("simd_v128_store32_lane lane 0 addr %d+%d: trap=%v want trap=%v, memory differs", addr, off, gt, wt)
					}
				}
				{
					m2 := memTestModule(t, 256)
					gt := simdGTrap(func() { simd_g_v128_store32_lane_l1(m2, addr, off, simd_g_from(v)) })
					m3 := memTestModule(t, 256)
					wt := simdGTrap(func() { simd_v128_store32_lane(m3, addr, off, 1, v) })
					if gt != wt || !bytes.Equal(m2.memory, m3.memory) {
						t.Fatalf("simd_v128_store32_lane lane 1 addr %d+%d: trap=%v want trap=%v, memory differs", addr, off, gt, wt)
					}
				}
				{
					m2 := memTestModule(t, 256)
					gt := simdGTrap(func() { simd_g_v128_store32_lane_l2(m2, addr, off, simd_g_from(v)) })
					m3 := memTestModule(t, 256)
					wt := simdGTrap(func() { simd_v128_store32_lane(m3, addr, off, 2, v) })
					if gt != wt || !bytes.Equal(m2.memory, m3.memory) {
						t.Fatalf("simd_v128_store32_lane lane 2 addr %d+%d: trap=%v want trap=%v, memory differs", addr, off, gt, wt)
					}
				}
				{
					m2 := memTestModule(t, 256)
					gt := simdGTrap(func() { simd_g_v128_store32_lane_l3(m2, addr, off, simd_g_from(v)) })
					m3 := memTestModule(t, 256)
					wt := simdGTrap(func() { simd_v128_store32_lane(m3, addr, off, 3, v) })
					if gt != wt || !bytes.Equal(m2.memory, m3.memory) {
						t.Fatalf("simd_v128_store32_lane lane 3 addr %d+%d: trap=%v want trap=%v, memory differs", addr, off, gt, wt)
					}
				}
				{
					m2 := memTestModule(t, 256)
					gt := simdGTrap(func() { simd_g_v128_store64_lane_l0(m2, addr, off, simd_g_from(v)) })
					m3 := memTestModule(t, 256)
					wt := simdGTrap(func() { simd_v128_store64_lane(m3, addr, off, 0, v) })
					if gt != wt || !bytes.Equal(m2.memory, m3.memory) {
						t.Fatalf("simd_v128_store64_lane lane 0 addr %d+%d: trap=%v want trap=%v, memory differs", addr, off, gt, wt)
					}
				}
				{
					m2 := memTestModule(t, 256)
					gt := simdGTrap(func() { simd_g_v128_store64_lane_l1(m2, addr, off, simd_g_from(v)) })
					m3 := memTestModule(t, 256)
					wt := simdGTrap(func() { simd_v128_store64_lane(m3, addr, off, 1, v) })
					if gt != wt || !bytes.Equal(m2.memory, m3.memory) {
						t.Fatalf("simd_v128_store64_lane lane 1 addr %d+%d: trap=%v want trap=%v, memory differs", addr, off, gt, wt)
					}
				}
			}
		}
	}
}

// simdGTrap runs f and reports whether it trapped (panicked).
func simdGTrap(f func()) (trapped bool) {
	defer func() {
		if recover() != nil {
			trapped = true
		}
	}()
	f()
	return false
}

var nan32 = math.Float32frombits(0x7fc00000)
var nan64 = math.Float64frombits(0x7ff8000000000000)
